### PR TITLE
use pypi class for python recipes (resolves #566)

### LINKED ISSUE #566: Update all python recipes to use the pypi bbclass
Motivated by the pull request at https://github.com/bulwahn/meta-ros/pull/12.

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by bulwahn** [comment]
I quickly tested this pull request with this build configuration:
```
Build Configuration:
BB_VERSION           = "1.35.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "i586-oe-linux"
MACHINE              = "qemux86"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "m32 i586"
TARGET_FPU           = ""
meta                 = "master:ced4ac760926ce43a937dad2be3b873b1beec6aa"
meta-oe              
meta-multimedia      
meta-python          = "master:e08670d4362b57373557fbe6b31cbffffa465acc"
meta-ros             = "use-pypi-class:58a843f99f4b63f76148bc714db553f7ee5e062c"
```

**Comment by bulwahn** [comment]
Hmm... I don't understand why this build is failing.

**Comment by rojkov** [comment]
Hm.. I guess I know what's wrong with CI - meta-openembedded get's added after meta-ros. But I'll fix this tomorrow. gtg now.

**Comment by rojkov** [comment]
I've fixed the order which layers get added in and re-triggered the build.

**Comment by rojkov** [comment]
Looks good to me. Merging...

**Pull request merged**
