### PR TITLE
README.md: Add "under construction" notice

### PR DESCRIPTION
**Pull request by herb-kuta-lge**
README.md: Add "under construction" notice

### CODE REVIEW

**Comment by bulwahn** [comment]
As you might have noticed, my focus and the support of other maintainers have moved to other projects. How about deciding on new maintainers and transfering this project from bmwcarit to ros?
This way, all links to bmwcarit/meta-ros are automatically forwarded to ros/meta-ros and the existing pull requests and issue tracker is not lost.

**Comment by bulwahn** [comment]
@herb-kuta-lge Could you propose this on discourse.ros.org in the OpenEmbedded category and ask for opinions and maintainers that would maintain the repository at this new location? Or do you want me to start the discussion on this topic?

**Comment by herb-kuta-lge** [comment]
@bulwahn I've asked Tully Foote to delete the forked ros/meta-ros and to accept the transfer of this one into ros -- see https://github.com/orgs/ros/teams/meta-ros-maintainers/discussions/1.

**Comment by bulwahn** [comment]
I cannot access that link as it seems, I only get an error 404.

**Comment by herb-kuta-lge** [comment]
I didn't realize the meta-ros-maintainers discussions are private. Here's what the link resolves to:

**Comment by herb-kuta-lge** [comment]
I didn't realize that the meta-ros-maintainers discussions are private. Here's what the link points to:

> From bmwcarit/meta-ros#629 (comment):
> 
> How about deciding on new maintainers and transfering this project from bmwcarit to ros?
> This way, all links to bmwcarit/meta-ros are automatically forwarded to ros/meta-ros and the existing pull requests and issue tracker is not lost.
> 
> @tfoote This would be a better way to go. Would you be willing to delete ros/meta-ros and accept the transfer of bmwcarit/meta-ros into ros in its place?

**Comment by tfoote** [comment]
Sure I can facilitate that. For the moment I've moved ros/meta-ros to https://github.com/ros/meta-ros-legacy-fork and to transfer this to the ros organization the easiest way will be to transfer it to me personally then I'll move it into the ros organization and update the permissions.

Before executing this it would be good to pre announce it on the OpenEmbedded channel to make sure that there's not potential issues that could hit people during or after the migration. Though Github's redirects will mean that most things will keep working without much disruption.

**Comment by andre-rosa** [comment]
> Before executing this it would be good to pre announce it on the OpenEmbedded channel to make sure that there's not potential issues that could hit people during or after the migration. Though Github's redirects will mean that most things will keep working without much disruption.

Thanks! Pre-announcement [here](https://discourse.ros.org/t/pre-announcement-a-new-home-for-meta-ros-under-ros-organization/9392).

**Comment by tfoote** [comment]
It's been over a week, so I think we can plan to make this move whenever it's convenient for you @bulwahn .

**Comment by windelbouwman** [comment]
This would be nice, I look forward to using a ROS2 dashing yocto layer! This will be the idea right?

**Comment by bulwahn** [comment]
@tfoote, I tried transfering it to you, but then got the response:

"You can only transfer a repository from an organization to yourself at this time."

I am the owner of the bmwcarit organisation and I am the admin of the meta-ros repository.

How can I transfer the repository to you or ros?

The help suggests that:

> If you have owner permissions in an organization or admin permissions to one of its repositories, you can transfer a repository owned by your organization to your personal user account or to another organization.

So can I simply transfer it to ros or should I just add you being an admin of this repository and then you can transfer it to your personal account?

**Comment by bulwahn** [comment]
@tfoote I just simply added you as Admin to meta-ros. Feel free to transfer it whenever you want.

**Comment by tfoote** [comment]
Thanks @bulwahn it's now available at ros/meta-ros

@herb-kuta-lge @andre-rosa Can you take some time to update the documentation for the new URL? Maybe edit this PR with those changes.

**Comment by herb-kuta-lge** [comment]
@bulwahn < I think you'll need to inform the maintainers of https://layers.openembedded.org/ that you've transferred ownership of meta-ros.

**Comment by herb-kuta-lge** [comment]
> Maybe edit this PR with those changes.

Done.

**Comment by shr-project** [comment]
> @bulwahn < I think you'll need to inform the maintainers of https://layers.openembedded.org/ that you've transferred ownership of meta-ros.

I've updated the repo url on https://layers.openembedded.org/layerindex/branch/master/layer/meta-ros/, can update the maintainers as well once there is an agreement who should be listed as a maintainer now.

**Review by lokesku — APPROVED** [review]
Looks good

**Pull request merged**
