### PR TITLE
Catkin fix v2

### PR DESCRIPTION
**Pull request by dominiquehunziker**
Supersedes PR: #376
Related issues: #331 #380

See [this](https://github.com/bmwcarit/meta-ros/issues/380#issuecomment-198489593) for a rough outline of the functionalities added (the issue relating to the missing libraries has been addressed).

### CODE REVIEW

**Comment by bulwahn** [comment]
Can you comment on the few TODO notes left in the commit? The travis CI reports that two patches do not have a Upstream-Status; do you have plans to adjust the upstream ROS packages to be cross-compilable, or are you already in discussion with the ROS maintainers?

**Comment by dominiquehunziker** [comment]
The TODO is not critical. It is a nice to have feature. Currently, it's also necessary to either create a setup script or add the relevant environment configuration as stated in the README.md. So, there is no loss of functionality; I just added it as a reminder.

I haven't made a decision yet whether I should try to push the two patches upstream. It is not a very clean solution to start with, i.e., initially I had a different approach in mind, but it would require bigger changes to catkin.
~~Also the current approach relies on the fact that gcc will prepend the configured sysroot automatically if the search path for header files are specified like this: `-I=/usr/include`. So, if a compiler different from gcc is used I'm not sure it will work. This might be a problem in general for this PR, not just for the suitability for an upstream PR.~~ Edit: After writing this answer I realized that I had missed an obvious fix for the search path for header files issue. Now the patch is also cleaner. Nevertheless, there is still an issue with the generated setup files as well as all the files templated on `@PYTHON_EXECUTABLE@`

**Comment by bulwahn** [comment]
From reviewing the changes, there are no further concerns from my side. The travis script still reports the two failures: Upstream-Status lines in patches are a good practice in the overall Yocto project, which is relatively easy to live up to and maintain.
On Monday or Tuesday, I will have time to actually run and build some test images with this PR and check if there are some issues on my local setup.

**Comment by jvgomez** [comment]
Just for the record: I was able to compile an image and also create a catkin package on the target machine. I haven't tested yet the cross-compilation.

**Comment by dominiquehunziker** [comment]
Note: There is an issue with the dependencies of the catkin package. The package should only be necessary if one wants to compile code on the target machine (otherwise catkin-runtime should be suffienent). It should, therefore, depend on the *-dev of gcc, etc. to install the header files, etc. However, we had this QA error when doing that -- I'm not sure how this should be handled.

**Comment by bulwahn** [comment]
@dominiquehunziker I hope that you can and will provide a new pull request with this feature. It is a good idea to get the feature running; unfortunately, I just did not have the spare time to test the pull request yet. Next time, I hope to find the time to do some minimal testing and merge the pull request.

**Comment by dominiquehunziker** [comment]
Yes, didn't realize that deleting the branch closed the PR. I'm working on a new version, but I'm also a bit short on time.

In the meanwhile I'm trying to push the necessary changes to catkin itself; though the changes will only affect kinetic-devel and probably won't be available in indigo.

**Comment by dominiquehunziker** [comment]
@bulwahn I don't know whether I should create a new PR for this, but [here](https://github.com/rapyuta/meta-ros) is the newest version of the catkin fix. It would be great if you could add your opinion on the [catkin PR](https://github.com/ros/catkin/pull/811), which is the same patch as applied in the meta-ros fork.

**Pull request closed without merging**
