### PR TITLE
ROS 2 Humble Hawksbill - honister branch

### PR DESCRIPTION
**Pull request by vmayoral**
**Progress tracking**:
- [x] Update recipes in `honister` branch against `humble` rosdistro using `superflore`
- [x] Fix recipes to build in `honister`
- [x] Testing and validation ([writeup](https://news.accelerationrobotics.com/ros2-humble-yocto-petalinux/))

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/branched-humble-call-for-beta-testing/25284/11

**Comment by rosterloh** [comment]
@vmayoral I'd love to be a beta tester

**Comment by vmayoral** [comment]
All right, as it is, recipes build for me in my workstation but there might some minor hiccups with the following recipes which required some manual hacking in my build directory:
- `cyclonedds`
- `orocos-kdl-vendor`

@rosterloh, feel free to share your feedback if you find time to test it.

**Comment by vmayoral** [comment]
Made a small *writeup* about how to reproduce things: https://news.accelerationrobotics.com/ros2-humble-yocto-petalinux/

Checked from my side, ready for review.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/branched-humble-call-for-beta-testing/25284/20

**Comment by jlamperez** [comment]
This is not working for me,

First I had this problem with `rosidl-adapter-native`  and `rmw-implementation_2.8.1-2.bb`

```
ERROR: Nothing PROVIDES 'rosidl-adapter-nativerosidl-adapter-native' (but /media/jlamperez/DATA/Xilinx/Kria/2022.1/Vitis-Tutorials/Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/ref_files/xilinx-kv260-starterkit-2022.1/project-spec/meta-ros/meta-ros2-humble/generated-recipes/rmw-implementation/rmw-implementation_2.8.1-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'launch-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['launch-ros', 'rclpy', 'rmw-implementation', 'rosidl-adapter-nativerosidl-adapter-native']
NOTE: Runtime target 'demo-nodes-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['demo-nodes-cpp', 'launch-ros', 'rclpy', 'rmw-implementation', 'rosidl-adapter-nativerosidl-adapter-native']
ERROR: Required build target 'petalinux-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['petalinux-image-minimal', 'demo-nodes-cpp', 'launch-ros', 'rclpy', 'rmw-implementation', 'rosidl-adapter-nativerosidl-adapter-native']
```

Solved with this,

```
--- a/meta-ros2-humble/recipes-bbappends/rmw-implementation/rmw-implementation_%.bbappend
+++ b/meta-ros2-humble/recipes-bbappends/rmw-implementation/rmw-implementation_%.bbappend
@@ -2,7 +2,7 @@
 
 ROS_BUILD_DEPENDS:remove = "${@bb.utils.contains('ROS_WORLD_SKIP_GROUPS', 'connext', 'rmw-connext-cpp rmw-connextdds', '', d)}"
 
-ROS_BUILD_DEPENDS:append = "rosidl-adapter-native"
+ROS_BUILD_DEPENDS:append = " rosidl-adapter-native"
 ROS_EXEC_DEPENDS:append = " \
     rmw-fastrtps-cpp \
     rmw-cyclonedds-cpp \
```

And now with `ament-cmake-test_1.3.1-2.bb` 

```
| -- Installing: blah/build/tmp/work/cortexa72-cortexa53-xilinx-linux/ament-cmake-test/1.3.1-2-r0/image/usr/share/ament_cmake_test/cmake/ament_add_test_label.cmake
| rm: cannot remove 'blah/build/tmp/work/cortexa72-cortexa53-xilinx-linux/ament-cmake-test/1.3.1-2-r0/image/home': No such file or directory
| WARNING: exit code 1 from a shell command.
ERROR: Task (blah/project-spec/meta-ros/meta-ros2-humble/generated-recipes/ament-cmake/ament-cmake-test_1.3.1-2.bb:do_install) failed with exit code '1'
```

This can be seen using `petalinux-build -c ament-cmake-test` . It seems that it can not remove an `image/home` directory, it is weird.

I don't have a solution.

**Comment by vmayoral** [comment]
The first patch doesn't make sense. Please provide a proper patch if meant as a contribution.  

Your second issue seems specific to your build environment. I'd recommend doing this in a clean environment and **with the right PetaLinux version**.

**Comment by jlamperez** [comment]
The first is just a space.

I am using a fresh PetaLinux 2022.1 project. The project is created in `/media/DATA/blah` instead of in `/home/blah`  and the `ament-cmake-test` is creating me a folder called `/media/DATA/petalinux_project/build/tmp/work/cortexa72-cortexa53-xilinx-linux/ament-cmake-test/1.3.1-2-r0/image/media/DATA/petalinux_project/build/tmp/work/cortexa72-cortexa53-xilinx-linux/ament-cmake-test/1.3.1-2-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/` if my petalinux project was in `/home` it would work well and it would remove the pointed `image/home` folder but this is not created and instead I got `image/media`

**Comment by jlamperez** [comment]
I think the problem is this [ament-cmake-test_%.bbappend](https://github.com/vmayoral/meta-ros/blob/honister-humble/meta-ros2-humble/recipes-bbappends/ament-cmake/ament-cmake-test_%25.bbappend)

**Comment by jlamperez** [comment]
Same problem with rosidl-cmake_%.bbappend and [this line](https://github.com/vmayoral/meta-ros/blob/honister-humble/meta-ros2-humble/recipes-bbappends/rosidl/rosidl-cmake_%25.bbappend#L11)

**Comment by jlamperez** [comment]
I am seeing a lot of bbappend recipes with same pattern

```
# ERROR: do_package: Files/directories were installed but not shipped in any package
#
do_install:append:class-target() {
    mkdir -p ${D}/usr/lib/python3.9/site-packages/
    mv ${D}${STAGING_DIR_NATIVE}/usr/lib/python3.9/site-packages/${ROS_BPN}* ${D}/usr/lib/python3.9/site-packages/
    rm -r ${D}/home

```

Can there be any other way for this?

I count more or less all this files are going to fail to me 

```
./recipes-bbappends/rosidl-dds/rosidl-generator-dds-idl_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl/rosidl-generator-cpp_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl/rosidl-typesupport-introspection-c_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl/rosidl-parser_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl/rosidl-generator-c_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl/rosidl-adapter_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/actionlib-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/std-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/diagnostic-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/geometry-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/visualization-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/sensor-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/shape-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/trajectory-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/std-srvs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/nav-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/common-interfaces/stereo-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-cpp_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-c_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rmw-dds-common/rmw-dds-common_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcutils/rcutils_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosbag2/rosbag2-interfaces_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosbag2/rosbag2-py_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/unique-identifier-msgs/unique-identifier-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/example-interfaces/example-interfaces_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/geometry2/tf2-py_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/geometry2/tf2-geometry-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/geometry2/tf2-kdl_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/geometry2/tf2-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/action-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/lifecycle-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/rcl-interfaces_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/rosgraph-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/statistics-msgs_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/builtin-interfaces_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rcl-interfaces/composition-interfaces_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-python/rosidl-generator-py_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-typesupport/rosidl-typesupport-cpp_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-typesupport/rosidl-typesupport-c_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/rosidl-typesupport/rosidl-typesupport-introspection-cpp_%.bbappend:    rm -r ${D}/home
./recipes-bbappends/message-filters/message-filters_%.bbappend:    rm -r ${D}/home
```

**Comment by jlamperez** [comment]
Some problems with rosbag2 and zstd-vendor

```
| Cloning into 'zstd-1.4.4'...
| fatal: unable to access 'https://github.com/facebook/zstd.git/': error setting certificate verify locations:  CAfile: /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt CApath: none
| Cloning into 'zstd-1.4.4'...
| fatal: unable to access 'https://github.com/facebook/zstd.git/': error setting certificate verify locations:  CAfile: /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt CApath: none
| Cloning into 'zstd-1.4.4'...
| fatal: unable to access 'https://github.com/facebook/zstd.git/': error setting certificate verify locations:  CAfile: /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt CApath: none
| -- Had to git clone more than once:
|           3 times.
| CMake Error at /media/DATA/petalinux-project/build/tmp/work/cortexa72-cortexa53-xilinx-linux/zstd-vendor/0.15.1-2-r0/build/zstd-1.4.4-prefix/tmp/zstd-1.4.4-gitclone.cmake:31 (message):
|   Failed to clone repository: 'https://github.com/facebook/zstd.git'
| 
| 
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/media/DATA/petalinux-project/project-spec/meta-ros/meta-ros2-humble/generated-recipes/rosbag2/zstd-vendor_0.15.1-2.bb:do_compile) failed with exit code '1'

```

**Comment by vmayoral** [comment]
Re-launched with a few other BSPs. Recipes throw no errors for me, `bitbake` task executor initiates nicely and the builds finish fine (after a few hours 🤣):

| `meta-ros` (Honister/Humble) in `AMD ZCU104` | `meta-ros` (Honister/Humble) in `NVIDIA Jetson AGX Xavier` | 
|----------|----------|
| [asciicast](https://asciinema.org/a/496558) | [asciicast](https://asciinema.org/a/496556) |

**Comment by jlamperez** [comment]
My test environment is this one,

- Petalinux 2022.1 upgraded to the last `2022.1_update1` that supports kv260/kr260
  -  `petalinux-upgrade -u 'http://petalinux.xilinx.com/sswreleases/rel-v2022/sdkupdate/2022.1_update1/' -p 'aarch64'`
- BSP: `xilinx-kv260-starterkit-v2022.1-05140151.bsp`
  - `petalinux-create --type project -s xilinx-kv260-starterkit-v2022.1-05140151.bsp`

This Petalinux update contains `meta-ros` layers inside (foxy). I am removing it from `bblayers.conf` file and only adding `meta-ros2-humble` and also replacing the new `meta-som-apps` `ros-tsn-pubsub` for inheriting with `ros_distro_humble.bbclass`.

And start building with `petalinux-build`.

Then I am getting the errors pointed out above. The one that I don't know how to deal with is `ca-certificates.crt CApath: none` I would need to dig it more.

It seems that this Petalinux 2022.1_update doesn't like humble.

**Comment by jlamperez** [comment]
I've been able to pass the zstd-vendor doing some changes on the patch, now I am having same CAfile problem with orocos_kinematics_dynamics

```
| Cloning into 'orocos_kdl-507de66'...
| fatal: unable to access 'https://github.com/orocos/orocos_kinematics_dynamics.git/': error setting certificate verify locations:  CAfile: /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt CApath: none
| Cloning into 'orocos_kdl-507de66'...
| fatal: unable to access 'https://github.com/orocos/orocos_kinematics_dynamics.git/': error setting certificate verify locations:  CAfile: /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-petalinux-linux/etc/ssl/certs/ca-certificates.crt CApath: none
| -- Had to git clone more than once:
|           3 times.
| CMake Error at /media/DATA/petalinux-project/build/tmp/work/cortexa72-cortexa53-xilinx-linux/orocos-kdl-vendor/0.2.2-2-r0/build/orocos_kdl-507de66-prefix/tmp/orocos_kdl-507de66-gitclone.cmake:31 (message):
|   Failed to clone repository:
|   'https://github.com/orocos/orocos_kinematics_dynamics.git'
```

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-humble-hawksbill-released/25729/7

**Comment by vmayoral** [comment]
The last bunch of changes add fixes for the [image_common](https://github.com/ros-perception/image_common) and [vision_opencv](https://github.com/ros-perception/vision_opencv) repos.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/announcing-the-completion-of-meta-ros-milestone-17/25933/2

**Comment by vmayoral** [comment]
@panxxhub, @robwoolley, @jlamperez and @rosterloh, ping.

We sent a new set of changes that should address some of the issues discussed above more elegantly.

**Comment by rcwoolley** [comment]
Thanks for all this work getting Humble ready for meta-ros.   I am setting up a machine to do some build coverage and test coverage across the matrix of supported releases.

Since that might take some more time to get up and running, I did a quick visual review of the commits you have added so far.   Here are a few things I saw:

I noticed that you added the byobu recipe.  Is this needed by ROS?  The only reference to it that I could find was this: http://wiki.ros.org/screenrun  Perhaps it should be added to another layer alongside screen or tmux?

A few of the commits modify recipes that were adjusted by previous commits in the series.   I suggest we should try to clean up the commit history for this PR.

I noticed a few cases where comments and code was copied from another recipe but the copyright assignment was changed.   I noticed this in the rcutils bbapend as well as in the rosidl-typesupport-fastrtps recipe.   I suggest we should retain the original copyright line when copy and pasting code that was contributed by LG.

**Comment by vmayoral** [comment]
> Thanks for all this work getting Humble ready for meta-ros. I am setting up a machine to do some build coverage and test coverage across the matrix of supported releases.

Interesting. Can this CI-like effort be contributed back? I think we all will benefit significantly from it.

> I noticed that you added the byobu recipe. Is this needed by ROS? The only reference to it that I could find was this: http://wiki.ros.org/screenrun Perhaps it should be added to another layer alongside screen or tmux?

That's a good catch and it's specific to my dev. preferences. I don't think that should be added. We can remove it.

> A few of the commits modify recipes that were adjusted by previous commits in the series. I suggest we should try to clean up the commit history for this PR.

This is fair ask. I'll need to rewrite the git history for that, so let's do it once we're good with the rest of the changes.

> I noticed a few cases where comments and code was copied from another recipe but the copyright assignment was changed. I noticed this in the rcutils bbapend as well as in the rosidl-typesupport-fastrtps recipe. I suggest we should retain the original copyright line when copy and pasting code that was contributed by LG.

This surprised me a bit @rcwoolley. We've been <ins>quite cautious with giving credit to LG and all previous contributors</ins>, only adding our contributions where appropriate (where there're actual changes). Note that the `humble` recipes are brand new, so there's not much to compare against, except if we look at `rolling` which is the closest one. I guess your claims above point to that.

You mention `rcutils` and `rosidl-typesupport-fastrtps`:
- `rcutils`
  - `rcutils_5.0.0-1.bbappend` `rolling` ([link](https://github.com/ros/meta-ros/blob/honister/meta-ros2-rolling/recipes-bbappends/rcutils/rcutils_5.0.0-1.bbappend))
  - `rcutils_%.bbappend` `humble` ([link](https://github.com/ros/meta-ros/pull/1003/files#diff-45a8b9b9435eeafc9656fad86dd7951860e39f3090d7913e8fe06a58a25f7d72))
- `rosidl-typesupport-fastrtps`: I'm sorry but you need to be more specific. Are you referring to `rosidl-typesupport-fastrtps-cpp`, or `rosidl-typesupport-fastrtps-c`. I checked the latter and it seems to be pretty obvious that there are relevant changes:
  - `rosidl-typesupport-fastrtps-c_2.0.2-1.bbappend` `rolling` ([link](https://github.com/ros/meta-ros/blob/honister/meta-ros2-rolling/recipes-bbappends/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-c_2.0.2-1.bbappend))
  - `rosidl-typesupport-fastrtps-c_%.bbappend` `humble` ([link](https://github.com/ros/meta-ros/pull/1003/files#diff-dd1d085e604d2932cc0abe17c3ec6b1bba0fe25ed921171a28a917979e96f245))


In both cases I see strong reasoning and contributions to add credit in Humble's recipe headers. So based on the above @rcwoolley, I don't find reason in your comment.

I understand you just sent some ideas *on a quick pass*, and though I agree we should assess contributions and credit appropriately, I think we should be *very careful* with claims such as the one you make above. They just discourage contributions and frankly, it's not like this repo has received a lot 😉. If you still have concerns about some recipes, we can look at it case by case. In case we mistakenly modified something we shouldn't have, happy to rectify.

**Comment by razr** [comment]
There are multiple QA fixes like that https://github.com/ros/meta-ros/pull/1003/commits/b424870e4f996ea20789bb5cca5c3874223ffc6a#diff-19a762c9c9a46f1cd00a06c856d4bcae93a3149a1d0acc5507705126067bf1cbR16 
I am wondering whether it is the correct way of fixing these issues?

**Comment by vmayoral** [comment]
> There are multiple QA fixes like that [b424870#diff-19a762c9c9a46f1cd00a06c856d4bcae93a3149a1d0acc5507705126067bf1cbR16](https://github.com/ros/meta-ros/commit/b424870e4f996ea20789bb5cca5c3874223ffc6a#diff-19a762c9c9a46f1cd00a06c856d4bcae93a3149a1d0acc5507705126067bf1cbR16) I am wondering whether it is the correct way of fixing these issues?

Very open to suggestions @razr.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-06-16/26093/2

**Comment by suyash-narain** [comment]
Hi @vmayoral, 

I was successfully able to use your branch to create a ros2 humble image on honister, but a peculiar thing I observed was that the source script ros_setup.sh was nowhere to be found. I never faced this issue with any of the previous versions of ROS2. 

setup.sh file is sourced from ament-packages template, but while building the ros2 humble image, I got all the 'ros-core' packages installed and each individual package having its own local_setup.sh in /usr/share, but ros_setup.sh found in /usr/bin is nowhere to be found. Hence I cannot source the environment. I copied the setup.sh file from ros2 galactic over to the humble image and sourced it, and that worked. But setup files were not generated by default for humble.

Do you have any suggestions here?

thanks

**Comment by vmayoral** [comment]
Kudos to @grsandeep85 and @mhatle. I've pushed their patches to the branch of this PR.
To everyone testing things, please pull and re-build.

@suyash-narain, this should address your issues.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/robotic-processing-unit-and-robotcore/27562/7

**Comment by robwoolley** [comment]
Hi @vmayoral,

I just pushed a preview of my changes for humble + kirkstone here: [https://github.com/robwoolley/meta-ros/tree/superflore/humble/2022-09-30](https://github.com/robwoolley/meta-ros/tree/superflore/humble/2022-09-30) I did it from scratch so I could see the problems first hand.

One example was ros-distro.inc missing things in ROS_SUPERFLORE_GENERATED_BUILDTOOLS which is why many of the packages had to have BBCLASSEXTEND += "native" added where they didn't need to before.  I fixed the problems I saw in iceoryx-, orocos-kdl-, and cyclonedds. The fixes might be applicable to honister as well and in resolving the problems you saw.

Let me know if I can help you with getting your ROS 2 Humble Hawksbill Honister configuration ready to merge.

What sort of support level were you aiming for with maintaining your configuration? (The levels are listed here: [https://github.com/ros/meta-ros/wiki/Policies#supportlevel-values-in-mcf-files](https://github.com/ros/meta-ros/wiki/Policies#supportlevel-values-in-mcf-files) ) Since the Honister release in Yocto Project is EOL, it would normally fall to "best-effort" according to the existing policy that was laid out. You may also consider "contrib" if you want to reduce the effort spent maintaining the branch and doing regular builds.

Regards,
Rob

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/meta-ros-bof-at-roscon2022/27765/2

**Comment by alperyazar** [comment]
Hi everyone,

I am trying to build this branch by following steps on https://www.hackster.io/vmayoral/ros-2-humble-in-amd-zcu102-with-yocto-6d3d9c by @vmayoral. The only difference is that I am using PetaLinux 2022.2 not 2022.1 but I am using this branch, not the built-in `meta-ros` layer come with PetaLinux 2022.2. I can compile and boot the system but I can't find ROS after booting. For example, where is `setup.bash` located? Can't find as `/opt/ros/humble/setup.bash`. Is it expected? I am using this commit: https://github.com/vmayoral/meta-ros/commit/59a615d6e1b30f8576711d7281d1be097b25c33c

Thanks.

**Comment by vmayoral** [comment]
> Hi everyone,
> 
> I am trying to build this branch by following steps on https://www.hackster.io/vmayoral/ros-2-humble-in-amd-zcu102-with-yocto-6d3d9c by @vmayoral. The only difference is that I am using PetaLinux 2022.2 not 2022.1 but I am using this branch, not the built-in `meta-ros` layer come with PetaLinux 2022.2. I can compile and boot the system but I can't find ROS after booting. For example, where is `setup.bash` located? Can't find as `/opt/ros/humble/setup.bash`. Is it expected? I am using this commit: https://github.com/vmayoral/meta-ros/commit/59a615d6e1b30f8576711d7281d1be097b25c33c
> 
> Thanks.

@alperyazar, I've tried reaching out via LinkedIn. Let's chat about your issues and how we can support you.

**Comment by vmayoral** [comment]
Community members and clients are relying on this PR and branch. Given that things haven't been moving forward for a while, and the unstable status of the`honister` branch. Let's get this in for now.

@robwoolley, happy to work together and merge the efforts you've led at https://github.com/ros/meta-ros/pull/1035 as well. Ping me and let's have a side chat to move things forward on this direction if desired.

**Pull request merged**
