### PR TITLE
Add recipes for mavros

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This pull request is very similar to the work done in https://github.com/bmwcarit/meta-ros/pull/424, but with the differences:

 - Download tarball instead of checking out a git repository.
 - The change in config.cmake.in uses what is done in the automatically generated files as reference for setting `mavlink_INCLUDE_DIRS` variable.
 - The mavlink files are in fact stored under `/opt/ros/indigo`, where it should be, based on the Ubuntu distribution. The last time I checked building with that #424, they were conflicting with another mavlink installation (one that goes to the standard locations).
 - The license checksum variables are set consistently with what has been done in other recipes in this repository.
 - Build and run dependencies set (although it seems that the current version of #424 apparently has fixed that).

@JochiPochi Your comments on this are very appreciated, since you've been working on this too for a while.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Oh, the CI check failed because the patch file was missing the Upstream-Status tag. I'll update it.

**Comment by guludo** [comment]
Just updated the patch file. I just wanted to note that https://github.com/mavlink/mavlink-gbp-release/pull/5 has the patch for fixing `patch/config.cmake.in` instead of `config.cmake.in`. As far as I understand, the releases are done automatically with the `bloom` toll, which supposedly would use `patch/config.cmake.in`.

**Comment by JochiPochi** [comment]
good idea on calling this ros-mavlink. I just recently stumbled with it interfeering with the mavlink recipe from https://github.com/koenkooi/meta-uav too. Was that the one you were talking about as well?

Thanks for submitting the PR to the mavlink project, I've been wanting to get rid of needing a patch for some time.

@bulwahn [mavlink/mavlink-gbp-release#5 ](https://github.com/mavlink/mavlink-gbp-release/pull/5) is a ROS Kinetic release but that should work fine for us I think. On that note though, what are the components on meta-ros that make us an indigo release? Since we compile from source does it matter if we grab indigo or kinetic releases for future recipes?

**Comment by guludo** [comment]
> good idea on calling this ros-mavlink. I just recently stumbled with it interfeering with the mavlink recipe from https://github.com/koenkooi/meta-uav too. Was that the one you were talking about as well?

Yep.

> Thanks for submitting the PR to the mavlink project, I've been wanting to get rid of needing a patch for some time.

> @bulwahn mavlink/mavlink-gbp-release#5 is a ROS Kinetic release but that should work fine for us I think. On that note though, what are the components on meta-ros that make us an indigo release? Since we compile from source does it matter if we grab indigo or kinetic releases for future recipes?

I think another option would be asking them to backport the patch to indigo. But if we can fix on a Kinetic release known for working with Indigo too, then I think we would be fine.

**Comment by guludo** [comment]
@JochiPochi 

> good idea on calling this ros-mavlink

Maybe too late for that, but IMHO maybe it's a good idea to have all packages be prefixed with "ros-" in order to avoid name clashes like that. I'd even say we name them like it's done for Ubuntu packages: `ros-<distribution>-<pkgname>`, e.g., `ros-indigo-mavlink`. We probably should be able to easily maintain different distributions, so that the user could select which one to use.

**Comment by bulwahn** [comment]
The meta-ros layer is an indigo distribution because the recipes' versions match the provided versions in the distribution.yaml in the indigo directory of the rosdistro repository. This is the place where all ROS package maintainers report new package releases and the ROS core team tests and integrates them. I have a script that checks if the versions in the distribution.yaml file and in meta-ros match and if not creates recipe update git commits automatically. I use this script about once every month to keep meta-ros roughly up to date. Of course, it is no problem for us to decide to make exceptions to that stated above if we consider it to be a better solution. We are our own maintainers and I am pragmatic about such decisions and changes, as long as it is documented somewhere and can be found for later development changes.

**Comment by bulwahn** [comment]
I am not a fan of prefixing it with ros-<distribution> because the layer would contain many duplicate recipes with very similar content. I instead would prefer to maintain a second branch for a second distribution. Users probably do not want to combine recipes of different distribution and the proposed solution would not allow that either compared to maintaining two branches. For maintaining two branches, I want to first get a CI testing set up; this is something on my todo list for a couple months now, and I am slowly progressing on that.

**Comment by bulwahn** [comment]
@guludo @JochiPochi If you two have decided on a common pull request, just close the one that would be obsolete and tell me when the other pull request is ready to merge, I will then test building it and then merge it (next week once I am back from vacation).

**Comment by guludo** [comment]
Hi @bulwahn 

> I am not a fan of prefixing it with ros- because the layer would contain many duplicate recipes with very similar content.

That makes sense for `ros-<distro>-` prefixes and your solution with separate branches makes sense. But I don't see how the prefix `ros-` would cause duplicate recipes.

**Comment by guludo** [comment]
Oh, I just saw now that there's a `create-ros-recipe.py` script. I should've seen that before writing patches by hand hehe.

**Comment by guludo** [comment]
> @guludo @JochiPochi If you two have decided on a common pull request, just close the one that would be obsolete and tell me when the other pull request is ready to merge, I will then test building it and then merge it (next week once I am back from vacation).

@JochiPochi Are you okay with using this pull request?

**Comment by JochiPochi** [comment]
@guludo Tentatively yes. I haven't finished running my mavros tests. I'll inform you asap.

**Comment by bulwahn** [comment]
Only prefixing with ros might work, but I dislike the resulting names for some standard packages, e.g. roslaunch would be called ros-roslaunch, similar for rostest, rospy and roscpp. So then it seems better to add the ros prefix selectively when there is the possibility of name clashing; that is just as you did for mavlink, and I think that is currently the best solution.

**Comment by bulwahn** [comment]
There are actually two scripts for creating recipes by two other authors in the scripts directory; unfortunately both scripts are still far away from perfect and complete. So I also still write all new recipes by hand.

**Comment by JochiPochi** [comment]
Hey @guludo, All seemed good, I only have two comments:
- This PR is missing a recipe for mavros_extras that is part of the tarball. Here's a [commit](https://github.com/cyphyworks/meta-ros/commit/60991144bc0aefe259b0c8e55819d8d319a2f937) I made to supplement it, feel free to grab and add it here or modify it accordingly.

- Can you be a little bit more verbose on the mavlink recipe commit message on why the patch for mavlink was necessary? Not for me but for the gitlog. The incorrect path is a common problem when writing recipes for wild cmake projects so I just want to make sure that is documented. That was the reason why I separated the mavlink recipe and the patch in separate commits on my PR.

Other than that it's all good, I'll be happy to close #424 and use this one instead once those two points are addressed :) Thanks for picking up the slack I was introducing, I was having trouble finding time to fix the issues with my implementation!

**Comment by guludo** [comment]
@JochiPochi I'd be happy to cherry-pick that commit here. I just had one comment regarding the dependencies though.

**Comment by JochiPochi** [comment]
@guludo Here's another [commit](https://github.com/cyphyworks/meta-ros/commit/9e678cf0d7ea62fbe59f107df1aab06c7b83bec0) with a less paranoid dependency list to match the `package.xml` file

**Comment by guludo** [comment]
@JochiPochi Thanks for the commit adding mavros_extras! I've added more information on the commit message for `ros-mavlink` and cherry-picked your commit. Hopefully it's now ready to be merged.

**Comment by guludo** [comment]
Btw, sorry for the delay on doing the fixes :-)

**Comment by JochiPochi** [comment]
No worries on the delay.

On the other hand, there is a typo on the commit I told you to cherrypick. I fixed that sometime ago but I forgot to update it here. 
I should have sent branch links instead of commit links as that way my force push fixes would have showed. So that's my fault:

Here's the branch: https://github.com/cyphyworks/meta-ros/commits/mavros-extras

Would you mind cherry picking the latest commit from there again please? This time I tested it instead of doing just a quick fix :)

As soon as that happens it will be ready for merge in my opinion

**Comment by guludo** [comment]
@JochiPochi Done :-)

**Comment by bulwahn** [comment]
I ran a quick test build with `bitbake ros-mavlink mavros mavros-extras`on a clean and fresh build environment with this build configuration :
```
Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:db7799747b263507427e325638353142ae79403c"
meta-oe           
meta-python       
meta-multimedia   = "master:18d518a03d7d55b69f7ff4b19916c7006220c3e9"
meta-ros          = "guludo-mavros-v2:4abde38c557402f63ad04cb414cb8179eecf2bbe"
```
Bitbake then fails with:
```
 CMake Error at /home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/sysroots/x86_64-linux/opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
|   Could not find a package configuration file provided by "tf" with any of
|   the following names:
| 
|     tfConfig.cmake
|     tf-config.cmake
| 
|   Add the installation prefix of "tf" to CMAKE_PREFIX_PATH or set "tf_DIR" to
|   a directory containing one of the above files.  If "tf" provides a separate
|   development package or SDK, be sure it has been installed.
| Call Stack (most recent call first):
|   CMakeLists.txt:7 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/mavros-extras/0.17.4-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: /home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/mavros-extras/0.17.4-r0/temp/run.do_configure.7763:1 exit 1 from 'cmake ${OECMAKE_SITEFILE} /home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/mavros-extras/0.17.4-r0/mavros-0.17.4/mavros_extras -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/mavros-extras/0.17.4-r0/toolchain.cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DCMAKE_PREFIX_PATH='/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/sysroots/qemux86/opt/ros/indigo;/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/sysroots/qemux86/usr;/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/sysroots/x86_64-linux/opt/ros/indigo;/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/sysroots/x86_64-linux/usr' -DCMAKE_INSTALL_PREFIX:PATH='/opt/ros/indigo' -DCATKIN_BUILD_BINARY_PACKAGE=ON -DSETUPTOOLS_DEB_LAYOUT=OFF -DCATKIN_ENABLE_TESTING=0 ${PACKAGECONFIG_CONFARGS} -Wno-dev'
| ERROR: Function failed: do_configure (log file is located at /home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/mavros-extras/0.17.4-r0/temp/log.do_configure.7763)
ERROR: Task (/home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/mavros/mavros-extras_0.17.4.bb:do_configure) failed with exit code '1'
```
So it seems some build dependencies where overly optimized away in the recipe.

Here also another remark: As I understand you created these commits together, you might want to add some kind of acknowledgement of that in the commit message. But that is of course up to you two.

**Comment by guludo** [comment]
Hi @bulwahn,

I'll do a fresh build here and correct the errors. Thanks.

> Here also another remark: As I understand you created these commits together, you might want to add some kind of acknowledgement of that in the commit message. But that is of course up to you two.

Yes, of course! I'll do it. In those situations it would be nice if git allowed multiple commit authors.

**Comment by JochiPochi** [comment]
Yep, the recipes got over optimized indeed. Looks like I had `tf` build already from a separate recipe. It is only used for `mavros-extras` so I added it to my recipe. @guludo once more if you cherrypick the last commit on my branch that should solve the problem. The rest of your recipes are good as they are.

I did scratch builds of just mavros and mavros-extras this time so there should be no compilation error again.

**Comment by JochiPochi** [comment]
I think that finding some of the mistakes I made through the course of this PR took a lot longer than I wish they did. Do you know of a better way to check that a recipe doesn't use previously build packages on `temp` if they aren't explicitly cited on the dependency list other than making scratch builds? (They take too long, even on a 10 core machine)
I think I've seen bitbake showing warning about those from time to time but not sure how to make it error on those instead of just go as a warning

**Comment by JochiPochi** [comment]
> Here also another remark: As I understand you created these commits together, you might want to add some kind of acknowledgement of that in the commit message. But that is of course up to you two.

@guludo, I'd be more than happy if the mavros-extras commit is the only one on my name, if you are okay with it. And that should show with the cherrypick, what do you think?

**Comment by guludo** [comment]
@JochiPochi Great. I was going to test the recipes separately today, but I'll just cherry pick your commit again then. :-)

**Comment by guludo** [comment]
@bulwahn @JochiPochi's commit re-cherry-picked and previous commits amended to add more accurate authorship information.

**Comment by bulwahn** [comment]
I ran `bitbake ros-mavlink mavros mavros-extras` on a clean and fresh build environment with this build configuration:
```
Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:dc24d785282eb13521cff084677f49de226c316b"
meta-oe           
meta-python       
meta-multimedia   = "master:18d518a03d7d55b69f7ff4b19916c7006220c3e9"
meta-ros          = "guludo-mavros-v3:4d18537b4abbc5a8a14a96e57434240fa690642b"
```
There are no errors and no warnings and I will merge this pull request now. Please close the other open pull request. Thanks a lot.

**Pull request merged**
