### PR TITLE
ompl: fix compilation error

### PR DESCRIPTION
**Pull request by yangjiel**
The issue is here #522 
For the ompl fix:
This time I submitted the issue to ompl and they do a fix. I generated the git format-patch from the commit they made. The format should be good this time.

As for the cv-bridge, I am not able to fix as I am working on morty environment only, can't test it on other environment. For now I just keep a patch in my repository.

Please have a look for those changes, thank you.

### CODE REVIEW

**Comment by rojkov** [comment]
@yangjiel The upstream has released the version 1.1.1 with the patch already included. Could you please upgrade the ompl recipe from v1.1.0 to v1.1.1?
This way there's no need to have the patch in the meta layer.

**Comment by yangjiel** [comment]
Seems ompl haven't address the gcc6 problem fully yet, there is still gcc6 problem at the branch 1.1.1. I have talked to them. As soon as they response, I will upgrade the ompl version to 1.1.1.

**Comment by yangjiel** [comment]
I have upgraded the ompl from version 1.1.0 to 1.1.1.

**Comment by rojkov** [comment]
I successfully built `core-image-ros-world` with

```
Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-25"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:ef68005a8c527e9b1d05b7769f0ec8ebe9ec3f91"
meta-oe           
meta-python       
meta-multimedia   = "master:1cbd1bc195017312ba8cf670b340f61a2ac6207b"
meta-ros          = "yangjiel-master-v1:f25474fdf3fb576e832426e7f40836eb33a8b821"
```
and a patch for https://github.com/bmwcarit/meta-ros/issues/532 applied manually.

Thanks @yangjiel ! That looks great

**Pull request merged**
