### PR TITLE
Enable moveit2

### PR DESCRIPTION
**Pull request by LewisLiuPub**
Enable moveit2 packages for ROS2 Foxy:
1. Create .bb files for each moveit2 sub-modules
2. Create .bbapend files for bugfixing of building/launching errors.

these bb files depend on Moveiti source code repo: https://github.com/ros-planning/moveit2, branch: main

### CODE REVIEW

**Comment by LewisLiuPub** [comment]
@shr-project , please help review.

**Comment by shr-project** [comment]
From what rosdistro commit were these recipes generated?

Even the latest Foxy release from 2020-10-09 generated in https://github.com/ros/meta-ros/pull/734 doesn't have moveit components yet.

The 2020-11-05 which is being prepared in https://discourse.ros.org/t/preparing-for-foxy-sync-2020-11-05/17113 doesn't seem to have them as well.

**Comment by LewisLiuPub** [comment]
These recipes were generated from ROS2 foxy.
The latest code of Moveit2 supports ROS2 foxy now, and I tested on Ubuntu 18.04/20.04 system.
I also tested the recipes ported to meta-ros based on branch dunfell.  Some launch files failed, and we are in progress of fixing these errors.
So it's not in a hurry to merge this PR. I'll let you know once we make the issues shot.

**Comment by shr-project** [comment]
>> From what rosdistro commit were these recipes generated?
> These recipes were generated from ROS2 foxy.

Superflore generates recipes from rosdistro index, see commits like
https://github.com/ros/meta-ros/commit/5f2f5afb35fcb13bd2e0bea7a52f48cf3f9de828
https://github.com/ros/meta-ros/commit/d842e980c2f09c57c70a66daa0e77d1543ce6e16

I don't see them in this PR and I don't see Moveit2 components in rosditro repo:
https://github.com/ros/rosdistro
so I wonder how did you generate them with superflore.

Because as it is now, all these generated-recipes from this PR will be removed by superflore, next time we upgrade foxy to new release.

**Comment by LewisLiuPub** [comment]
Oh, I got you. Actually, I am just using [moveit source code repo](https://github.com/ros-planning/moveit2) to enable moveit to yocto system.

Can I state that currently it is not the right time to enable moveit2 into meta-ros, because it is not added into rosdistro-foxy, even though its features pass tests under foxy?

if so, I am ok to wait for its readiness or directly close this PR first.
I can take some effort to work on Navigation2's issues.

**Comment by shr-project** [comment]
> Can I state that currently it is not the right time to enable moveit2 into meta-ros, because it is not added into rosdistro-foxy, even though its features pass tests under foxy?

That's correct in this form, but if it's moved from meta-ros2-foxy/generated-recipes to e.g. meta-ros2-foxy/recipes-moveit2 (and the comments in the recipe saying that it was generated with superflore are replaced with something more accurate) then I don't mind merging it.

Then when moveit2 packages are included in the rosindex and superflore generates the recipes for them automatically, the manually created .bb files from recipes-moveit2 will be dropped and replaced by superflore generated versions in generated-recipes (and the .bbappends will be adjusted accordingly).

@herb-kuta-lge do you agree?

**Comment by herb-kuta-lge** [comment]
> @herb-kuta-lge do you agree?

Yes.

**Comment by LewisLiuPub** [comment]
@shr-project @herb-kuta-lge is the conclusion also valid now? 
If so, and since moveit2 project has no clear release schedule, I can help update my patches to align with the latest meta-ros code base (maybe Branch dunfell) and move moveit2 meta layer out of folder generated-recipes to another specific folder (say, meta-ros2-foxy/recipes-moveit2).

**Comment by shr-project** [comment]
> @shr-project @herb-kuta-lge is the conclusion also valid now?

I believe it's still valid as not much changed since Nov.

**Comment by shr-project** [comment]
See the updates in https://github.com/ros/meta-ros/pull/776 I did last week and rebase on top of that if something more is needed.

**Comment by shr-project** [comment]
Closing, fell free to re-open if there is something left after rebase.

**Pull request closed without merging**
