### PR TITLE
tf, tf2, message-filters, roscpp: remove signals from find_package() calls to support boost 1.69

### LINKED ISSUE #618: roscpp, boost 1.69 and warrior
Greetings,

boost 1.69 has got it to thud branch of oe-core, so roscpp is broken now (see https://github.com/bmwcarit/meta-ros/issues/615). Is there any chance compatibility with thud can be restored, or do we have to downgrade to sumo now?

Thanks!

UPD: looks like dependency on boost::signals has been removed shortly from ros_comm/roscpp, but it hasn't been released yet, and meta-ros seems to be designed to use release tarballs. Waiting for a release then?

### PR DESCRIPTION
**Pull request by aizelauna**
boost has been updated in Yocto thud branch to 1.69. This boost update removes the deprecated library boost::signals. 
Since several versions, it is replaced by boost::signals2 which is a header only library.
Ros code already uses signals2 library but it still has links to the older library in its CMake files. This commit removes those references as they are now useless and more importantly source of error at configure time.

This PR should fix #618  issue.

### CODE REVIEW

**Comment by bulwahn** [comment]
Patch generally looks okay. I am just wondering:
  - is it possibly simpler to just update those packages? The upstream status suggests we are just lacking updates, right? I have not been updating the indigo packages much lately.
  - is this commit backwards compatible? Does this commit also work with a build configuration before boost was updated to 1.69?

**Comment by aizelauna** [comment]
First or all, thanks very much for looking at my PR.

> is it possibly simpler to just update those packages? The upstream status suggests we are just lacking updates, right? I have not been updating the indigo packages much lately.

To set the status, I used the same status than this patch that adds recent boost support:
https://github.com/bmwcarit/meta-ros/blob/master/recipes-ros/ros-comm/roscpp/0001-make-implicit-cast-explicit.patch
It looks like that the decision has been taken to not update kinetic and indigo packages.

> is this commit backwards compatible? Does this commit also work with a build configuration before boost was updated to 1.69?

I'll try to test this commit with rocko branch, I'll let you know about the result.

**Comment by aizelauna** [comment]
Test is going on, but I will not have any result before mid of march.
It looks like that meta-ros is not compatible with rocko, I have an issue with yaml-cpp that should be easily fixed with a bbappend (issue #613).

**Comment by aizelauna** [comment]
I tested this branch of _meta-ros_ within a _rocko_ based project. Boost version is 1.64.
It works just fine. 

For the record, I had to patch _yaml-cpp_ with this line in a bbappend file (issue #613):
` FILES_${PN}-dev += "/usr/lib/cmake/yaml-cpp"`
I did not include this in the PR because this is something not required with thud.

**Comment by aizelauna** [comment]
Hi,
I am coming back to get some update on this PR.
Is there anything else to do to be accepted and merged to master?

**Review by shr-project — DISMISSED** [review]

**Review by shr-project — APPROVED** [review]

**Pull request merged**
