### PR TITLE
Make meta-ros build against recent OpenEmbedded with recipe specific sysroots

### PR DESCRIPTION
**Pull request by rojkov**
The PR includes fixes for
* stricter gcc checks,
* missing dependencies
* issues inflicted by the new RSS feature.

The main issue reported in https://github.com/ros/catkin/issues/851 hasn't been properly solved though, but worked around.

### CODE REVIEW

**Comment by bulwahn** [comment]
I reviewed all commits: they all look good, and I also like the order of commits which should allow us to properly bisect issues in the future. I am currently running a few test builds and provide feedback within the next few days.

**Comment by bulwahn** [comment]
Build Configurations before the `Recipe-Specific Sysroots` Commit
-----------------------------------------------------------------

```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5ecdab6c2589a83bbbc522074052ff4438782102"
meta-oe           
meta-python       
meta-multimedia   = "master-next:c162c9102881ae97772e56ca779ffedbc445aca0"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Result: No errors.

```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5ecdab6c2589a83bbbc522074052ff4438782102"
meta-oe           
meta-python       
meta-multimedia   = "master:5ecbf9bab404af0de7d0f058d1620f40dae0d2d8"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Result:
  on first run, python-pyyaml failed; on second run, everything ran through
  The python-pyyaml error is not related to this pull request.

```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5ecdab6c2589a83bbbc522074052ff4438782102"
meta-oe           
meta-python       
meta-multimedia   = "master-next:a4a241160103d9e9296a7e9e0545f324604379d4"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Results:
  Various errors during parsing the recipes due to unmatched dependencies.
  Changes in the master-next branch of meta-openembedded cause these failures.
```
ERROR: Nothing PROVIDES 'gst-plugins-base' (but /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/gscam/gscam_0.1.3.bb DEPENDS on or otherwise requires it)
ERROR: gst-plugins-base was skipped: Recipe is blacklisted: Depends on blacklisted gstreamer
NOTE: Runtime target 'gscam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gscam', 'gst-plugins-base']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'gscam', 'gst-plugins-base']
NOTE: Runtime target 'core-image-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['core-image-ros-world', 'packagegroup-ros-world', 'gscam', 'gst-plugins-base']
ERROR: Nothing PROVIDES 'gstreamer' (but /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/gscam/gscam_0.1.3.bb DEPENDS on or otherwise requires it)
ERROR: gstreamer was skipped: Recipe is blacklisted: Fails to build with RSS http://errors.yoctoproject.org/Errors/Details/130583/
ERROR: Nothing PROVIDES 'gst-plugins-good' (but /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/gscam/gscam_0.1.3.bb DEPENDS on or otherwise requires it)
ERROR: gst-plugins-good was skipped: Recipe is blacklisted: Depends on blacklisted gstreamer
NOTE: Runtime target 'gstreamer0.10-pocketsphinx' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gstreamer0.10-pocketsphinx']
NOTE: Runtime target 'ros-pocketsphinx-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-pocketsphinx-dev', 'gstreamer0.10-pocketsphinx']
NOTE: Runtime target 'ros-pocketsphinx' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-pocketsphinx', 'gstreamer0.10-pocketsphinx']
ERROR: Nothing RPROVIDES 'gscam-dev' (but /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/gscam/gscam_0.1.3.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'gscam-dev'
NOTE: Runtime target 'gscam-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gscam-dev']
ERROR: Nothing RPROVIDES 'gst-plugins-good-gconfelements' (but /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-pocketsphinx/ros-pocketsphinx_0.3.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'gst-plugins-good-gconfelements' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gst-plugins-good-gconfelements']
```

Build Configurations after `the Recipe-Specific Sysroots` Commit
----------------------------------------------------------------

`the Recipe-Specific Sysroots` commit is 809746f56df4b91af014bf6a3f28997d6698ac78.

```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:809746f56df4b91af014bf6a3f28997d6698ac78"
meta-oe           
meta-python       
meta-multimedia   = "master:5ecbf9bab404af0de7d0f058d1620f40dae0d2d8"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Result:
  Still a number of recipes fail; some in the openembedded-core repository
  and some in meta-ros.
  most of them are reproducible, and do not disappear in the second build run.

First run:
```  
Summary: 16 tasks failed:
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/pluginlib/pluginlib_1.10.4.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/roscpp_1.11.20.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/resource-retriever/resource-retriever_1.11.7.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-python/recipes-devtools/python/python-pyyaml_3.12.bb:do_compile
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-support/atk/atk_2.22.0.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-graphics/pango/pango_1.40.3.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0_1.10.2.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.36.1.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-gnome/libgudev/libgudev_230.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-support/libsoup/libsoup-2.4_2.56.0.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
```

Second run:
```
Summary: 14 tasks failed:
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-python/recipes-devtools/python/python-pyyaml_3.12.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.36.1.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-support/atk/atk_2.22.0.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-gnome/libgudev/libgudev_230.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-multimedia/gstreamer/gstreamer1.0_1.10.2.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-support/libsoup/libsoup-2.4_2.56.0.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/openembedded.org/openembedded-core/meta/recipes-graphics/pango/pango_1.40.3.bb:do_prepare_recipe_sysroot
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosconsole_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
```

```
Build Configuration:
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:d1109378d730c5cf50240c4d1a468e3aef5208ea"
meta-oe           
meta-python       
meta-multimedia   = "master:5ecbf9bab404af0de7d0f058d1620f40dae0d2d8"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Result:
  Still a number of recipes fail; the recipes in the depending layers are libgphoto, gstreamer and python-pyyaml.
  All other failures are due to recipes in meta-ros.
  Most of the failures are reproducible, and do not disappear in the second build run.

First run:
```
Summary: 8 tasks failed:
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-python/recipes-devtools/python/python-pyyaml_3.12.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosconsole_1.11.20.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
```

Second run:
```
Summary: 11 tasks failed:
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/roscpp_1.11.20.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-python/recipes-devtools/python/python-pyyaml_3.12.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/rosconsole-bridge/rosconsole-bridge_0.4.4.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/resource-retriever/resource-retriever_1.11.7.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/pluginlib/pluginlib_1.10.4.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
```

Third run:
```
Summary: 11 tasks failed:
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/pluginlib/pluginlib_1.10.4.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/roscpp_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/rosconsole-bridge/rosconsole-bridge_0.4.4.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/resource-retriever/resource-retriever_1.11.7.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-python/recipes-devtools/python/python-pyyaml_3.12.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
```

Overall Conclusion:
The pull request does not resolve all issues in my build configuration, but in generally addresses a number of issues that I reported in #452.

@rojkov  Is the description sufficient to reproduce the errors on your machine?

**Comment by rojkov** [comment]
@bulwahn I've tested with more recent oe-core and a bit outdated meta-openembedded. Just updated the latter and I see gstreamer blacklisted indeed. Those blacklisting commits in meta-openembedded effectively make the layer incompatible with meta-ros. Could you try to roll it back to `92a1d82b0c04e2126327e20e3091e557dfa4a9de`, refresh oe-core and build again?

Here's my build configuration
```
Build Configuration:
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-24"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:d1109378d730c5cf50240c4d1a468e3aef5208ea"
meta-oe           
meta-python       
meta-multimedia   = "HEAD:92a1d82b0c04e2126327e20e3091e557dfa4a9de"
meta-ros          = "rss:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

I do tests with
```
$ bitbake packagegroup-ros-world collada-urdf rosconsole
```

And my local.conf is this http://pastebin.com/fs5tuDbX

**Comment by bulwahn** [comment]
I tested `bitbake core-image-ros-world -k` on build configuration:
Build Configuration:
```
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:d1109378d730c5cf50240c4d1a468e3aef5208ea"
meta-oe           
meta-python       
meta-multimedia   = "HEAD:92a1d82b0c04e2126327e20e3091e557dfa4a9de"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v1:ffe229f5052e047ba92d1b819441cf9418f2536d"
```

Result:
```
Summary: 9 tasks failed:
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/rosbag-storage_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/pluginlib/pluginlib_1.10.4.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/kdl-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry/eigen-conversions_1.11.8.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/ros-comm/roscpp_1.11.20.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometry2/tf2_0.5.13.bb:do_compile
  /home/lukas/dev/github.com/bmwcarit/meta-ros/recipes-ros/geometric-shapes/geometric-shapes_0.4.5.bb:do_compile
```

If you cannot re-produce the issue, I will provide you with the detailed error reports and look into the issue on my machine. At a first look, it seemed that certain boost headers were not properly found.

**Comment by rojkov** [comment]
Yep. After I've deleted all caches and sstate I can reproduce the errors with missing boost in sysroot.

**Comment by rojkov** [comment]
@bulwahn Could you please try again?

I've updated the catkin patch meant to avoid leaking host environment to sysroot. Now the sysroot prefix gets removed from absolute paths to libraries.

Also added one more patch adding an explicit dependency on libeigen to kdl-parser.

My current settings for `bitbake core-image-ros-world -k` are

```
Build Configuration:
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-24"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:d1109378d730c5cf50240c4d1a468e3aef5208ea"
meta-oe           
meta-python       
meta-multimedia   = "HEAD:92a1d82b0c04e2126327e20e3091e557dfa4a9de"
meta-ros          = "rss:3fe83a38168f3df4bff60108c18907dcc7ed9bf5"

```

**Comment by rojkov** [comment]
Hm... Now I'd appreciate logs. The eigen issues are expected, difficult to identify though. But the persisting boost problem is worrisome.

**Comment by bulwahn** [comment]
Okay, here is my build log on gist: https://gist.github.com/bulwahn/fe9f8177934e68cb6d692a16be7595e5

**Comment by rojkov** [comment]
Updated the patches once again to fix the missing eigen and pcl headers.

There were no Boost-related issues in the logs. But I can't reproduce the problems with `gstreamer` and `libgphoto2`.
@bulwahn could you please run 
```
$ bitbake -c cleanall gstreamer libgphoto2
```
before testing? The issues you're facing could be caused by somehow corrupted local sstate.

**Comment by bulwahn** [comment]
@rojkov I always delete my complete build directory before testing, so the two problems in gstreamer and libgphoto are reproducible on my machine and not due to a corrupted local state. For this pull request, we can ignore those two errors, and now with the current version, all other recipes seem to run through. I will do some more testing on other build configurations, and then we can merge this pull request.

**Comment by bulwahn** [comment]
I tested it on two build configurations:
```
Build Configuration:
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:d1109378d730c5cf50240c4d1a468e3aef5208ea"
meta-oe           
meta-python       
meta-multimedia   = "HEAD:92a1d82b0c04e2126327e20e3091e557dfa4a9de"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v3:d3d4634fe0f4ac134d469a990074d62db7b373e7"

Summary: 2 tasks failed:
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-multimedia/recipes-multimedia/gstreamer-0.10/gstreamer_0.10.36.bb:do_compile
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
```

```
Build Configuration:
BB_VERSION        = "1.33.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:def3800c7e58d9d1b54ea1df27b190a0f6d1d544"
meta-oe           
meta-python       
meta-multimedia   = "master:ec8d5fc0bb1f882a0cdd82a81a09175e503c3647"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-rss-v3:d3d4634fe0f4ac134d469a990074d62db7b373e7"

Summary: 1 task failed:
  /home/lukas/dev/openembedded.org/meta-openembedded/master/meta-oe/recipes-graphics/gphoto2/libgphoto2_2.5.8.bb:do_configure
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

From my side that is sufficient to merge this pull request now. @rojkov Do you still have some open points that would like to address?

**Comment by rojkov** [comment]
No opens, everything is fine for me.

I guess I know why gstreamer worked for me: I have `glib-genmarshal` installed on my host which leaked to bitbake most probably. Still I've no idea why libgphoto2 is failing for you.

I need to invest some time to setting up containerized builds.

**Pull request merged**
