### PR TITLE
recipe updates for indigo distribution on 2017-09-14

### PR DESCRIPTION
**Pull request by bulwahn**
This pull request updates the recipes to the current versions released on 2017-09-14. This release of the indigo distribution was announced in https://discourse.ros.org/t/new-packages-for-indigo-2017-09-14/2646.

### CODE REVIEW

**Comment by bulwahn** [comment]
This pull request was built successfully with this build configuration:
```
Build Configuration:
BB_VERSION        = "1.35.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:cbc396dd10488990c98bb6fd94c7d10a736d57c1"
meta-oe
meta-multimedia
meta-python       = "master:4496cb4b29173492e48f935a519e2aea58e40bd5"
meta-ros          = "indigo-updates:be18fd744db8845753928f465a2052df441e94f9"
```

**Comment by rojkov** [comment]
Builds successfully with the fixes from #555 applied:
```
Build Configuration:
BB_VERSION        = "1.35.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-26"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:cbc396dd10488990c98bb6fd94c7d10a736d57c1"
meta-oe           
meta-python       
meta-multimedia   = "master:4496cb4b29173492e48f935a519e2aea58e40bd5"
meta-ros          = "bulwahn-indigo-updates-v3:0501491c724de552ecc7c82b39b28f3e2e006e88"
```
@bulwahn This update was done after Github had updated its tarball auto-generation, so it's safe for now to merge. But I wonder if we'd better switch to fetching git repos to avoid #552 in future.

**Comment by bulwahn** [comment]
I just rebased this pull request on the current master; so, I expect the CI now to test this pull request successfully and then we can merge this.

**Comment by rojkov** [comment]
CI is green now. Merging...

**Pull request merged**
