### PR TITLE
adjustments due to recent developments in openembedded-core et al.

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by bulwahn** [comment]
I have tested this pull request with this build configuration:
```
Build Configuration:
BB_VERSION        = "1.35.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5a25ed1071f0d9b7d95edcc2b5b4545f960d5f95"
meta-oe           
meta-multimedia   
meta-python       = "master:ac2a6d2b5d69937577effcb8bb2149651bac0176"
meta-ros          = "recent-oecore-adjustments:ef4c8dd4cf47ee53abb8e4b0a8ce6e2616a93e21"
```

**Comment by rojkov** [comment]
Now I get this error when trying to build this PR plus #546 cherry-picked.
```
| [ 83%] Building CXX object CMakeFiles/mavconn.dir/src/tcp.cpp.o
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot-native/usr/bin/i586-oe-linux/i586-oe-linux-g++  -Dmavconn_EXPORTS -I/home/rojkov/work/ros/build/workspace/sources/libmavconn/libmavconn/include -I/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/usr/include -I/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include  -m32 -march=i586  --sysroot=/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0=/usr/src/debug/libmavconn/0.18.7-r0 -fdebug-prefix-map=/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot-native= -fdebug-prefix-map=/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot=  -fvisibility-inlines-hidden  -m32 -march=i586  --sysroot=/home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot -std=c++14 -fPIC   -o CMakeFiles/mavconn.dir/src/tcp.cpp.o -c /home/rojkov/work/ros/build/workspace/sources/libmavconn/libmavconn/src/tcp.cpp
| In file included from /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../message.hpp:32:0,
|                  from /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/common.hpp:16,
|                  from /home/rojkov/work/ros/build/workspace/sources/libmavconn/libmavconn/include/mavconn/mavlink_dialect.h:23,
|                  from /home/rojkov/work/ros/build/workspace/sources/libmavconn/libmavconn/include/mavconn/interface.h:37,
|                  from /home/rojkov/work/ros/build/workspace/sources/libmavconn/libmavconn/src/mavlink_helpers.cpp:21:
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../mavlink_helpers.h: In function 'uint8_t mavlink::mavlink_frame_char_buffer(mavlink::mavlink_message_t*, mavlink::mavlink_status_t*, uint8_t, mavlink::mavlink_message_t*, mavlink::mavlink_status_t*)':
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../mavlink_helpers.h:781:4: error: 'MAVLINK_START_SIGN_STREAM' was not declared in this scope
|     MAVLINK_START_SIGN_STREAM(status->signing->link_id);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../mavlink_helpers.h:781:4: note: suggested alternative: 'MAVLINK_MAX_SIGNING_STREAMS'
|     MAVLINK_START_SIGN_STREAM(status->signing->link_id);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~
|     MAVLINK_MAX_SIGNING_STREAMS
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../mavlink_helpers.h:783:4: error: 'MAVLINK_END_SIGN_STREAM' was not declared in this scope
|     MAVLINK_END_SIGN_STREAM(status->signing->link_id);
|     ^~~~~~~~~~~~~~~~~~~~~~~
| /home/rojkov/work/ros/build/tmp-glibc/work/i586-oe-linux/libmavconn/0.18.7-r0/recipe-sysroot/opt/ros/indigo/include/mavlink/v2.0/common/../mavlink_helpers.h:783:4: note: suggested alternative: 'MAVLINK_MAX_SIGNING_STREAMS'
|     MAVLINK_END_SIGN_STREAM(status->signing->link_id);
|     ^~~~~~~~~~~~~~~~~~~~~~~
|     MAVLINK_MAX_SIGNING_STREAMS
```

**Comment by bulwahn** [comment]
Hmm... that's new to me; I did not see that error last week. Possibly yet another error due to even more recent openembedded-core commit than last week?

**Comment by bulwahn** [comment]
@rojkov I believe I found the root of this mavros build issue, cf. my comment at #547.

**Comment by rojkov** [comment]
Good catch, I've updated #546 to point to the previous known good tag of mavlink.

**Pull request merged**
