### PR TITLE
Fix pythonpath for systemd environment file

### LINKED ISSUE #503: PYTHONPATH in roscore systemd service file
The PYTHONPATH in the [EnvironmentFile](https://github.com/bmwcarit/meta-ros/blob/master/recipes-ros/ros-comm/roslaunch/roscore-default) of [roscore.service](https://github.com/bmwcarit/meta-ros/blob/master/recipes-ros/ros-comm/roslaunch/roscore.service#L6) should be 
`/opt/ros/kinetic/lib/python2.7/dist-packages/` instead of `/opt/ros/kinetic/lib/python2.7/site-packages/`.

### PR DESCRIPTION
**Pull request by mcopejans**
Closes #503

### CODE REVIEW

**Comment by mcopejans** [comment]
@bulwahn PTAL

**Comment by rojkov** [comment]
Why this change is needed?

I've just checked the path to ROS python libs in `core-image-ros-world` and it seems all the libs are inside `/opt/ros/indigo/lib/python2.7/site-packages`.

**Comment by bulwahn** [comment]
@mcopejans Did you check the state on your development machine, or in the image that is created with the `bitbake` tool? I just want to make sure that there is not a misunderstanding in which this script is intended to be executed.

**Comment by rojkov** [comment]
Did you test the proposed change? I believe with this patch applied `roscore` simply won't find its python libs.

AFAIK `dist-packages` is a convention specific to debian-based distros like Ubuntu. OpenEmbedded doesn't adhere this convention.

**Comment by mcopejans** [comment]
That sounds like a reasonable explanation. I am using Ubuntu. Sorry for the misunderstanding. I will close the PR and linked issue.

**Pull request closed without merging**
