### PR TITLE
camera-info-manager: solves link issues

### PR DESCRIPTION
**Pull request by Minipada**
If libimage_transport.so and libcamera_calibration_parsers.so are installed on host machine, this commit prevents the compilation against those host libraries
It is similar to [the octomap-ros commit](https://github.com/bmwcarit/meta-ros/commit/43bd17e8839f4078351895eca361804f19efb13c) except here I use the ${ROSDISTRO} variable instead of using indigo directly

### CODE REVIEW

**Comment by bulwahn** [comment]
@Minipada there are two issues with this pull request:
1. it seems that you are merging the already merged commit again into this repository; I think a `git rebase master` should the trick, so that only one commit remains.
2. The adjustment of the octomap-ros recipe has been dropped a few days ago, so I am wondering if the solution we found there would also resolve the link issue you are encountering.
@rojkov What is your opinion? Do you have a good solution in mind?

**Comment by rojkov** [comment]
Hm.. I was wrong about https://github.com/bmwcarit/meta-ros/pull/446. It seems host environment leaks to Yocto both ways, either with `NO_CMAKE_FIND_ROOT_PATH` or without. I've just reproduced the link issue with a fake `libimage_transport.so` on my host.

@Minipada How about this patch for catkin instead?

```
diff --git a/cmake/templates/pkgConfig.cmake.in b/cmake/templates/pkgConfig.cmake.in
index d99b811..c692108 100644
--- a/cmake/templates/pkgConfig.cmake.in
+++ b/cmake/templates/pkgConfig.cmake.in
@@ -125,9 +125,9 @@ foreach(library ${libraries})
     foreach(path @PKG_CONFIG_LIB_PATHS@)
       find_library(lib ${library}
         PATHS ${path}
-        NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
+        NO_DEFAULT_PATH ONLY_CMAKE_FIND_ROOT_PATH)
       if(lib)
-        set(lib_path ${path})
+        get_filename_component(lib_path ${lib} DIRECTORY)
         break()
       endif()
     endforeach()

```

**Comment by Minipada** [comment]
@bulwahn It would be way better to find a more consistent solution, I agree.
@rojkov I was trying to test it, but I can't find the file to test this patch. Where would it be?

**Comment by rojkov** [comment]
@Minipada Sorry, I apply this to `catkin-native`

```
$ devtool modify catkin-native
$ cd workspace/sources/catkin-native/
$ patch -p1 < /path/to/the/patch
```

**Comment by Minipada** [comment]
I tried, did afterward

    devtool build
    bitbake my_recipe
but now rosconsole is throwing me error the error
` /opt/ros/indigo/lib/librostime.so: file not recognized: File format not recognized`

I assume catkin-native being modified, every recipe depending on it had to be bitbaked again. I compiled using the latest stage of `meta-ros`

**Comment by rojkov** [comment]
Works for me with fake `/opt/ros/indigo/lib/librostime.so` created on host.

But I had to remove tmp-glibc recently to test the latest openembedded with recipe specific sysroots. Try to delete tmp-glibc and rebuild it too.

**Comment by rojkov** [comment]
By the way, with the patch above (plus minor fixes for stricter gcc checks and missing builddeps) I've managed to get a successful build of `packagegroup-ros-world` on top of the latest `oe` with recipe specific sysroots enabled.

**Comment by bulwahn** [comment]
I unfortunately could not follow the whole discussion in detail, but if that two-line patch solves both issues, the recipe-specific sysroots problem and the host environment leaks, we should certainly merge that magic patch. Let @Minipada and me have a look, test it properly and confirm that it does the promised magic.

**Comment by Minipada** [comment]
@rojkov I'm gonna test that either tomorrow either during the next week. It would be amazing, definitely, if it does the job

**Comment by bulwahn** [comment]
@Minipada, @rojkov provides the pull request #455 with some changes that probably also addresses the issue that you encountered in this pull request. You might want to give #455 a try to check if it solves your linking problem.

**Comment by Minipada** [comment]
@bulwahn I'm in kind of a rush and don't have the opportunity to make tests on our only server before this week end. I'd need to upgrade the `oe` layer and make modifications of the mentioned packages

**Comment by bulwahn** [comment]
@Minipada We have tested and merged pull request #455 and I expect that this now resolves the issue you reported. Once you confirmed that, I would suggest to close this pull request here.

**Comment by Minipada** [comment]
Hey, sorry for the delay.
I just tested the meta-ros layer and didn't work for me. I had no ROS installation, then got the usual error with /usr/lib/liboctomap.so. I created a dummy file which solved the issue, had it again for /usr/lib/liboctomath.so as you can see.
`
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: octomap-ros-0.4.0-r0 do_compile: oe_runmake failed
ERROR: octomap-ros-0.4.0-r0 do_compile: Function failed: do_compile (log file is located at /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/temp/log.do_compile.25134)
ERROR: Logfile of failure stored in: /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/temp/log.do_compile.25134
Log data follows:
DEBUG: Executing shell function do_compile
NOTE: make -j 8
ERROR: oe_runmake failed
/home/yocto/poky/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -H/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/octomap_ros-0.4.0 -B/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/yocto/poky/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -E cmake_progress_start /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build/CMakeFiles /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
make -f CMakeFiles/octomap_ros.dir/build.make CMakeFiles/octomap_ros.dir/depend
make[2]: Entering directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
cd /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build && /home/yocto/poky/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/octomap_ros-0.4.0 /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/octomap_ros-0.4.0 /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build/CMakeFiles/octomap_ros.dir/DependInfo.cmake --color=
Scanning dependencies of target octomap_ros
make[2]: Leaving directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
make -f CMakeFiles/octomap_ros.dir/build.make CMakeFiles/octomap_ros.dir/build
make[2]: Entering directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
make[2]: *** No rule to make target `/usr/lib/liboctomath.so', needed by `devel/lib/liboctomap_ros.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/octomap_ros.dir/src/conversions.cpp.o
/home/yocto/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"octomap_ros\" -Doctomap_ros_EXPORTS -I/home/yocto/poky/build/tmp/sysroots/raspberrypi3/opt/ros/indigo/include -I/home/yocto/poky/build/tmp/sysroots/raspberrypi3/usr/include -I/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/octomap_ros-0.4.0/include  -march=armv7ve -marm -mfpu=neon-vfpv4  -mfloat-abi=hard -mcpu=cortex-a7  --sysroot=/home/yocto/poky/build/tmp/sysroots/raspberrypi3 -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0=/usr/src/debug/octomap-ros/0.4.0-r0 -fdebug-prefix-map=/home/yocto/poky/build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/home/yocto/poky/build/tmp/sysroots/raspberrypi3= -fvisibility-inlines-hidden  -march=armv7ve -marm -mfpu=neon-vfpv4  -mfloat-abi=hard -mcpu=cortex-a7  --sysroot=/home/yocto/poky/build/tmp/sysroots/raspberrypi3 -fPIC   -o CMakeFiles/octomap_ros.dir/src/conversions.cpp.o -c /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/octomap_ros-0.4.0/src/conversions.cpp
make[2]: Leaving directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
make[1]: *** [CMakeFiles/octomap_ros.dir/all] Error 2
make[1]: Leaving directory `/home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/build'
make: *** [all] Error 2
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at /home/yocto/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/octomap-ros/0.4.0-r0/temp/log.do_compile.25134)
ERROR: Task (/home/yocto/poky/build/../meta-ros/recipes-ros/octomap-ros/octomap-ros_0.4.0.bb:do_compile) failed with exit code '1'


`

**Comment by rojkov** [comment]
What's your build configuration? I'd like to reproduce the problem.

**Comment by Minipada** [comment]
Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "raspberrypi3"
DISTRO            = "poky"
DISTRO_VERSION    = "2.0.1"
TUNE_FEATURES     = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU        = "hard"
meta              
meta-yocto        
meta-yocto-bsp    = "roboyagi_master_rpi3:fc835685191e5a9cf2e26aa27ef3c1f68c84c508"
meta-raspberrypi  = "master:c768a3d1aed8d16d08afe12fddb359914e0a203a"
meta-oe           
meta-python       
meta-perl         = "master:131255dd561225d7e4ebbf5155420a685dfebf6e"
meta-ros          = "master:8a3adc1a6542f2c8a40b36021a78dc1057e3ed08"
meta-webserver    = "master:131255dd561225d7e4ebbf5155420a685dfebf6e"

I'm using the morty layer for **meta**

**Comment by rojkov** [comment]
I see... The morty branch doesn't support recipe specific sysroots which https://github.com/bmwcarit/meta-ros/pull/455 was meant to fix in meta-ros.
You may want to try the latest master of bitbake and oe.

Hopefully I'll be able to find some time next week to see what can be done for morty.

**Comment by Minipada** [comment]
In my case, I know how to solve it manually and I don't think I will test soon enough. Maybe we can close this pull request and open an issue if it matters

**Pull request closed without merging**
