### PR TITLE
create-ros-recipe.py: add script to generate ROS recipe from reposito…

### LINKED ISSUE #8: create a script that generates bitbake recipes out of the package.xml files

### PR DESCRIPTION
**Pull request by Minipada**
create-ros-recipe.py: add script to generate ROS recipe from repository, package name and package version.

Fixes #8

### CODE REVIEW

**Comment by bulwahn** [comment]
Thanks. I have not looked into it in detail; here just some things that I noticed on the first scan, you can probably format your python code with the pep8 tooling, and it should contain a header with license information.

**Comment by Minipada** [comment]
Sorry for the closed/opened issues. I used pep8 and added license.
Thanks

**Comment by bulwahn** [comment]
python script looks good now. The commit message now starts with `create-ros-recipe.py: create-ros-recipe.py:`; probably some mistake during rebasing and squashing. Could you quickly improve the commit message? After that, I am ready to merge the pull request.

**Comment by Minipada** [comment]
My bad, it's done.
Thanks

**Pull request merged**
