### PR TITLE
[dunfell][gatesgarth][hardknott][master] Add support for ROS 1 noetic 2021-03-12 release

### PR DESCRIPTION
**Pull request by shr-project**
https://discourse.ros.org/t/ros-noetic-ninjemys-release/14262

- Noetic 2020-10-09 - https://discourse.ros.org/t/new-packages-for-noetic-2020-10-09/16758
- Noetic 2020-11-30 - https://discourse.ros.org/t/new-packages-for-noetic-2020-11-30/17641
- Noetic 2020-12-14 - https://discourse.ros.org/t/new-packages-for-noetic-2020-12-14/17894
- Noetic 2021-01-22 - https://discourse.ros.org/t/new-packages-for-noetic-2021-01-22/18612
- Noetic 2021-02-08 - https://discourse.ros.org/t/new-packages-for-noetic-2021-02-08/18868
- Noetic 2021-03-12 - https://discourse.ros.org/t/new-packages-for-noetic-2021-03-12/19430

Depends on:
https://github.com/ros/meta-ros/pull/771
and
https://github.com/ros/meta-ros/pull/772
and
https://github.com/ros/meta-ros/pull/773
and
https://github.com/ros/meta-ros/pull/762
and uses superflore from
https://github.com/ros-infrastructure/superflore/pull/279

### CODE REVIEW

**Comment by shr-project** [comment]
Remaining issues:
```
Summary: 3 tasks failed:
  virtual:native:/jenkins/mjansa/build/ros/webos-noetic-gatesgarth/meta-ros/meta-ros1-noetic/generated-recipes/catkin/catkin_0.8.9-1.bb:do_configure
  /jenkins/mjansa/build/ros/webos-noetic-gatesgarth/meta-ros-webos/recipes-core/images/webos-image-ros-world.bb:do_rootfs
  /jenkins/mjansa/build/ros/webos-noetic-gatesgarth/meta-ros/meta-ros1-noetic/generated-recipes/ompl/ompl_1.5.1-1.bb:do_package
```

with hardknott I've fixed the issue with catkin itself, so it tests more recipes which are failing (probably caused by the issue in catkin - most of it is wrong python3 shebang in catkin generated files):
```
Summary: 77 tasks failed:
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros/rosunit_1.15.7-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rospy_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rostest_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/navigation/costmap-2d_1.17.1-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosmsg_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rostopic_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/kdl-parser/kdl-parser_1.14.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros/rosclean_1.15.7-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosparam_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/robot-navigation/nav-2d-utils_0.2.6-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosservice_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/roslaunch_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosgraph_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosmaster_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosnode_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/roswtf_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-comm/rosbag_1.15.9-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/xacro/xacro_1.14.5-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/geometric-shapes/geometric-shapes_0.7.2-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/srdfdom/srdfdom_0.6.2-1.bb:do_package
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/move-base-flex/mbf-utility_0.3.4-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros/rosboost-cfg_1.15.7-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros/rosmake_1.15.7-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros/roscreate_1.15.7-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/control-toolbox/control-toolbox_1.18.2-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/interactive-markers/interactive-markers_1.12.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-multimaster-msgs_1.2.5-2.bb:do_compile
  virtual:native:/jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/genmsg/genmsg_0.5.16-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/geometry/tf-conversions_1.13.2-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/mavros/mavros_1.5.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/image-pipeline/depth-image-proc_1.15.2-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/flexbe/flexbe-testing_1.3.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/flexbe/flexbe-onboard_1.3.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/flexbe/flexbe-mirror_1.3.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/image-pipeline/image-rotate_1.15.2-1.bb:do_configure
  virtual:native:/jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-environment/ros-environment_1.3.2-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rosparam-shortcuts/rosparam-shortcuts_0.4.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/neonavigation/costmap-cspace_0.10.4-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-controllers/diff-drive-controller_0.18.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros-common/recipes-core/images/ros-image-world.bb:do_rootfs
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/navigation/amcl_1.17.1-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/flexbe/flexbe-widget_1.3.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/flexbe/flexbe-input_1.3.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/cob-substitute/cob-safety-controller_0.6.10-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/cob-perception-common/cob-object-detection-visualizer_0.6.17-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/leo-common/leo-teleop_1.1.0-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/cob-substitute/cob-reflector-referencing_0.6.10-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/navigation/fake-localization_1.17.1-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/neonavigation/map-organizer_0.10.4-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-controllers/imu-sensor-controller_0.18.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/stag-ros/stag-ros_0.3.6-3.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-controllers/four-wheel-steering-controller_0.18.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/franka-ros/franka-control_0.7.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-controllers/force-torque-sensor-controller_0.18.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/dnn-detect/dnn-detect_0.1.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/navigation-experimental/pose-base-controller_0.3.4-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/diagnostics/rosdiagnostic_1.10.3-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/cob-control/cob-omni-drive-controller_0.8.12-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ompl/ompl_1.5.1-1.bb:do_package
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/phidgets-drivers/libphidget22_1.0.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/cob-control/cob-tricycle-controller_0.8.12-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/ros-controllers/joint-state-controller_0.18.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/mcl-3dl/mcl-3dl_0.5.1-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/robot-localization/robot-localization_2.6.8-2.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rc-visard/rc-tagdetect-client_3.1.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rc-visard/rc-pick-client_3.1.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jsk-3rdparty/slic_2.1.21-2.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/hfl-driver/hfl-driver_0.0.20-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.4.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/neonavigation/track-odometry_0.10.4-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/roscompile/roscompile_1.1.1-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/py-trees/py-trees_0.7.3-1.bb:do_package_qa
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/jsk-recognition/checkerboard-detector_1.2.15-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/rc-visard/rc-hand-eye-calibration-client_3.1.0-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/imu-tools/imu-filter-madgwick_1.2.2-1.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/pybind11-catkin/pybind11-catkin_2.5.0-1.bb:do_install
  /jenkins/mjansa/build/ros/ros1-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/industrial-robot-status-controller/industrial-robot-status-controller_0.1.2-1.bb:do_compile
```

**Comment by shr-project** [comment]
Remaining issues:
```
Summary: 60 tasks failed:
  virtual:native:meta-ros1-noetic/generated-recipes/genmsg/genmsg_0.5.16-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/mavros/mavros_1.6.0-1.bb:do_patch
  meta-ros1-noetic/generated-recipes/laser-geometry/laser-geometry_1.6.7-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/kdl-parser/kdl-parser_1.14.1-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/robot-navigation/nav-2d-utils_0.3.0-2.bb:do_configure
  meta-ros1-noetic/generated-recipes/geometric-shapes/geometric-shapes_0.7.2-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/srdfdom/srdfdom_0.6.2-1.bb:do_package
  meta-ros1-noetic/generated-recipes/move-base-flex/mbf-utility_0.3.4-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/geometry/tf-conversions_1.13.2-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/interactive-markers/interactive-markers_1.12.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-multimaster-msgs_1.2.7-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/eigenpy/eigenpy_2.6.1-3.bb:do_configure
  meta-ros1-noetic/generated-recipes/eml/eml_1.8.15-7.bb:do_configure
  meta-ros1-noetic/generated-recipes/image-pipeline/depth-image-proc_1.15.3-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/flexbe/flexbe-onboard_1.3.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/flexbe/flexbe-mirror_1.3.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/flexbe/flexbe-testing_1.3.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/image-pipeline/image-rotate_1.15.3-1.bb:do_configure
  virtual:native:meta-ros1-noetic/generated-recipes/ros-environment/ros-environment_1.3.2-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/rosparam-shortcuts/rosparam-shortcuts_0.4.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/pr2-ethercat-drivers/fingertip-pressure_1.9.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/vrpn/vrpn_7.34.0-2.bb:do_package  
  meta-ros1-noetic/generated-recipes/scan-tools/laser-scan-matcher_0.3.3-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/navigation/amcl_1.17.1-1.bb:do_configure
  meta-ros-common/recipes-core/images/ros-image-world.bb:do_rootfs
  meta-ros1-noetic/generated-recipes/leo-common/leo-teleop_1.2.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/cob-substitute/cob-safety-controller_0.6.10-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/flexbe/flexbe-widget_1.3.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/cob-substitute/cob-reflector-referencing_0.6.10-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/flexbe/flexbe-input_1.3.1-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/cob-perception-common/cob-object-detection-visualizer_0.6.17-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/navigation/fake-localization_1.17.1-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/osqp-vendor/osqp-vendor_0.1.2-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/dnn-detect/dnn-detect_0.1.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/robot-localization/robot-localization_2.7.1-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/navigation-experimental/pose-base-controller_0.3.4-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/people/face-detector_1.4.0-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/neonavigation/track-odometry_0.10.8-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/rc-visard/rc-pick-client_3.1.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/ros-led/ws281x_0.0.9-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.5.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/pybind11-catkin/pybind11-catkin_2.5.0-1.bb:do_install
  meta-ros1-noetic/generated-recipes/stag-ros/stag-ros_0.3.7-1.bb:do_package_qa
  meta-ros1-noetic/generated-recipes/phidgets-drivers/libphidget22_1.0.2-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/rc-visard/rc-hand-eye-calibration-client_3.1.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/imu-tools/imu-filter-madgwick_1.2.2-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/openzen-sensor/openzen-sensor_1.2.0-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/jsk-3rdparty/slic_2.1.21-2.bb:do_compile
  meta-ros1-noetic/generated-recipes/rc-visard/rc-tagdetect-client_3.1.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/neonavigation/map-organizer_0.10.8-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/hfl-driver/hfl-driver_0.0.20-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/mcl-3dl/mcl-3dl_0.5.4-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/m-explore/multirobot-map-merge_2.1.4-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/rc-genicam-camera/rc-genicam-camera_1.3.0-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/qpoases-vendor/qpoases-vendor_3.2.1-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/mqtt-bridge/mqtt-bridge_0.2.1-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/ros-industrial-cmake-boilerplate/ros-industrial-cmake-boilerplate_0.2.8-1.bb:do_package
  meta-ros1-noetic/generated-recipes/jsk-recognition/checkerboard-detector_1.2.15-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/mocap-optitrack/mocap-optitrack_0.1.1-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/taskflow/taskflow_3.0.0-3.bb:do_compile
  meta-ros1-noetic/generated-recipes/mqtt-bridge/mqtt-bridge_0.2.1-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/ros-industrial-cmake-boilerplate/ros-industrial-cmake-boilerplate_0.2.8-1.bb:do_package
  meta-ros1-noetic/generated-recipes/jsk-recognition/checkerboard-detector_1.2.15-1.bb:do_configure
  meta-ros1-noetic/generated-recipes/mocap-optitrack/mocap-optitrack_0.1.1-1.bb:do_compile
  meta-ros1-noetic/generated-recipes/taskflow/taskflow_3.0.0-3.bb:do_compile
```

and to replace that python3 distutils/shebang patch with something better.

**Comment by shr-project** [comment]
The core image builds and passes the sanity testing as described in https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#ros-1-sanity-test remaining build issues in world image will be fixed incrementally in separate PR(s) before Milestone 16 is closed.

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Perhaps squash `30b606b1 {noetic} python3: don't modify shebang from distutils` and its reversion?

**Comment by shr-project** [comment]
Also in other branches:
   764100201..20ed30676  dunfell -> dunfell-next
   b3b4cd776..cd1a16c90  gatesgarth -> gatesgarth
   b3b4cd776..cd1a16c90  gatesgarth -> gatesgarth-next
   d54e14d63..6a4bc25ca  hardknott -> hardknott
   d54e14d63..6a4bc25ca  hardknott -> hardknott-next
   d54e14d63..6a4bc25ca  master -> master
   d54e14d63..6a4bc25ca  master -> master-next

**Comment by shr-project** [comment]
Forgot to cherry-pick 2 more changes from my dunfell-next branch, added to all branches now:
   20ed30676..7cc9c3f5d  dunfell -> dunfell
   20ed30676..7cc9c3f5d  dunfell -> dunfell-next
   cd1a16c90..9a560c478  gatesgarth -> gatesgarth
   cd1a16c90..9a560c478  gatesgarth -> gatesgarth-next
   6a4bc25ca..5c5f3702a  hardknott -> hardknott
   6a4bc25ca..5c5f3702a  hardknott -> hardknott-next
   6a4bc25ca..5c5f3702a  master -> master
   6a4bc25ca..5c5f3702a  master -> master-next

**Pull request merged**
