### PR TITLE
[master] Update humble and iron

### PR DESCRIPTION
**Pull request by grsandeep85**
Update humble and iron with master, with this it will build with upstream master poky and oe-core.

### CODE REVIEW

**Review by robwoolley — CHANGES_REQUESTED** [review]
As of the Yocto 4.2 release, the LAYERSERIES_COMPAT variable in layer.conf no longer expands variables. This was done to make it clearer which Yocto releases are supported by a given layer.

See the Yocto Release 4.2 (mickledore) migration guide for details:
      https://docs.yoctoproject.org/next/migration-guides/migration-4.2.html

While this doesn't affect the earlier releases, Richard expressed that the change was made because some layer maintainers were abusing LAYERSERIES_COMPAT by making it dynamic.  I hardcoded the value in order to avoid perpetuating this.

**Review by robwoolley — COMMENTED** [review]
Looks good.  The permanent fix will be to update rosdistro directly, but I believe this will require getting help from the TSC.

**Review by robwoolley — APPROVED** [review]
Looks good.  The permanent fix will be to update rosdistro directly, but I believe this will require getting help from the TSC.

**Review by robwoolley — APPROVED** [review]
Looks good.  The permanent fix will be to update rosdistro directly, but I believe this will require getting help from the TSC.

**Review by robwoolley — APPROVED** [review]
Looks good.  The permanent fix will be to update rosdistro directly, but I believe this will require getting help from the TSC.

**Review by robwoolley — COMMENTED** [review]
Looks good.  The permanent fix will be to update rosdistro directly, but I believe this will require getting help from the TSC.

**Comment by grsandeep85** [comment]
> As of the Yocto 4.2 release, the LAYERSERIES_COMPAT variable in layer.conf no longer expands variables. This was done to make it clearer which Yocto releases are supported by a given layer.
> 
> See the Yocto Release 4.2 (mickledore) migration guide for details: https://docs.yoctoproject.org/next/migration-guides/migration-4.2.html
> 
> While this doesn't affect the earlier releases, Richard expressed that the change was made because some layer maintainers were abusing LAYERSERIES_COMPAT by making it dynamic. I hardcoded the value in order to avoid perpetuating this.

HI @robwoolley ,

Thanks for pointing this, not sure how it was building for with latest poky. Anyway you can drop this patch during PR merge.

**Comment by robwoolley** [comment]
Thanks, Sandeep.  I tested your fixes and pushed the commits to kirkstone-next.  I have held back the iron fixes temporarily as I flush out my current queue for humble.  I intend to port the whole series to iron once I'm done.

**Comment by grsandeep85** [comment]
Hi @robwoolley ,

Can you push the patches to master(especially humble one) this is something I need for YP summit.

**Comment by robwoolley** [comment]
Hi @grsandeep85, sure thing.  I am glad to help support your talk.

I cherry picked the commits from kirkstone-next to master-next (ie scarthgap).  and did a test build of ros-image-core and the affected packages.  Please check it out and I will push the changes from master-next to master.

**Comment by grsandeep85** [comment]
Hi @robwoolley,

Patches looks good. I tested with master-next last night and everything is working as expected. Please go ahead and push to master.

**Pull request closed without merging**
