### PR TITLE
reactivating joint-state-publisher

### PR DESCRIPTION
**Pull request by bulwahn**
I could reactivate joint-state-publisher after reviewing pull request https://github.com/bulwahn/meta-ros/pull/6 and cherry-picking the commit that upgrades and repairs wxwidgets & wxpython.

### CODE REVIEW

**Comment by bulwahn** [comment]
`bitbake core-image-ros-world` ran successfully on this build configuration:
```
Build Configuration:
BB_VERSION           = "1.35.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "i586-oe-linux"
MACHINE              = "qemux86"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "m32 i586"
TARGET_FPU           = ""
meta                 = "master:cf5c44ac611c2c2657e6fd3c1f723bcb20b812dd"
meta-oe              
meta-multimedia      
meta-python          = "master:acfb8417e370d017e7307872e61564deeda76a13"
meta-ros             = "joint-state-publisher-without-update:baa478be242c3ec015d59f0dcf25171d4277107a"
```

**Comment by bulwahn** [comment]
@rojkov To build successfully, the CI needs to have the `DISTRO_FEATURE opengl`; can you add that in the CI build?

**Comment by bulwahn** [comment]
@rojkov I just had a look at the `.yottaci.yaml`; can I just add that configuration and the CI build automagically uses that?

**Comment by rojkov** [comment]
Yes, sure. This is exactly how it works.

**Comment by bulwahn** [comment]
Hmm... CI failed because of insufficient disk space; the dependencies for the joint-state-publisher pull in quite some recipes and hence it fails...
@rojkov If you can't fix it this week, no worries, this pull request can wait for some time; joint-state-publisher has been deactivated for quite some year (probably more than a year), and in the past, no user complained or did provide a patch here at indigo.

**Comment by rojkov** [comment]
Oh, compressed sstate takes 60G now. That's too much for no real benefit. I'll reset it and re-trigger.

**Comment by bulwahn** [comment]
I did not see this failure in my test builds; I will need to investigate if I can reproduce this failure locally.

**Comment by Paul-Ajay** [comment]
@bulwahn  Any updates on this issue?
I tried building with the updated wxwidgets & wxpython files and webkitgtk 2.8.5 on the kinetic-experimental-v3 branch and ended up with lot of compilation warnings and errors from the webkitgtk library. 
Any suggested configurations / patch files to solve the issues?

**Comment by shr-project** [comment]
legacy (v1) isn't maintained anymore.

**Pull request closed without merging**
