### PR TITLE
dynamic-reconfigure properly depends on ${PYTHON_PN}-rospkg

### LINKED ISSUE #593: dynamic_reconfigure lacks ${PYTHON_PN}-rospkg in its DEPENDS/RDEPENDS
So each recipe that needs dynamic_reconfigure must add `${PYTHON_PN}-rospkg` to DEPENDS, or fail with error like
```
| Traceback (most recent call last):
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/freenect_stack-0.4.1/freenect_camera/cfg/Freenect.cfg", line 3, in <module>
|     from dynamic_reconfigure.parameter_generator_catkin import *
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
|     import roslib
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/roslib/__init__.py", line 50, in <module>
|     from roslib.launcher import load_manifest
|   File "/home/yocto/builds/navbox-c2-sumo/tmp-glibc/work/aarch64-oe-linux/freenect-camera/0.4.1-r0/recipe-sysroot/opt/ros/indigo/lib/python2.7/site-packages/roslib/launcher.py", line 42, in <module>
|     import rospkg
| ImportError: No module named rospkg
```
when catkin tries to generate dreconf files

### PR DESCRIPTION
**Pull request by dkargin**
Added ${PYTHON_PN}-rospkg to DEPENDS. Packages with dreconf will fail to build
if they not have rospkg in its depends.
Fixes #593

### CODE REVIEW

**Comment by bulwahn** [comment]
Thank you, Dmitry, for this pull request. The changes look sound and the CI ran through. Could you please update the commit message to follow the openembedded-core/yocto style, i.e., "<recipe-name>: describe the change with imperative, e.g., depend on ..., improve dependencies".

**Comment by dkargin** [comment]
Should I repack it to another commit with better description text, or update description for pull request?

And I've squished a commit with dependency fix for theora transport in this pull request. libogg was missing, so theora_image_transport was failing to build. I could split it to a separate pull request, but it is really inconvenient to support our own build infrastructure (find bug - kill bug) and keep it in sync with strict pull-request policy.

**Comment by rojkov** [comment]
@dkargin It would be enough to simply reword the commit messages of the two commits and to "force push" them to the same branch:
```
$ git rebase -i HEAD~2
<do some rewording>
$ git push -f sybotech fix_dreconf_deps
```

**Comment by bulwahn** [comment]
Here another github hint: if you put "(resolves #<issue-no>)" in your commit message header, the github issue tracker automatically creates a reference from the issue to the commit and closes the issue once the pull request is merged.

**Comment by dkargin** [comment]
Updated commit and removed extra references to ${PYTHON_PN}-rospkg for the packages, that need only dynamic-reconfigure.

**Comment by bulwahn** [comment]
Could you please remove the merge commits in this pull request, e.g., by rebasing the commit? Also, could you please put the commit message header in active voice and reduce the commit message header to 55 characters. Look at the linux kernel commit message conventions to learn about the rules for commit messages in meta-ros. We try to follow the same rules if possible.

**Comment by dkargin** [comment]
Shortened commit message, rebased to current master, squashed merge commits. 

`git rebase` is weird. It can cause the galaxy to collapse.

**Comment by rojkov** [comment]
Looks good to me, but the CI build failed due to excessive growth of bitbake cache.
I've reset the cache and restarted the build.

**Comment by bulwahn** [comment]
Commit was merged with pull request #604.

**Pull request closed without merging**
