### PR TITLE
rospack: backport lunar patch to fix boost incompatibility

### PR DESCRIPTION
**Pull request by rojkov**

### CODE REVIEW

**Comment by bulwahn** [comment]
Thanks. I wonder why we did not notice this before though? Any ideas?

**Comment by rojkov** [comment]
@bulwahn boost 1.65 has landed in OE-Core quite recently. I was notified about the ROS build failure by a OE-Core CI engineer yesterday.

**Comment by bulwahn** [comment]
Okay, I see. So, does OE-core CI actually now check if depending layers break due to upstream changes? Probably, we should also have a weekly cronjob on our CI that checks meta-ros against the master oecore and master openembedded repository. Then, we will notice such failures within a week as well.

**Comment by bulwahn** [comment]
My review is unspectacular; looks good to me. Let us wait until the CI runs through and then merge this commit.

**Comment by rojkov** [comment]
Yes, they run nightly builds for the industrial profile of "IoT Reference OS Kit for Intel Architecture" [1] which contains ROS's core plus MoveIt and some industrial packages.

I'm still consumed with tasks unrelated to ROS and my kid makes me busy at home :) Hopefully I'll find time for the cron jobs closer to Xmas.

[1] https://github.com/intel/intel-iot-refkit

**Comment by rojkov** [comment]
BTW, here's the dashboard for nightly ROS core builds in OE-core
https://autobuilder.yocto.io/builders/nightly-refkit/

**Comment by bulwahn** [comment]
Don't worry. I think we are maintaining this project quite well as small side project; and I am sure being busy with your kid is also a quite enjoyable activity for you...

**Comment by bulwahn** [comment]
CI is green; I will merge it.

**Pull request merged**
