### PR TITLE
Add ROS 2 Humble Hawksbill recipes to master - honister branch

### PR DESCRIPTION
**Pull request by vmayoral**
Follows from https://github.com/ros/meta-ros/pull/1003.

### CODE REVIEW

**Comment by panxxhub** [comment]
there are QA issues of all *-msgs( control-msgs, moveit-msgs .etc)

**Comment by vmayoral** [comment]
Thanks for reporting @panxxhub. We could use a few contributions for those messages that haven't been considered already.

**Comment by robwoolley** [comment]
Thanks for contributing this work.  I just wrapped up the building and testing for Milestone 17.   I will try to tackle this next.

**Comment by panxxhub** [comment]
some insane qa happens while building controller manager

**Comment by vmayoral** [comment]
> some insane qa happens while building controller manager

That's right @panxxhub. The jump to Yocto `Honister` is a big leap and most recipes need adjustments. The changes above address the *QA issues* in a subset of the repositories (*that I considered the minimum set to build a basic development rootfs*). Any other recipe/repo beyond those require similar adjustments to address QA issues. Take a look at how it's addressed for some other recipes above.

**Comment by panxxhub** [comment]
> > some insane qa happens while building controller manager
> 
> That's right @panxxhub. The jump to Yocto `Honister` is a big leap and most recipes need adjustments. The changes above address the _QA issues_ in a subset of the repositories (_that I considered the minimum set to build a basic development rootfs_). Any other recipe/repo beyond those require similar adjustments to address QA issues. Take a look at how it's addressed for some other recipes above.

other than some qa of [installed-vs-shipped], the qa issues of controller manager is much more complex(shebang-size,etc ) which i can't fix by myself, would you please hava a look at it?

**Comment by vmayoral** [comment]
`master` has moved to `Kirkstone`, so this PR makes no sense anymore.

Moving discussion to https://github.com/ros/meta-ros/pull/1003 instead.

**Pull request closed without merging**
