### PR TITLE
[kirkstone] Update ROS_OE_RELEASE_SERIES to kirkstone

### PR DESCRIPTION
**Pull request by homalozoa**
Signed-off-by: Homalozoa <nx.tardis@gmail.com>

### CODE REVIEW

**Comment by vmayoral** [comment]
This Yocto release (`kirkstone`) was out just this month (April 2022) and the recipes in `master` branch have not changed since last year. I doubt things will work out of the box without changes.

@homalozoa, have you tested the recipes against `kirkstone`?

**Comment by shr-project** [comment]
see https://github.com/ros/meta-ros/issues/999

**Comment by homalozoa** [comment]
> This Yocto release (`kirkstone`) was out just this month (April 2022) and the recipes in `master` branch have not changed since last year. I doubt things will work out of the box without changes.
> 
> @homalozoa, have you tested the recipes against `kirkstone`?

Hi @vmayoral . I already tested this change in my repo [meta-saha](https://github.com/cyber-zoo/meta-saha) with meta-tegra on Jetson Xavier NX, and I'm sure it is OK. The image will not build succeed without this change, ref the latest `poky` and `meta-openembedded`.

**Comment by shr-project** [comment]
https://github.com/ros/meta-ros/pull/1009 is more complete fix.

**Comment by homalozoa** [comment]
> https://github.com/ros/meta-ros/pull/1009 is more complete fix.

That's OK. Will it(#1009) be merged recently? @shr-project

**Comment by robwoolley** [comment]
Thanks for submitting this PR.  Upgrading to kirkstone requires additional fixes more than just updating the configuration file.   I will be pushing all the changes required shortly.

**Pull request closed without merging**
