### PR TITLE
ROS 2 Humble Hawksbill - Yocto Honister (2022/11/01)

### PR DESCRIPTION
**Pull request by robwoolley**
There was a new package milestone for ROS 2 Humble on 2022-11-01: https://discourse.ros.org/t/new-packages-for-ros-2-humble-hawksbill-2022-11-01/28085

This PR included generated recipes for that milestone as well as additional changes necessary to do a full ros-image-world build for Humble on Honister.

This PR is a first draft for feedback from the community. Additional modifications may be necessary to break the changes down into individual commits with appropriate commit messages.

### CODE REVIEW

**Comment by razr** [comment]
@robwoolley @vmayoral @RethinkMatze

There was a [new `humble` release](https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2022-11-23/28495) on the 23d of Nov, Does it make sense to rebase `humble` patches to it?

**Comment by razr** [comment]
@robwoolley do we need a patch with the updated [Build Instructions](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions) as well? I'm wondering how others could reproduce your build.

**Comment by robwoolley** [comment]
@razr Yes, I think so.  It should be pretty straightforward.  I'll give it a shot tomorrow.

Regarding the build instructions, I haven't changed the steps.  My instructions are based on the wiki, just simplified.

**Comment by razr** [comment]
@robwoolley, thanks for your response, just to clarify:

1. Since we extend a `meta-ros` build to `humble` should we also add it to the [instructions](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions)? Like

These instructions are for building ROS 2 dashing, eloquent, foxy, galactic, **humble** and rolling

2. `bionic` is also mentioned as a build machine, I assume you use `jammy` instead? Or it is still `bionic`?
3. I see you have created [`ros2-humble-honister.mcf`](https://github.com/ros/meta-ros/blob/1a170e2183758aa8641e0231d30a15199c1177b5/files/ros2-humble-honister.mcf). Do you want to create a PR for it as well? Did you use this file for your build?
4. is your `ROS-ADDITIONS` segment of the local.conf exactly as described [here](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#build-environment-setup)

**Comment by razr** [comment]
There was also an announcement about a [new `honister` release](https://lists.yoctoproject.org/g/yocto-announce/message/246?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2Chonister%2C20%2C2%2C0%2C91076968). We might need to adjust [ros2-humble-honister.mcf](https://github.com/ros/meta-ros/blob/1a170e2183758aa8641e0231d30a15199c1177b5/files/ros2-humble-honister.mcf) as well

**Comment by robwoolley** [comment]
> @robwoolley, thanks for your response, just to clarify:
> 
> 1. Since we extend a `meta-ros` build to `humble` should we also add it to the [instructions](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions)? Like
> 
> These instructions are for building ROS 2 dashing, eloquent, foxy, galactic, **humble** and rolling
> 
> 2. `bionic` is also mentioned as a build machine, I assume you use `jammy` instead? Or it is still `bionic`?
> 3. I see you have created [`ros2-humble-honister.mcf`](https://github.com/ros/meta-ros/blob/1a170e2183758aa8641e0231d30a15199c1177b5/files/ros2-humble-honister.mcf). Do you want to create a PR for it as well? Did you use this file for your build?
> 4. is your `ROS-ADDITIONS` segment of the local.conf exactly as described [here](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#build-environment-setup)

Thanks, Andrei.  This is helpful feedback.  I haven't quite gotten to this point yet as I am still trying to make sure the builds succeed and that the commit history is clean.

1. Rebase to Humble PR1 (2011-11-23) with Honister 3.4.4
2. Publish Humble PR1 to robwoolley/meta-ros
3. Review Victor and Matthias's PR for additional fixes
4. Merge the fixes onto PR1 baseline
5. Take Humble patch series for Honister and add meta-ros2-humble layers to Dunfell, Kirkstone, Langdale with Hardknott and Mickledore as stretch goals

I don't intend to update the documentation to add Humble until it is working for all supported Yocto releases to avoid any confusion.  Ideally, I would like to complete this before our next working group meeting.

**Comment by robwoolley** [comment]
This pull request has been superseded by https://github.com/ros/meta-ros/pull/1035

**Pull request closed without merging**
