### PR TITLE
Upgrade Octomap recipe to 1.8.0

### PR DESCRIPTION
**Pull request by rojkov**
* The upgraded recipe includes one more backported commit from Octomap's  `devel` branch that fixes cross-compilation without an external CMake module.
* The second commit removes the obsolete CMake module.

### CODE REVIEW

**Comment by bulwahn** [comment]
Commits look good. However I was asking myself if we can remove the tweaks in the octomap-ros recipe as well? The pull request https://github.com/OctoMap/octomap_ros/pull/6 was closed, so the patch does not seem to be necessary in the octomap-ros recipe right?

**Comment by bulwahn** [comment]
I ran `bitbake octomap-ros` without errors on build configuration:
```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5ecdab6c2589a83bbbc522074052ff4438782102"
meta-oe           
meta-python       
meta-multimedia   = "master-next:c162c9102881ae97772e56ca779ffedbc445aca0"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-octomap-upgrade-v1:7830cd18fb86b715db8dc9fc3252ea09e81fa86b"
```

**Comment by bulwahn** [comment]
Once the question on octomap-ros is answered, I would merge this pull request.

**Comment by rojkov** [comment]
Good catch! I've dropped the build dependency in octomap-ros.

**Comment by bulwahn** [comment]
Okay, I ran `bitbake octomap-ros` without errors on build configuration:
```
Build Configuration:
BB_VERSION        = "1.33.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:5ecdab6c2589a83bbbc522074052ff4438782102"
meta-oe           
meta-python       
meta-multimedia   = "master-next:c162c9102881ae97772e56ca779ffedbc445aca0"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-ros          = "rojkov-octomap-upgrade-v2:12e6df4b54116aa943f58c507de7d710b9ae5dbe"
```

So, it looks good and I will merge it.

**Pull request merged**
