### PR TITLE
python-imaging: adds a patch to disable link to host tcl lib Fixes #395

### LINKED ISSUE #395: Python-Imaging Error
Hello

May be asking in the wrong place but trying to build a ROS project in Yocto/Poky and always hit the same failure with python-imaging. Seems the one calling for it is rosbag but even without a ROS request I get the following - 

michael@michael-Kudu-Pro:~/yocto/build$ bitbake python-imaging
NOTE: Started PRServer with DBfile: /home/michael/yocto/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 37498, PID: 12511
Parsing recipes: 100% |##########################################################################################################################################################################| Time: 00:00:58
Parsing of 2312 .bb files complete (0 cached, 2312 parsed). 2852 targets, 150 skipped, 9 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.26.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "overo"
DISTRO            = "poky"
DISTRO_VERSION    = "1.8"
TUNE_FEATURES     = "arm armv7a vfp neon callconvention-hard cortexa8"
TARGET_FPU        = "vfp-neon"
meta  
meta-yocto        = "(nobranch):83aa565d93aacae484976562ef1ae8dbbb6b2bc0"
meta-gnome  
meta-oe  
meta-xfce  
meta-systemd  
meta-networking  
meta-multimedia  
meta-python       = "(nobranch):10d3c8f85280a0bf867a8e4f84bcda81c290d28e"
meta-gumstix      = "(nobranch):8ea631d8ef26cb13102dac0910be52674cb7b395"
meta-gumstix-extras = "(nobranch):15cfa9fcff75d3d95f66cfa190e1b604ff5ea4f6"
meta-ros          = "master:a5a19128a82a1c04a65d06eb615dbcf254dd1ae8"
meta-ti           = "(nobranch):03cb3ff15f3b8535ca409ce682f44ec1b81da0c3"
meta-java         = "(nobranch):66c97ae7461f4c1a13917131787bb76dc34e6b6f"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: QA Issue: python-imaging: The compile log indicates that host include and/or library paths were used.
         Please check the log '/home/michael/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/python-imaging/1.1.7-r5/temp/log.do_compile' for more information. [compile-host-path]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /home/michael/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/python-imaging/1.1.7-r5/temp/log.do_package_qa.22115
ERROR: Task 9 (/home/michael/yocto/poky/meta-ros/recipes-devtools/python/python-imaging_1.1.7.bb, do_package_qa) failed with exit code '1'
NOTE: Tasks Summary: Attempted 715 tasks of which 0 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/michael/yocto/poky/meta-ros/recipes-devtools/python/python-imaging_1.1.7.bb, do_package_qa

The failure seems to be with the following - 

cc1: warning: include location "/usr/include/tcl8.6" is unsafe for cross-compilation [-Wpoison-system-directories]

Any help would be great, or if you can point me in the right direction. A little lost since OE pulled python-imaging from there index. Thank you.

Cheers, Michael

### PR DESCRIPTION
**Pull request by Minipada**
Everything's in the title

### CODE REVIEW

**Comment by bulwahn** [comment]
Thanks for the patch.
Just a few minor remarks:
- have you considered to provide this patch back to the python-imaging developers? Probably, you would to extend the patch to have a configuration option, such as `is_crosscompile_environment`, and in the recipe we would set this option then. 
- I think you can simplify the patch by just deleting the crucial part instead of commenting it out.
- In OpenEmbedded, there is a style guide on patches at http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines. We try to follow this style guide as far as possible in meta-ros as well. One point that I immediately noticed was that your patch is still missing an Upstream-Status line.
- In the commit message, I usually only use the base name of the recipe, so `python-imaging` instead of `python-imaging_1.1.7.bb`. Furthermore, I personally dislike the word 'fix'; in my experience, I very often found problems just in those commits that 'fix' some stuff; unfortunately, although these commits have good intentions, _fixing_ an issue in one scenario might cause problems in another. So it is better to be honest, and say it _resolves_ this one issue.

**Comment by Minipada** [comment]
Thanks for the remarks, as usual.
You're right on submitting it to python-imaging, otherwise, a new patch will have to be done for every new version. Would you have an example recipe where it is applied so I can submit it properly to python-imaging mailing list?

About the difference between the words fix and resolve, I'm not a native English speaker and didn't make the difference between them. I checked their definition and you're right, we resolve issues. Thanks for the precision

**Comment by bulwahn** [comment]
While having a look at your pull request, I have just noticed that python-imaging is actually maintained in the meta-python layer; so I am actually inclined to remove the python-imaging recipe in meta-ros and assume that users obtain python-imaging with the meta-python layer, especially because the meta-python maintainers would be maintaining the recipe much better than I could do in meta-ros. For example, they have already included a CVE patch that I was not aware of.

For your patch, this would mean that you have to submit this patch to the meta-oe mailing list for its inclusion in the meta-python layer.

**Comment by bulwahn** [comment]
@Minipada please check pull request #421 to understand why we do not maintain python-imaging in meta-ros anymore. Hence, your suggested improvement should be included in meta-python, not in meta-ros; and this pull request is therefore obsolete. Contact me if you need help to get your patch upstream in meta-python.

**Pull request closed without merging**
