### PR TITLE
[dunfell][gatesgarth][hardknott][honister] {galactic} Miscellaneous fixes for recipes

### PR DESCRIPTION
**Pull request by rcwoolley**
I encountered some build failures when building ROS2 Galactic for Yocto Project hardknott release.

I have merged my fixes into meta-ros and tested using the documented steps: https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions to build ros-image-core

I then appended the following line to conf/local.conf to satisfy one of the recipe's dependencies:
DISTRO_FEATURES_append = " x11 opengl vulkan "

Followed by this command:
bitbake libg2o openvslam octomap libphidget22

Without my fixes these recipes will fail, with the fixes applied they should successfully build.

### CODE REVIEW

**Comment by shr-project** [comment]
I've updated this to follow our commit conventions and did few more changes inside, please check.

**Comment by shr-project** [comment]
I didn't look into the details, but openvslam fails with this PR applied:
```
/jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/9.3.0/include/avxintrin.h: In member function 'virtual float fbow::L2_avx_generic::computeDist(__m256*)':
/jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/9.3.0/include/avxintrin.h:1228:1: error: inlining failed in call to always_inline '__m256 _mm256_setzero_ps()': target specific option mismatch
 1228 | _mm256_setzero_ps (void)
      | ^~~~~~~~~~~~~~~~~
/jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/git/3rd/FBoW/src/fbow.cpp:121:39: note: called from here
  121 |         __m256 sum = _mm256_setzero_ps(), sub_mult;
      |                      ~~~~~~~~~~~~~~~~~^~
In file included from /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/9.3.0/include/immintrin.h:51,
                 from /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/git/3rd/FBoW/include/fbow/vocabulary.h:40,
                 from /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/git/3rd/FBoW/include/fbow/fbow.h:34,
                 from /jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/git/3rd/FBoW/src/fbow.cpp:27:
/jenkins/mjansa/build/ros/ros2-galactic-dunfell/tmp-glibc/work/core2-64-oe-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/lib/x86_64-oe-linux/gcc/x86_64-oe-linux/9.3.0/include/avxintrin.h:147:1: error: inlining failed in call to always_inline '__m256 _mm256_add_ps(__m256, __m256)': target specific option mismatch
  147 | _mm256_add_ps (__m256 __A, __m256 __B)
      | ^~~~~~~~~~~~~
```

**Comment by shr-project** [comment]
Fails the same here with hardknott release as well.

**Comment by shr-project** [comment]
@rcwoolley Add Upstream-Status and Signed-off-by in:
meta-ros2-galactic/recipes-bbappends/openvslam/openvslam/no_compiler_probe.patch
and preferably use git format-patch to create it, so it can be easily applied with git am

`FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"` should be `:prepend`

And please follow the convention to add {ros-distro} prefix in commit summary when it touches only one of the ROS distributions.

Are you going to fix openvslam in foxy? Or these fixes aren't needed in foxy?

**Comment by rcwoolley** [comment]
> @rcwoolley Add Upstream-Status and Signed-off-by in: meta-ros2-galactic/recipes-bbappends/openvslam/openvslam/no_compiler_probe.patch and preferably use git format-patch to create it, so it can be easily applied with git am
> 
> `FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"` should be `:prepend`
> 
> And please follow the convention to add {ros-distro} prefix in commit summary when it touches only one of the ROS distributions.
> 
> Are you going to fix openvslam in foxy? Or these fixes aren't needed in foxy?

Thanks.  I encountered some beginner mistakes with GitHub PRs.  I didn't expect my fork repo's branch to get rewritten and lost your changes when I did a force push.  I will make the changes you asked for now and resubmit.

**Comment by shr-project** [comment]
Upstream-Status and Signed-off-by also missing in meta-ros2-galactic/recipes-bbappends/phidgets-drivers/libphidget22/fix_libdir.patch as shown by:

meta-ros$ ./scripts/check-patch-files.sh 'meta-ros*'
meta-ros2-galactic/recipes-bbappends/phidgets-drivers/libphidget22/fix_libdir.patch: missing Upstream-Status line

**Comment by shr-project** [comment]
> > @rcwoolley Add Upstream-Status and Signed-off-by in: meta-ros2-galactic/recipes-bbappends/openvslam/openvslam/no_compiler_probe.patch and preferably use git format-patch to create it, so it can be easily applied with git am
> > `FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"` should be `:prepend`
> > And please follow the convention to add {ros-distro} prefix in commit summary when it touches only one of the ROS distributions.
> > Are you going to fix openvslam in foxy? Or these fixes aren't needed in foxy?
> 
> Thanks. I encountered some beginner mistakes with GitHub PRs. I didn't expect my fork repo's branch to get rewritten and lost your changes when I did a force push. I will make the changes you asked for now and resubmit.

My version is in my fork as:
https://github.com/shr-project/meta-ros/tree/dunfell-next-pr-932

**Comment by rcwoolley** [comment]
I made the changes that were requested.  I also fixed the libphidget22-upstream commit.   The diagnosis was correct, but the method I used to disable the Debian renaming wasn't actually working.   I discovered that doing: "bitbake -c cleanall libphidget22 && bitbake libphidget22" still exhibited the problem.  I tested the new fix both by cleaning and rebuilding libphidget22, but also by examining the log.do_package for libphidget22-upstream to ensure that the debian renaming lines were not present.

These patches successfully built the recipes for both qemux86-64 and raspberrypi4-64.

**Comment by shr-project** [comment]
Some of my changes were missed in this version.

- Use BPN in FILESEXTRAPATHS.
- Fold libphidget22-upstream_%.bbappend into libphidget22-upstream_1.6.20210312.bb as it doesn't make sense to bbappend our own non-generated recipe, do we really need to disable debian naming for all PACKAGES? PN-doc surely wasn't renamed, right?
- The .patch files still don't have the headers from git format-patch.

I will update the PR in https://github.com/shr-project/meta-ros/tree/dunfell-next-pr-932 to avoid further delay.

**Comment by rcwoolley** [comment]
1.  I missed that. My apologies.
2. Folding the bbappend in makes sense.
Regarding the second part: not all the packages were created as they would have been empty, however they all did get renamed:

grep debian ../tmp/work/core2-64-oe-linux/libphidget22-upstream/1.6.20210312-r0/temp/log.do_package
DEBUG: Executing python function debian_package_name_hook
NOTE: debian: renaming libphidget22-upstream-src to libphidget22-src
NOTE: debian: renaming libphidget22-upstream-dbg to libphidget22-dbg
NOTE: debian: renaming libphidget22-upstream-staticdev to libphidget22-staticdev
NOTE: debian: renaming libphidget22-upstream-dev to libphidget22-dev
NOTE: debian: renaming libphidget22-upstream-doc to libphidget22-doc
NOTE: debian: renaming libphidget22-upstream-locale to libphidget22-locale
NOTE: debian: renaming libphidget22-upstream to libphidget22-0
DEBUG: Python function debian_package_name_hook finished

The reverse-runtime symlinks reflect the incorrect Debian names as well:

lrwxrwxrwx 1 rwoolley rwoolley 32 Sep 30 10:45 /opt/projects/meta-ros-build/tmp/ljpkgdata/raspberrypi4-64/runtime-reverse/libphidget22-0 -> ../runtime/libphidget22-upstream
lrwxrwxrwx 1 rwoolley rwoolley 36 Sep 30 10:45 /opt/projects/meta-ros-build/tmp/pkgdata/raspberrypi4-64/runtime-reverse/libphidget22-dbg -> ../runtime/libphidget22-upstream-dbg
lrwxrwxrwx 1 rwoolley rwoolley 36 Sep 30 10:45 /opt/projects/meta-ros-build/tmp/pkgdata/raspberrypi4-64/runtime-reverse/libphidget22-dev -> ../runtime/libphidget22-upstream-dev
lrwxrwxrwx 1 rwoolley rwoolley 36 Sep 30 10:45 /opt/projects/meta-ros-build/tmp/pkgdata/raspberrypi4-64/runtime-reverse/libphidget22-src -> ../runtime/libphidget22-upstream-src
lrwxrwxrwx 1 rwoolley rwoolley 42 Sep 30 10:45 /opt/projects/meta-ros-build/tmp/pkgdata/raspberrypi4-64/runtime-reverse/libphidget22-staticdev -> ../runtime/libphidget22-upstream-staticdev

We could isolate the change to the ones that currently conflict, but this would open up the possibility for a conflict in the future.

3.  Acknowledged.  I will use "git format-patch" for future recipe patches.

**Comment by shr-project** [comment]
Replaced by https://github.com/ros/meta-ros/pull/940

**Comment by shr-project** [comment]
> We could isolate the change to the ones that currently conflict, but this would open up the possibility for a conflict in the future.

or just set AUTO_LIBNAME_PKGS to empty as I did.

**Pull request closed without merging**
