### PR TITLE
recipe updates for indigo distribution on 2017-08-10

### PR DESCRIPTION
**Pull request by bulwahn**
This pull request updates the recipes to the current versions released on 2017-08-10. This release of the indigo distribution was announced in https://discourse.ros.org/t/new-packages-for-indigo-2017-08-10/2430.

### CODE REVIEW

**Comment by bulwahn** [comment]
This pull request was successfully built with this build configuration:
```
Build Configuration:
BB_VERSION        = "1.35.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:82ea78bd2f03b6ba4d720595d3a3fbd96e0232f9"
meta-oe           
meta-multimedia   
meta-python       = "master:ac2a6d2b5d69937577effcb8bb2149651bac0176"
meta-ros          = "indigo-updates:f72960682239a51377f56433f74eb9fce7a6b023"
```

**Comment by bulwahn** [comment]
Upps... I need to add an Upstream-Status line in the new patch file.

**Comment by bulwahn** [comment]
Quickly added the Upstream-Status line in the patch.
@rojkov It is now ready for reviewing, testing and merging.

**Comment by rojkov** [comment]
I can reproduce the same error as in CI locally. Will try to bisect the culprit.

**Comment by bulwahn** [comment]
@rojkov I already did a bisect; the issue has been reported at #542.

**Comment by bulwahn** [comment]
I rebased the commits to the current master; this triggers a new CI build, which I now expect to run successfully. In parallel, I am also running a test build on my local machine.

**Comment by bulwahn** [comment]
`bitbake core-image-ros-world` was successful on this build configuration:
```
Build Configuration:
BB_VERSION        = "1.35.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:62f1122ef166eba56441d669c6b3b3fe5f367418"
meta-oe           
meta-multimedia   
meta-python       = "master:28d2c9b4474844516a9e8328bb497cdf3bec88ef"
meta-ros          = "indigo-updates:1d70c411c1ff3f1d4c01243e4ee90bb646855527"
```

**Comment by rojkov** [comment]
I checked the build environment and it seems there's nothing wrong with the builder. Disk quota was far from being full, but gettext was not installed in the sysroot specific to the failed recipe. That's probably a sstate issue or some glitch of unknown nature. Let's see if it gets reproduced in https://bbci.blob.core.windows.net/logs/wry-fly

**Comment by bulwahn** [comment]
The build failure looks just like the issue I noticed on my build machine quite some time ago as well; it is recorded in #464.

**Comment by bulwahn** [comment]
The CI failure is not related to those commits; so I will just merge this pull request, the next CI jobs will show if the unrelated CI issue persists or not.

**Comment by mythi** [comment]
Hi,
5bebd0e triggers a build failure. Looks that 0.5.16 won't work with python3.

**Comment by bulwahn** [comment]
@mythi Could you please provide the build configuration and the relevant parts of your local.conf?

**Comment by mythi** [comment]
@bulwahn I think the most relevant config is ```ROS_USE_PYTHON3 = "yes"``` for catkin. I'm building the latest meta-ros with intel-iot-refkit (covering @rojkov).

Based on geometry2 commit log, the regression seems obvious: a python3 incompatible change was made before 0.5.16 and it's fixed after the release. backporting those two patches make the build succeed.

**Comment by bulwahn** [comment]
At the moment, I have already another test build running, I will try to re-produce. If you have time, please adjust the recipe and provide a pull request, then I will check if your pull request resolves the issue and merge it.

**Comment by mythi** [comment]
@bulwahn submitted #550

**Pull request merged**
