### PR TITLE
Enable CI builds

### LINKED ISSUE #552: Build failure due to checksum mismatch
I started getting the following checksum failure today:
`
bitbake yaml-cpp
...
ERROR: Fetcher failure for URL: 'https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz'. Checksum mismatch!
File: '.../downloads/release-0.5.3.tar.gz' has md5 checksum e2507c3645fc2bec29ba9a1838fb3951 when 64200ca0bf5e0af065804d8d3e8f6d42 was expected
File: '.../downloads/release-0.5.3.tar.gz' has sha256 checksum 3492d9c1f4319dfd5588f60caed7cec3f030f7984386c11ed4b39f8e3316d763 when ac50a27a201d16dc69a881b80ad39a7be66c4d755eda1f76c3a68781b922af8f was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "e2507c3645fc2bec29ba9a1838fb3951"
SRC_URI[sha256sum] = "3492d9c1f4319dfd5588f60caed7cec3f030f7984386c11ed4b39f8e3316d763"
`
 
If one does a wget of the 'https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz” and do an md5sum, it does show a different string (e2507c3645fc2bec29ba9a1838fb3951) than the one in the below recipe so it seems like that file may have possibly changed at the source:
https://github.com/bmwcarit/meta-ros/blob/master/recipes-devtools/yaml-cpp/yaml-cpp_0.5.3.bb

### PR DESCRIPTION
**Pull request by rojkov**
Also the PR fixes build failures reported in #552

closes #552

### CODE REVIEW

**Comment by bulwahn** [comment]
@rojkov do you know when the yottaci will finish and light up green? It does not seem like it would do so within the last 24 hours. Is this expected?

**Comment by rojkov** [comment]
@bulwahn yes, it's expected for the first build (when SSTATE is empty). Hopefully it finishes in several hours.

Though there are issues with outdated hash-sums for some tarballs generated on fly by github. I can't find all of them at once locally due to my corporate proxy perhaps, so I fix them as they break builds in CI.

**Comment by rojkov** [comment]
Finally CI is green again

**Comment by bulwahn** [comment]
Okay, this looks good to me. I am still unsure about tying the recipes to the git revisions instead of the archive files, as this potentially has a few drawbacks as well, but we can discuss this more in #552. For now, I will just merge it for a working CI.

**Pull request merged**
