### PR TITLE
[dunfell] Complete Milestone 17 

### PR DESCRIPTION
**Pull request by kuta42**

### CODE REVIEW

**Review by shr-project — APPROVED** [review]

**Comment by shr-project** [comment]
Maybe mention that this repo is now unmaintained and OSRF looking for new maintainers?

**Comment by vmayoral** [comment]
@kuta42 and @shr-project, I'm working [on a branch](https://github.com/vmayoral/meta-ros/tree/honister-humble) (⚠️ WIP ⚠️ ) to bring `meta-ros` in `honister` for Humble and align with REP-2008. Refer to https://discourse.ros.org/t/branched-humble-call-for-beta-testing/25284/8?u=vmayoral for my community message.

What's the process to add me as maintainer? Can you guys enable me and give me privileges? Also, regarding the current list of maintainers, is that annotated somewhere? I don't see that in the [wiki](https://github.com/ros/meta-ros/wiki).

**Comment by kuta42** [comment]
@vmayoral:

> What's the process to add me as maintainer?

@tfoote controls the maintainers of meta-ros.

> Also, regarding the current list of maintainers, is that annotated somewhere?

See https://github.com/orgs/ros/teams/meta-ros-maintainers

**Comment by kuta42** [comment]
> Maybe mention that this repo is now unmaintained and OSRF looking for new maintainers?

>  kuta42 force-pushed the dunfell-next branch from adf1a38 to b06c16e 36 minutes ago

@shr-project < How does it look now?

**Comment by shr-project** [comment]
> How does it look now?

LGTM

**Comment by vmayoral** [comment]
> @tfoote controls the maintainers of meta-ros.

thanks @kuta42, @tfoote can you help passing over maintainer’s privileges? @kuta42 and @shr-project, do any of you guys have any issues with me becoming a maintainer?

**Edit:** didn’t explain enough. I know the project well, been contributing since it’s early days and led teams in the past that ported the recipes to ROS 2 before LG took over it and integrated everything in here  more consistently (see https://github.com/erlerobot/meta-ros2))

**Review by shr-project — APPROVED** [review]

**Comment by kuta42** [comment]
> have any issues with me becoming a maintainer?

Not from me -- but please don't merge anything until PR-s to close Milestone 17 (https://github.com/ros/meta-ros/pull/1002, 1004-1007) have been merged, which should happen by the end of this week.

**Comment by kuta42** [comment]
Merged to other branches as well:
   d775fdbad..cd2e0d062  dunfell -> dunfell-next

**Pull request merged**
