### PR TITLE
[dunfell][gatesgarth][hardknott][master] Upgrade ROS 1 melodic to 2021-03-18 release

### PR DESCRIPTION
**Pull request by shr-project**
- Melodic 2020-11-11 - https://discourse.ros.org/t/new-packages-for-melodic-2020-11-11/17239
- Melodic 2020-12-07 - https://discourse.ros.org/t/new-packages-for-melodic-2020-12-07/17777
- Melodic 2020-12-21 - https://discourse.ros.org/t/new-packages-for-melodic-2020-12-21/18165
- Melodic 2021-01-26 - https://discourse.ros.org/t/new-packages-for-melodic-2021-01-26/18672
- Melodic 2021-02-24 - https://discourse.ros.org/t/new-packages-for-melodic-2021-02-24/19135
- Melodic 2021-03-18 - https://discourse.ros.org/t/new-packages-for-melodic-2021-03-18/19536

### CODE REVIEW

**Comment by shr-project** [comment]
Remaining issues:
```
Summary: 5 tasks failed:
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/tvm-vendor/tvm-vendor_0.7.1-1.bb:do_compile
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/dynamic-graph/dynamic-graph_4.3.1-3.bb:do_configure
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.4.0-1.bb:do_configure
```

**Comment by shr-project** [comment]
Remaining issues after upgrade to 2020-12-21:
```
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/robot-localization/robot-localization_2.6.9-1.bb:do_configure                  |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/robot-navigation/nav-grid-server_0.3.0-1.bb:do_configure                       |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/raptor-dbw-ros/can-dbc-parser_1.0.0-2.bb:do_compile                            |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.4.0-1.bb:do_configure                    |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install                                      |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/tvm-vendor/tvm-vendor_0.7.2-1.bb:do_compile                                    |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/cob-manipulation/cob-lookat-action_0.7.5-1.bb:do_configure                     |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install                                        |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/dynamic-graph/dynamic-graph_4.3.1-3.bb:do_configure                            |
  /jenkins/mjansa/build/ros/ros1-melodic-dunfell/meta-ros/meta-ros1-melodic/generated-recipes/stag-ros/stag-ros_0.2.1-1.bb:do_package_qa 
```

**Comment by shr-project** [comment]
Remaining issues to solve:
```
  meta-ros1-melodic/generated-recipes/robot-localization/robot-localization_2.6.9-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/mavros/mavros_1.6.0-1.bb:do_patch
  meta-ros1-melodic/generated-recipes/vesc/vesc-driver_1.1.0-1.bb:do_compile
  meta-ros1-melodic/generated-recipes/open-manipulator-p/open-manipulator-p-control-gui_1.0.0-5.bb:do_configure
  meta-ros1-melodic/generated-recipes/robot-navigation/nav-grid-server_0.3.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/cob-manipulation/cob-lookat-action_0.7.5-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/tvm-vendor/tvm-vendor_0.7.2-1.bb:do_compile
  meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install
  meta-ros1-melodic/generated-recipes/mqtt-bridge/mqtt-bridge_0.1.8-4.bb:do_compile
  meta-ros1-melodic/generated-recipes/rc-genicam-camera/rc-genicam-camera_1.3.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/stag-ros/stag-ros_0.2.1-1.bb:do_package_qa
  meta-ros1-melodic/generated-recipes/dynamic-graph/dynamic-graph_4.3.1-3.bb:do_configure
  meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install
  meta-ros1-melodic/generated-recipes/khi-robot/khi-robot-control_1.2.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/rc-genicam-driver/rc-genicam-driver_0.5.0-1.bb:do_configure
```

**Comment by shr-project** [comment]
Remaining issues after upgrade to 2021-03-18:
```
Summary: 16 tasks failed:
  meta-ros1-melodic/generated-recipes/mavros/mavros_1.6.0-1.bb:do_patch
  meta-ros1-melodic/generated-recipes/robot-localization/robot-localization_2.6.9-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/open-manipulator-p/open-manipulator-p-control-gui_1.0.0-5.bb:do_configure
  meta-ros1-melodic/generated-recipes/vesc/vesc-driver_1.1.0-1.bb:do_compile
  meta-ros1-melodic/generated-recipes/robot-navigation/nav-grid-server_0.3.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install
  meta-ros1-melodic/generated-recipes/stag-ros/stag-ros_0.2.1-1.bb:do_package_qa
  meta-ros1-melodic/generated-recipes/cob-manipulation/cob-lookat-action_0.7.5-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/heron-controller/heron-controller_0.2.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/mocap-optitrack/mocap-optitrack_0.1.1-1.bb:do_compile
  meta-ros1-melodic/generated-recipes/dynamic-graph/dynamic-graph_4.3.4-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/tvm-vendor/tvm-vendor_0.7.2-1.bb:do_compile
  meta-ros1-melodic/generated-recipes/khi-robot/khi-robot-control_1.2.0-1.bb:do_configure
  meta-ros1-melodic/generated-recipes/mqtt-bridge/mqtt-bridge_0.1.8-4.bb:do_compile
  meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install
  meta-ros1-melodic/generated-recipes/ros-led/ws281x_0.0.9-1.bb:do_compile
Summary: There were 3 WARNING messages shown.
Summary: There were 17 ERROR messages shown, returning a non-zero exit code.
```

**Comment by shr-project** [comment]
Remaining issues:
```
Summary: 14 tasks failed:
  meta-ros/meta-ros1-melodic/generated-recipes/robot-localization/robot-localization_2.6.9-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/open-manipulator-p/open-manipulator-p-control-gui_1.0.0-5.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/robot-navigation/nav-grid-server_0.3.0-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/vesc/vesc-driver_1.1.0-1.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/khi-robot/khi-robot-control_1.2.0-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/heron-controller/heron-controller_0.2.0-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/dynamic-graph/dynamic-graph_4.3.4-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/mqtt-bridge/mqtt-bridge_0.1.8-4.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/cob-manipulation/cob-lookat-action_0.7.5-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/mocap-optitrack/mocap-optitrack_0.1.1-1.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install
  meta-ros/meta-ros1-melodic/generated-recipes/ros-led/ws281x_0.0.9-1.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install
  meta-ros/meta-ros1-melodic/generated-recipes/stag-ros/stag-ros_0.2.1-1.bb:do_package_qa
Summary: There were 15 ERROR messages shown, returning a non-zero exit code.
```

**Comment by shr-project** [comment]
Remaining issues:
```
Summary: 6 tasks failed:
  meta-ros/meta-ros1-melodic/generated-recipes/cpr-multimaster-tools/message-relay_0.0.2-1.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/khi-robot/khi-robot-control_1.2.0-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/cob-manipulation/cob-lookat-action_0.7.5-1.bb:do_configure
  meta-ros/meta-ros1-melodic/generated-recipes/mqtt-bridge/mqtt-bridge_0.1.8-4.bb:do_compile
  meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-rules_1.1.0-1.bb:do_install
  meta-ros/meta-ros1-melodic/generated-recipes/volta/volta-control_1.1.0-1.bb:do_install
Summary: There were 6 ERROR messages shown, returning a non-zero exit code.

```

**Review by herb-kuta-lge — APPROVED** [review]

**Comment by shr-project** [comment]
Merged in all branches:
   fd0296bca..ba5505534  dunfell -> dunfell-next
   866d68cd8..450155448  gatesgarth -> gatesgarth
   866d68cd8..450155448  gatesgarth -> gatesgarth-next
   79653a348..7e8c8603c  hardknott -> hardknott
   79653a348..7e8c8603c  hardknott -> hardknott-next
   79653a348..7e8c8603c  master -> master
   79653a348..7e8c8603c  master -> master-next

**Pull request merged**
