### PR TITLE
rename repository 'geometry_experimental' to 'geometry2'

### PR DESCRIPTION
**Pull request by dominiquehunziker**
The repository `geometry_experimental` has been moved to [geometry2](https://github.com/ros/geometry2)

### CODE REVIEW

**Comment by jvgomez** [comment]
Souldn't the folder and .inc file be renamed as well?

**Comment by adegroote** [comment]
Please merge it. The build is broken since one week.

**Comment by DaikiMaekawa** [comment]
Why don't you merge this PR? Please reply or merge.

**Comment by bulwahn** [comment]
Sorry, I have been busy on other matters. I would merge the commit, but agree with jvgomez remark that the file name and folder name should also be adjusted to geometry2.

**Comment by dominiquehunziker** [comment]
amended the directory/file rename and rebased to current HEAD

**Comment by bulwahn** [comment]
Thanks for the work! @KristofRobot Do you have any further comments? Please merge if the commit looks good to you as well.

**Pull request merged**
