### PR TITLE
Be able to compile on target

### PR DESCRIPTION
**Pull request by Minipada**
As discussed in #331 , here is a WIP to compile on target on the head.

Current setup:
* poky @ 7a0e795
* meta-openembedded@ba89d45
* meta-ros -> branch [compile_target_head](https://github.com/sncn-private/meta-ros/tree/compile_target_head)

`MACHINE = "qemuarm64"`
GCC 6.3

It fails during configuration in multiple packages. As an example, with `tf-conversions`: it doesn't find eigen:

    | CMake Error at /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/tf-conversions/1.11.8-r0/recipe-sysroot/opt/ros/indigo/share/kdl_conversions/cmake/kdl_conversionsConfig.cmake:117 (message):
    |   Project 'kdl_conversions' specifies
    |   '/home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/orocos-kdl/1.3.0-r0/recipe-sysroot/usr/include/eigen3'
    |   as an include dir, which is not found.  It does not exist in any of the
    |   root filesystems.  Ask the maintainer 'Tully Foote
    |   <tfoote@osrfoundation.org>' to fix it.
    | Call Stack (most recent call first):
    |   /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/tf-conversions/1.11.8-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
    |   CMakeLists.txt:5 (find_package)
    | 
    | 
    | -- Configuring incomplete, errors occurred!

PS: As soon as it is done, I will squash all commits

### CODE REVIEW

**Comment by TSC21** [comment]
This is great work @Minipada! Thanks for the contribution. Anyway others can help on this?

**Comment by Minipada** [comment]
I just saw PR #472, should I switch to GCC 5.4 to test the feature?

**Comment by bulwahn** [comment]
Let's go through the commits and check which ones can be dropped, because they are already upstream and which can be included as an initial step, possibly then with another first pull request on that matter.

**Comment by bulwahn** [comment]
You do not need to change to GCC 5.4; most (if not all) packages currently compile with GCC6.

**Comment by bulwahn** [comment]
I would propose to rebase the changes to the current master.
When you do this, you will find out that you can drop the commit 15e293592840987d948673294678511c0901ea58 (python-catkin-pkg: updating to 0.2.10) because this has happened already.
Also, you can drop commit f536213168fe6e9bebc73c4ea8125725389df40f (Fix mandatory rostest dependency) because that has been addressed as well.

**Comment by bulwahn** [comment]
If commit 57fb006bd280b43bb53dd0a9a30e7be084238408 (remove dependency on python-argparse) makes sense, we could test and merge that already. However, I do not know the reason why the python-argparse dependency is removed with the given commit message.

**Comment by Minipada** [comment]
@bulwahn I rebased here, I didn't want to lose the actual state so I created a new branch, I wanted to have your input first. Branch is here: [https://github.com/sncn-private/meta-ros/tree/compile_target_head_rebased](https://github.com/sncn-private/meta-ros/tree/compile_target_head_rebased) 

It's not yet good. I have this on rosbash:

    | CMake Error: File /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/../package.xml does not exist.
    | CMake Error at /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/stamp.cmake:10 (configure_file):
    |   configure_file Problem configuring file
    | Call Stack (most recent call first):
    |   /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/catkin_package_xml.cmake:61 (stamp)
    |   /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/all.cmake:150 (_catkin_package_xml)
    |   /home/yocto/yocto-ws/build/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include)
    |   CMakeLists.txt:3 (find_package)

**Comment by bulwahn** [comment]
Okay, so the commits are still quite chaotic and it is really difficult to review the changes. I would prefer if there are no merge commits in the pull request and they are in an order so that at least the default use of bitbake continues to work with each and every commit. That will simplify to start picking and merging the commits in an order and discussing those that are not clear yet.
I can help testing and debugging, but for that, I need to know what you are testing. Are you just trying `bitbake core-image-ros-world` and then encounter the problem with rosbash? Also for that, it would be nice if every commit is intended to address one thing, as we then can simply start running `git bisect` to find which commit introduced the problem for rosbash.

**Comment by Minipada** [comment]
I completely agree with you. I honestly don't know how to proceed properly in this kind of situation.
I got mixed up with the rebase and it leaded to this mess. I was testing bitbake rosbash.

 I would like to do it in a clean way, and the 2 branches I submitted are clearly far from that. I'm ready to restart so we (and mostly you) don't spend long time debugging.
As an idea, I could take the actual origin/master branch and apply @dominiquehunziker commits one by one instead of rpyuta branch and try to rebase. What do you think about it?

**Comment by bulwahn** [comment]
Yes, that is probably the best way forward. Then we can immediately see what breaks and possibly which commits are not applicable or only with adjustments. Use the commit messages to describe what you did when rebasing and which decisions you made. That certainly helps us to review it.

**Comment by bulwahn** [comment]
@Minipada I have seen some changes on the feature_compile_on_target_master branch. When this is ready for some first testing, just let me know.

**Comment by Minipada** [comment]
I actually started testing yesterday but I met the issue the ROS environment variables were not set ROS_ETC_DIR, ROS_PACKAGE_PATH, ROS_DISTRO, PYTHONPATH and PATH (adding opt/ros/indigo/bin).
I am still in the process of testing manually what's missing before pushing it to the Yocto layer.
After setting them, I could execute `catkin_make`, but I had a path or environment issue:


    -- The C compiler identification is GNU 6.3.0
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working C compiler: /opt/poky/2.3/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
    -- Check for working C compiler: /opt/poky/2.3/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /opt/poky/2.3/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++
    -- Check for working CXX compiler: /opt/poky/2.3/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:59 (message):
      find_package(catkin) failed.  catkin was neither found in the workspace nor
      in the CMAKE_PREFIX_PATH.  One reason may be that no ROS setup.sh was
      sourced before.

After checking, the `setup.sh` has not been "delivered" in the SDK path (/opt/poky/2.3/sysroots/aarch64-poky-linux/opt/ros/indigo). Nevertheless, catkin is there: `/opt/poky/2.3/sysroots/aarch64-poky-linux/opt/ros/indigo/lib/python2.7/site-packages/catkin`.
Any help is welcomed :)

**Comment by Minipada** [comment]
@bulwahn What I noticed is that there is not nativesdk-catkin-runtime created in the build directory.

**Comment by Minipada** [comment]
@bulwahn Good thing is I have the same on qemu, I'm still debugging
Edit: I was on the origin branch ... I'll push new changes and update you

**Comment by Minipada** [comment]
After some tests, It seems packages don't want to compile (here is rosbash) because they provide files already by catkin. 

    Exception: FileExistsError: [Errno 17] File exists: '/home/yocto/yocto_topdir/tmp/sysroots-components/x86_64/catkin-runtime-native/opt/ros/indigo/share/catkin/cmake/all.cmake' ->
    '/home/yocto/yocto_topdir/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/recipe-sysroot-native/opt/ros/indigo/share/catkin/cmake/all.cmake'

    ERROR: rosbash-1.11.14-r0 do_prepare_recipe_sysroot: Function failed: extend_recipe_sysroot
    ERROR: Logfile of failure stored in: /home/yocto/yocto_topdir/tmp/work/aarch64-poky-linux/rosbash/1.11.14-r0/temp/log.do_prepare_recipe_sysroot.11847

These are generated in `do_prepare_recipe_sysroot` (from `poky/meta/classes/staging.bbclass`). I am currently trying to remove them from the standard installation in `catkin.bbclass`

**Comment by bulwahn** [comment]
Probably it is best to make catkin provide those files and all other packages not to provide them. Otherwise, you will just run in the same problem when you need to install two packages in one SDK, and both packages will provide the same _generated_ file in the catkin directory.

**Comment by bulwahn** [comment]
I want to get involved in testing and debugging of this pull request in the next week or the week after. Can you provide me a pointer to a document that describes the steps that you are doing? Or is as simple as just building an image and then trying to execute `catkin_make` in the qemu emulator?
To explain my question above, I am currently not sure if you try to just allow catkin to build on the target or if you want to make it possible to build cross-compile SDKs (SDK as defined in the bitbake/yocto context, i.e., also called cross-compile tool chain in other projects.). I personally have not built or used SDKs in yocto/bitbake; so to get started with even the basics, I would need some pointers to appropriate documentation.

**Comment by Minipada** [comment]
You are completely right, that's exactly what I try to do by modifying the bbclass.
I am going to write about the changes and all the steps I did in the rest of the week. You'll have updates

**Comment by Minipada** [comment]
@bulwahn [Here](https://github.com/sncn-private/meta-ros/wiki/Compile-on-target) is a WIP. You have the current state, configuration, tests done, what I can do and what are the next objectives. Please give me as many requirements and recommendations to comply with the rest of your work

**Comment by bulwahn** [comment]
Okay, I tested it with the current master of openembedded-core and encountered this failure on a clean build of `bitbake core-image-ros-world`, but everything else succeeds:
```
ERROR: catkin-native-0.6.19-r0 do_prepare_recipe_sysroot: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/home/lukas/work/repositories/openembedded.org/openembedded-core/meta/classes/staging.bbclass', lineno: 592, function: extend_recipe_sysroot
     0588:                    dest = newmanifest[l]
     0589:                    if l.endswith("/"):
     0590:                        staging_copydir(l, targetdir, dest, seendirs)
     0591:                        continue
 *** 0592:                    staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0593:
     0594:    for f in fixme:
     0595:        if f == '':
     0596:            staging_processfixme(fixme[f], recipesysroot, recipesysroot, recipesysrootnative, d)
File: '/home/lukas/work/repositories/openembedded.org/openembedded-core/meta/classes/staging.bbclass', lineno: 233, function: staging_copyfile
     0229:        os.symlink(linkto, dest)
     0230:        #bb.warn(c)
     0231:    else:
     0232:        try:
 *** 0233:            os.link(c, dest)
     0234:        except OSError as err:
     0235:            if err.errno == errno.EXDEV:
     0236:                bb.utils.copyfile(c, dest)
     0237:            else:
Exception: FileExistsError: [Errno 17] File exists: '/home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/sysroots-components/x86_64/python3-catkin-pkg-native/usr/bin/catkin_find_pkg' -> '/home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/x86_64-linux/catkin-native/0.6.19-r0/recipe-sysroot-native/usr/bin/catkin_find_pkg'

ERROR: catkin-native-0.6.19-r0 do_prepare_recipe_sysroot: Function failed: extend_recipe_sysroot
ERROR: Logfile of failure stored in: /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/x86_64-linux/catkin-native/0.6.19-r0/temp/log.do_prepare_recipe_sysroot.14735
ERROR: Task (virtual:native:/home/lukas/work/repositories/github.com/bmwcarit/meta-ros/recipes-ros/catkin/catkin_0.6.19.bb:do_prepare_recipe_sysroot) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7206 tasks of which 5751 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/lukas/work/repositories/github.com/bmwcarit/meta-ros/recipes-ros/catkin/catkin_0.6.19.bb:do_prepare_recipe_sysroot
```
When I then continue to re-build `bitbake core-image-ros-world` after that again, all packages fail in do_prepare_recipe_sysroot.

The build configuration I use is:
```
Build Configuration:
BB_VERSION        = "1.33.4"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-14.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:123962018251dfb1d6ca5aa5c0d02534007de3ab"
meta-oe           
meta-multimedia   
meta-python       = "master:e7ad92decb7025d76e2e8b2bc15349d548c8ad14"
meta-ros          = "sncn-private-feature_compile_on_target_master-v1:64d8e7e098323ab4a801035b9946f0b17bb9dcec"
```

**Comment by bulwahn** [comment]
To move this feature forward, I would propose to get the small and straight-forward changes merged upstream. As I see it there is some general clean-up in the catkin recipe/bbclass, improving dependencies, etc., these could be already put upstream.

**Comment by Minipada** [comment]
@bulwahn I'm not in office since recently and will not be until start of june. I still have this in mind and will continue asap

**Comment by dominiquehunziker** [comment]
An update from my side: I went back and reorganized the master branch in our fork, i.e., I split the changeset into logical units (commits) and I rebased the changeset to current HEAD (or to a very recent version of it). The reorganization can be found in the branch [manual_rebase](https://github.com/rapyuta/meta-ros/tree/manual_rebase). Let me know if you want me to create a new PR for this branch or if you want to continue with this version of the PR.

I also included the latest changes with regards to the catkin cross-compilation patch (corresponding PR is [here](https://github.com/ros/catkin/pull/811)).

I believe one of the issues is testing the new features, right? In any case I wrote down some of the steps I take to test all this.

---

To test the SDK and compiling on source we are going to build a slight modification of the chatter node from the [ROS wiki](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber(c%2B%2B)), i.e., we are going to cross-compile a library using the SDK and compile the executable on the target.

First prepare the image that is going to be used. The following packages should be installed `roslaunch`, `rostopic`, `roscpp-dev`, `std-msgs-dev`. Additionally, the following line has to be added the the image recipe:

    TOOLCHAIN_HOST_TASK += "nativesdk-catkin"

Build the image with `bitbake <image>` and generate the SDK with `bitbake <image> -c populate_sdk`. This will generate the SDK install script `${DEPLOY_DIR}/sdk/*.sh`.

In the following a simple Dockerfile to use the installer (and which sets up the cross-compile environment).
Alternatively, the SDK can be installed in the host and the corresponding environment-setup sourced (be aware the SDK's environment-setup script is completely changing the environment variables):

```dockerfile
FROM ubuntu:14.04
MAINTAINER Dominique Hunziker

# Install minimal dependencies to install SDK
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python \
        xz-utils && \
    rm -rf /var/lib/apt/lists/

# Install SDK
ADD toolchain.sh /toolchain.sh
RUN /toolchain.sh -d /usr/local/oecore-sdk -y

# Automatically source the environment setup script
RUN echo "\n. /usr/local/oecore-sdk/environment-setup-*" >> /root/.bashrc
```

The assumption is made that the generated SDK install script is renamed to `toolchain.sh` and is located in same directory as the Dockerfile. Given this, the following will get the docker container built and running:

    sudo docker build -t toolchain .
    sudo docker run --rm -it toolchain /bin/bash

Once inside the cross-compile environment the regular work-flow for building ROS packages with `catkin_make` can be followed:

    mkdir -p ws/src
    cd ws/src
    catkin_init_workspace
    catkin_create_pkg --rosdistro indigo my_pkg roscpp

Here the header file of the library (`my_pkg/include/my_pkg/chatter.h`):

```cpp
#include "ros/ros.h"

void chatter(ros::Rate& loop_rate, ros::Publisher& pub);
```

and the source file of the library (`my_pkg/src/chatter.cpp`):

```cpp
#include "my_pkg/chatter.h"

#include "std_msgs/String.h"

#include <sstream>

void chatter(ros::Rate& loop_rate, ros::Publisher& pub)
{
    int count = 0;
    while (ros::ok())
    {
        std_msgs::String msg;

        std::stringstream ss;
        ss << "hello world " << count;
        msg.data = ss.str();

        pub.publish(msg);

        ros::spinOnce();

        loop_rate.sleep();
        ++count;
    }
}
```

Modify the `CMakeLists.txt` accordingly (don't forget to install the header files and library).

Install the package with the location on the target `/opt/ros/cross_compiled` and the host destination directory (`/target`). Note: We disable the generation of the `setup.<shell>` utilities as they are still broken (`-DCATKIN_BUILD_BINARY_PACKAGE=ON`)

    DESTDIR=/target catkin_make install --cmake-args -DCMAKE_INSTALL_PREFIX=/opt/ros/cross_compiled -DCATKIN_BUILD_BINARY_PACKAGE=ON

Either transfer everything under `/target` to `/` on the target platform or directly mount the root directory of the target at `/target`. (For docker use `docker cp` from the host to transfer the files or use the volume mount option `-v` when running the container.)

As we didn't generate the `setup.<shell>` utilities we first have to modify the environment variables on the target system in order to include the cross-compiled library. Alternatively, the cross-compiled library could be installed to `/opt/ros/indigo` and have all the ROS code in the same location:

    export PYTHONPATH=$PYTHONPATH:/opt/ros/cross_compiled/lib/python2.7/site-packages
    export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/opt/ros/cross_compiled/share
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ros/cross_compiled/lib
    export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/opt/ros/cross_compiled

Create a workspace in the target:

    mkdir -p ws/src
    cd ws/src
    catkin_init_workspace
    catkin_create_pkg --rosdistro indigo runner my_pkg std_msgs

Add the source file for the executable and again modify the `CMakeLists.txt`:

```cpp
#include "my_pkg/chatter.h"

#include "std_msgs/String.h"

int main(int argc, char **argv)
{
    ros::init(argc, argv, "talker");

    ros::NodeHandle n;

    ros::Publisher chatter_pub = n.advertise<std_msgs::String>("chatter", 1000);

    ros::Rate loop_rate(10);
    
    chatter(loop_rate, chatter_pub);
}
```

Build the workspace and install the binaries:

    cd ws
    catkin_make install --cmake-args -DCMAKE_INSTALL_PREFIX=/opt/ros/on_target -DCATKIN_BUILD_BINARY_PACKAGE=ON

And finally run the executable:

    roscore &
    /opt/ros/on_target/lib/runner/runner &

Check the output with:

    rostopic echo /chatter

Final note: Various variations of this can also be tested. For example compile everything on the target (remove the line regarding `TOOLCHAIN_HOST_TASK` from the recipe) or build everything using the SDK (replace `roscpp-dev` with `roscpp` and `std-msgs-dev` with `std-msgs`).

**Comment by bulwahn** [comment]
@dominiquehunziker Thanks for your work. Rebasing to the current master is certainly good to get this merged now or pretty soon. Please open a new pull request; this existing pull request is getting too messy already, so let's start with a new one.
We certainly need a minimal guide so that I can test the features during the ongoing maintenance activities. Only if we can test the features frequently, we will notice when it breaks due to changes in openembedded-core, in catkin, or in meta-ros.
I will try to follow the documentation and test the functionality at some point this week or next week.

**Comment by Minipada** [comment]
@dominiquehunziker Just got back here, it really seems great. I'll try your fork over the week end and help work on it. Since this PR was based on #386 , we should close this one and assist you in the #519 . What do you think?

**Pull request closed without merging**
