### PR TITLE
realsense-camera: support RealSense camera

### PR DESCRIPTION
**Pull request by rojkov**
This is rather a request for comments on adding the RealSense camera driver for ROS to the layer. In my opinion the main challenge of such addition is that meta-ros has to depend on one more layer.
If that's unacceptable what would be a better way to integrate RealSense support to meta-ros?

### CODE REVIEW

**Comment by bulwahn** [comment]
In general, I think that it is acceptable. I am wondering though if we can make it possible that one must only include the extra layer if the realsense-camera is used, or if bitbake requires the extra layer no matter which recipes are built.

**Comment by rojkov** [comment]
If the layer is not included then any invocation of `bitbake` fails with

```
ERROR: No recipes available for:
  /home/rojkov/work/ros/meta-ros/recipes-extended/librealsense/librealsense_%.bbappend
```

An alternative to the bbappend would be having the meta-intel-realsense people persuaded to make librealsense's recipe catkin friendly. I'll submit a PR to their repo. Let's see what's their reaction.

**Comment by rojkov** [comment]
Also updated this PR by adding rostest to build-deps, force pushed.

**Comment by bulwahn** [comment]
I also noticed that you drop the tests in the realsense-camera ROS package; I believe a better patch would be to build the tests depending on the flag `CATKIN_ENABLE_TESTING`, as this is done with various other ROS packages (cf. https://github.com/search?q=CATKIN_ENABLE_TESTING&type=Code&utf8=✓).

Then this patch could also be directly provided in the upstream repository, and the recipe works out of the box, as we disable testing with that flag in our cross-compile tool chain.

**Comment by rojkov** [comment]
Indeed it makes more sense. Thank you for pointing out!
I've replaced the patch and submitted a PR upstream:
https://github.com/intel-ros/realsense/pull/146

**Comment by bulwahn** [comment]
Generally, the pull request looks good now. I suggest that we wait a couple days to see if the two pull requests are merged upstream, then adjust the Upstream-Status in the patch and drop the bbappend and finally merge it. I was further thinking if the realsense-camera recipe could actually use the released version 1.6 rather than the quite arbitrary current stable tag?

**Comment by rojkov** [comment]
- tweaked the realsense_camera patch to fix ROS' CI builds;
- the recipe targets the latest stable release now (1.6.0);
- split out librealsense's bbappend (I'll remove it from the PR if it's accepted upstream soon enough);
- force pushed.

**Comment by rojkov** [comment]
As it seems https://github.com/IntelRealSense/meta-intel-realsense/pull/7 isn't going to be accepted in foreseeable future I have

* updated realsense-camera to the latest stable release (1.6.1);
* dropped realsense-camera's patch accepted upstream;
* included librealsense recipe inheriting to catkin;
* rebased and force pushed.

**Comment by bulwahn** [comment]
Okay, recipes look good to me. I ran a quick test build (`bitbake realsense-camera`) on this build configuration:
```
Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:db7799747b263507427e325638353142ae79403c"
meta-oe           
meta-python       
meta-multimedia   = "master:18d518a03d7d55b69f7ff4b19916c7006220c3e9"
meta-ros          = "rojkov-realsense-v2:19b34e340108033bbea9832272ccb86dc5be5312"
```
The commit `rojkov-realsense-v2:19b34e340108033bbea9832272ccb86dc5be5312` is your commit applied to the current master.
Bitbake reported two warnings related to your recipes:
```
WARNING: librealsense-1.11.2-r0 do_package_qa: QA Issue: librealsense rdepends on libusb1, but it isn't a build dependency, missing libusb1 in DEPENDS or PACKAGECONFIG? [build-deps]
WARNING: realsense-camera-1.6.1-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: '/[...]/build/tmp-glibc/work/i586-oe-linux/realsense-camera/1.6.1-r0/packages-split/realsense-camera/opt/ros/indigo/lib/librealsense_camera_nodelet.so' [ldflags]
```
From my side, those warnings are okay: recipes do not have to be free of warnings. I will just add those as issues in the issue tracker to make everyone aware that we are aware of the warnings.

Would you like to address those warnings or should I just merge the pull request?

**Comment by rojkov** [comment]
Oops, somehow I missed this libusb1 dep...

* added build dep on libusb1 to the librealsense recipe;
* patched realsense-camera not to ignore bitbake's global linker flags;
* force pushed.

**Comment by Minipada** [comment]
Sorry to intervene but I didn't see any mention of this layer here, maybe you didn't notice it:
https://github.com/IntelRealSense/meta-intel-librealsense
Librealsense is inside, I didn't test it tho

**Comment by rojkov** [comment]
@Minipada Did you check this comment https://github.com/bmwcarit/meta-ros/pull/431#issuecomment-266030115 ?
The librealsense recipe in https://github.com/IntelRealSense/meta-intel-librealsense isn't compatible with catkin-based recipes and requires extra jumping through hoops.

**Comment by Minipada** [comment]
My bad for the pollution. I didn't see it, great then.

**Comment by bulwahn** [comment]
Okay, I tested it once again, and there is no warning anymore. I will merge it. Thanks.

**Pull request merged**
