### PR TITLE
[dunfell][gatesgarth][hardknott][honister][kirkstone] Add a bunch of colcon recipes, which can be included in an SDK build.

### PR DESCRIPTION
**Pull request by windelbouwman**
I recently went through the process of creating a slew of colcon recipes. This is my working result.

### CODE REVIEW

**Comment by shr-project** [comment]
Can you please include the recipe for python3-distlib as well? now it fails with:
```
ERROR: Nothing RPROVIDES 'python3-distlib' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-core_0.6.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-distlib' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-distlib']
NOTE: Runtime target 'python3-colcon-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-test-result-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-test-result-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-test-result' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-test-result', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-cmake-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-cmake-dev', 'python3-colcon-test-result', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-cmake' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-cmake', 'python3-colcon-test-result', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-ros-dev', 'python3-colcon-cmake', 'python3-colcon-test-result', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-ros', 'python3-colcon-cmake', 'python3-colcon-test-result', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-pkg-config-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-pkg-config-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-pkg-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-pkg-config', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-bash-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-bash-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-bash' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-bash', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-package-selection-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-package-selection-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-package-selection' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-package-selection', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-parallel-executor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-parallel-executor', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-parallel-executor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-parallel-executor-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-python-setup-py' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-python-setup-py', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-python-setup-py-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-python-setup-py-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-defaults' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-defaults', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-defaults-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-defaults-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-output-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-output-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-output' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-output', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-cd-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-cd-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-cd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-cd', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-recursive-crawl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-recursive-crawl', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-recursive-crawl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-recursive-crawl-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-metadata-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-metadata-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-metadata' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-metadata', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-notification-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-notification-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-notification' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-notification', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-library-path' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-library-path', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-library-path-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-library-path-dev', 'python3-colcon-core', 'python3-distlib']
NOTE: Runtime target 'python3-colcon-package-information' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-package-information', 'python3-colcon-core', 'python3-distlib']
ERROR: Nothing RPROVIDES 'python3-colcon-core-dev' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-core_0.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-core-dev'
NOTE: Runtime target 'python3-colcon-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-core-dev']
ERROR: Nothing RPROVIDES 'python3-colcon-package-information-dev' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-package-information_0.3.3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-package-information-dev'
NOTE: Runtime target 'python3-colcon-package-information-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-package-information-dev']
ERROR: Nothing RPROVIDES 'python3-colcon-common-extensions-dev' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-common-extensions_0.2.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-common-extensions-dev'
NOTE: Runtime target 'python3-colcon-common-extensions-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-common-extensions-dev']
ERROR: Nothing RPROVIDES 'python3-colcon-devtools' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-common-extensions_0.2.1.bb, /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-devtools_0.2.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-devtools'
NOTE: Runtime target 'python3-colcon-devtools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-devtools']
ERROR: Nothing RPROVIDES 'python3-colcon-common-extensions' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-common-extensions_0.2.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-common-extensions'
NOTE: Runtime target 'python3-colcon-common-extensions' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-common-extensions']
ERROR: Nothing RPROVIDES 'python3-colcon-devtools-dev' (but /jenkins/home/anaconda/ros1-noetic-honister/meta-ros/meta-ros-common/recipes-devtools/colcon/python3-colcon-devtools_0.2.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-colcon-devtools-dev'
NOTE: Runtime target 'python3-colcon-devtools-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-colcon-devtools-dev']
```

**Comment by windelbouwman** [comment]
I added the recipe for distlib as well, thanks for the check, I forgot this..

**Comment by shr-project** [comment]
Merged to other branches as well:
   ea3596dbc..7fbe6da94  dunfell -> dunfell-next
   4e66ddf2f..a962cc7d8  gatesgarth -> gatesgarth
   4e66ddf2f..a962cc7d8  gatesgarth -> gatesgarth-next
   951ab29a1..ce3d4fa55  hardknott -> hardknott
   951ab29a1..ce3d4fa55  hardknott -> hardknott-next
   6773e3d32..e46c82888  honister -> honister
   6773e3d32..e46c82888  honister -> honister-next
   6773e3d32..e46c82888  master -> master
   6773e3d32..e46c82888  master -> master-next

**Comment by RiZom-91** [comment]
Hello @windelbouwman,

I'm a bit confused about how to add this to an SDK. Should one use TOOLCHAIN_TARGET_TASK_append = " pyton3-colcon-common-extensions" or TOOLCHAIN_HOST_TASK_append = " nativesdk-python3-colcon-common-extensions"?

nativesdk version will fail on dunfell branch because some python3 package recipes don't extend nativesdk like python3-coloredlogs, python3-docutil, python3-humanfriendly and python3-dateutil.

I was also wondering if all the ament-cmake* and ament-package should be part of the TOOLCHAIN_TARGET_TASK variable or the host one using nativesdk prefix.

My ultimate goal here is to be able to use "colcon build" with the SDK and cross-compile my own workspace.

**Comment by windelbouwman** [comment]
Hi @RiZom-91 ,

You should use `TOOLCHAIN_HOST_TASK_append = " nativesdk-python3-colcon-common-extensions"`, which will include colcon as a command in the SDK.

I see that I forgot to add some recipe bbappends containing `BBCLASSEXTEND += "nativesdk" for python3-humanfriendly and some other python packages that do not have nativesdk yet. You could add those bbappends to your own layer, or as a pull request to meta-ros.

The ultimate goal is indeed to use colcon to cross compile your workspace. This is what we are doing now.

**Pull request merged**
