### PR TITLE
Drop support for ROS distributions Kinetic and Crystal from thud

### PR DESCRIPTION
**Pull request by shr-project**
Kinetic recipes weren't ever generated in the new meta-ros and we don't plan to generate them now.

Crystal distribution reached EOL in Dec 2019:
https://index.ros.org/doc/ros2/Releases/#releases
and we don't plan to update its recipes anymore.

### CODE REVIEW

**Review by herb-kuta-lge — DISMISSED** [review]
Please move this change to a different PR: it has nothing to do with dropping Crystal.

**Comment by shr-project** [comment]
> Please move this change to a different PR: it has nothing to do with dropping Crystal.

Which change? the kinetic removal? Then the different PR will depend on this one or other way around, should I just rename the PR as "Drop unsupported ROS distributions"?

**Comment by shr-project** [comment]
Waiting for the branches to be finalized (-draft suffix removed and no longer rebase-able)

**Comment by shr-project** [comment]
This alligns thud-draft with warrior-draft (as with crystal dropped as well https://github.com/ros/meta-ros/pull/690) and zeus-draft (https://github.com/ros/meta-ros/pull/691), before new changes for Milestone 12 are merged through their corresponding pull requests (thud https://github.com/ros/meta-ros/pull/677, warrior https://github.com/ros/meta-ros/pull/678, zeus https://github.com/ros/meta-ros/pull/679 and dunfell/master https://github.com/ros/meta-ros/pull/680 with build branch changes for all of them in https://github.com/ros/meta-ros/pull/675

Only the README.md, meta-ros-backports-warrior layer itself and dependency on it in LAYERDEPENDS_ros-common-layer + ROS_OE_RELEASE_SERIES is now different between thud and warrior branches.

```
$ git diff --stat thud-mj8b-crystal-drop warrior-draft-crystal-drop 
 README.md                                                                                                                  |    4 +-
 meta-ros-backports-warrior/classes/python3-dir.bbclass                                                                     |    5 -
...
 meta-ros-backports-warrior/recipes-support/spdlog/spdlog_1.3.1.bb                                                          |   19 ---
 meta-ros-common/conf/layer.conf                                                                                            |    1 -
 meta-ros-common/conf/ros-distro/ros-distro.conf                                                                            |    2 +-
 40 files changed, 3 insertions(+), 3836 deletions(-)
```

**Pull request merged**
