### PR TITLE
Some recent changes to run with ROS_USE_PYTHON3 = "yes"

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by bulwahn** [comment]
Hmm... you fix one issue, and two new unrelated issues from openembedded-core appear... I am following up on what broke the recent master

**Comment by bulwahn** [comment]
I just rebased and force pushed it; CI build job is restarted.

**Comment by bulwahn** [comment]
Just for the record, I successfully build `bitbake core-image-ros-world` (in total 4 test builds) with `ROS_USE_PYTHON3` set and unset and with these two recent build configurations:
```
Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "qemuarm"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv5 thumb dsp"
TARGET_FPU           = "soft"
meta                 = "master:709b60a5e34a22aadb6dca7b888c010de8e6e4a4"
meta-oe              
meta-multimedia      
meta-python          = "master:3064819552cff0d6829b108e31aca9aa092c5f9d"
meta-ros             = "python3-manifest-change:6ddc0cc518ebcfdd6871774030bb5f91c09557d9"
```
```
Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "qemuarm"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv5 thumb dsp"
TARGET_FPU           = "soft"
meta                 = "master:709b60a5e34a22aadb6dca7b888c010de8e6e4a4"
meta-oe
meta-multimedia
meta-python          = "master:2f7de931885c1b9e63c4e4238f0f7ad1388e8b6d"
meta-ros             = "python3-manifest-change:6ddc0cc518ebcfdd6871774030bb5f91c09557d9"
```

**Comment by bulwahn** [comment]
CI is green; @rojkov This is really more your patch than mine; any comments? Once you update the git submodule in your intel-refkit layer to include this commit in meta-ros, you can drop the change in your layer.

**Comment by rojkov** [comment]
LGTM.
re refkit... it was rather dead than alive at least a couple of my assignments ago. Most probably it won't be updated.

**Comment by bulwahn** [comment]
re refkit... that is unfortunate; it was some motivation last year to know that refkit users are some users of meta-ros out there; possibly, the refkit users step up and maintain the refkit layer now.

**Pull request merged**
