### PR TITLE
librealsense: drop the recipe

### PR DESCRIPTION
**Pull request by rojkov**
As the main repository for the librealsense recipe now contains
fixes required for linking catkin-based packages against it
we can stop maintaining our own version of librealsense recipe.

Also this patch adapts realsense-camera recipe to link against
the non-catkin version of librealsense.

### CODE REVIEW

**Comment by bulwahn** [comment]
@rojkov I reviewed the commit and it looks good. Currently I do not have access to my build machine until March 13th, as I am on vacation. If there is no need to hurry, I suggest to postpone the merge until I am back from vacation; hopefully, we can also update the upstream status until then. If this pull request is a blocker for https://github.com/intel/intel-iot-refkit/pull/49, we can merge the pull request without me testing it, as it is limited to the realsense recipe. If the dependencies on the layers have changed, we should also mention that on the ROS wiki pages. By the way, I would prefer to see the ros recipes from the intel-iot-refkit repository in the meta-ros repository; two to three weeks ago, some user mentioned his interest in moveit recipes. What are the reasons that you wanted to provide them in the iot-refkit repository?

**Comment by rojkov** [comment]
@bulwahn No hurry, have your time! My priorities have been changed drastically for the next two weeks at least, so this PR can definitely wait.

I put MoveIt to intel-iot-refkit just for the sake of agility because in intel-iot-refkit we can't use libtinyxml and quite many packages including moveit have to be patched to be linkable against libtinyxml2. I wanted to maintain all the patches in one place. But I'd be happy to include the new recipes to meta-ros.

**Comment by bulwahn** [comment]
Okay, when I am back, I will do the usual testing and then merge the pull request. If you find time a pull request with moveit recipes is also always greatly appreciated from my side.

**Comment by rojkov** [comment]
@bulwahn Any chance to test this PR soon? Now it's getting more importance...

**Comment by rojkov** [comment]
Updated the realsense-camera recipe to 1.7.2 and force pushed.

**Comment by bulwahn** [comment]
@rojkov Sorry, I have been busy with other topic, and then used my meta-ros working time on the side track of this boost issue. I have two build machines (one in Fedora, the other is Ubuntu), but on both now fail with an issue on libgphoto2. This libgphoto2 issue is very, very probable not related to this pull request.

Hence, I cannot successfully build `bitbake realsense-camera`.
I tested now:
`bitbake librealsense camera-info-manager pcl-ros roscpp` without any issue.
`bitbake opencv-bridge` fails with libgphoto2 issue.

My build configuration is:
```
Build Configuration:
BB_VERSION        = "1.33.2"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:ac5c08ea00816852a712a8d7025bce7e865460ec"
meta-oe           
meta-python       
meta-multimedia   = "master:1dff2351aa6cdafa5a501e8956cb853ab17ed9ae"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-intel-realsense = "master:1d50cb5b82926f8e69a78999e9e8d2ffe2169897"
meta-ros          = "rojkov-drop-librealsense-v2:7f889a8a53fa3febb7e5c51f6f408ddec83bbf26"
```

I would suggest to simply merge your pull request, although I could not fully test it.
@rojkov Is that good for you?

**Comment by bulwahn** [comment]
After I added `PACKAGECONFIG_remove_pn-opencv = "gphoto2"` to my local.conf (to avoid the libgphoto2 issue #464), I could successfully build `bitbake realsense-camera core-image-ros-world` on this build configuration:
```
Build Configuration:
BB_VERSION        = "1.33.2"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "HEAD:ac5c08ea00816852a712a8d7025bce7e865460ec"
meta-oe           
meta-python       
meta-multimedia   = "master:1dff2351aa6cdafa5a501e8956cb853ab17ed9ae"
meta-qt4          = "master:2c7f8df9039be498f8a2232d1428adb7f4e5e800"
meta-intel-realsense = "master:1d50cb5b82926f8e69a78999e9e8d2ffe2169897"
meta-ros          = "rojkov-drop-librealsense-v2:7f889a8a53fa3febb7e5c51f6f408ddec83bbf26"
```

So, I will now merge this pull request with some more confidence 👍

**Pull request merged**
