### PR TITLE
{common} Add images for ros_base and perception

### PR DESCRIPTION
**Pull request by sgstreet**
Simple PR to add two addition images. One to build the ros_base variant and the other to build the perception variant.

### CODE REVIEW

**Comment by sgstreet** [comment]
@robwoolley Close as unnecessary?

**Comment by robwoolley** [comment]
How do you feel about using it as the basis for another image recipe?   Like ros-image-turtlebot3 or ros-image-virtualbot (targeting a virtual machine like QEMU or the cloud for rapid development?)

**Comment by sgstreet** [comment]
> How do you feel about using it as the basis for another image recipe? Like ros-image-turtlebot3 or ros-image-virtualbot (targeting a virtual machine like QEMU or the cloud for rapid development?)

Good idea, lets send this to the circular bin with the big delete key in the cloud.

**Comment by sgstreet** [comment]
Tossing this.

**Pull request closed without merging**
