### PR TITLE
Bump festival and speech-tools to version 2.4

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by alistair23** [comment]
Ping!

**Comment by alistair23** [comment]
Ping^2

**Comment by bulwahn** [comment]
Looks good to me. Indentation looks strange, probably due to a mixture and spacing and tabs.

I did not test it, though. I leave it to the new meta-ros maintainers to decide on merging this pull request.

**Comment by alistair23** [comment]
Thanks for the comments, I have fixed the spacing.

**Comment by herb-kuta-lge** [comment]
@alistair23 These packages are not required (as of yet) by any ROS 2 distros. Once we start work on ROS 1, we will upgrade the recipes in `meta-ros` for any platform packages its components depend on to the versions provided by Ubuntu **bionic**, just as we did for the ROS 2 platform packages. According to https://packages.ubuntu.com/bionic/festival and https://packages.ubuntu.com/bionic/speech-tools, **bionic** provides v2.5.0 of these packages. Is there a reason that you want to use v2.4?

**Comment by alistair23** [comment]
I'm not sure where they got the 2.5 version from, according to the [package home page](http://www.cstr.ed.ac.uk/projects/festival/) 2.4 is the latest release.

**Comment by herb-kuta-lge** [comment]
http://festvox.org/festival/ mentions v2.5 .

**Comment by alistair23** [comment]
It does, that is a different page then linked to by the Ubuntu package though. It's homepage links to the link I posted above which only mentions 2.4.

Either way, 2.4 was the latest that I could find at the time and that one that I tested. Even if there is a newer version, updating to 2.4 first will hopefully reduce the burden of later updating to 2.5.

**Comment by herb-kuta-lge** [comment]
> Either way, 2.4 was the latest that I could find at the time and that one that I tested

So you didn't use `apt install festival` to install it when developing? Or perhaps you're on Ubuntu **xenial**, where v2.4~release is what `apt` would install?

**Comment by alistair23** [comment]
I don't use Ubuntu.

I needed to bump the festival version in the meta-ros layer to 2.4 (maybe 2.5 would work as well). I'm not clear where apt and Ubuntu are involved.

**Comment by herb-kuta-lge** [comment]
Which ROS distro are you using?

**Comment by alistair23** [comment]
I'm using OpenEmbedded. meta-ros is a layer for the OpenEmbedded distro.

**Comment by herb-kuta-lge** [comment]
OK, then since the [README](https://github.com/ros/meta-ros/blob/3f4b9ff10264bbedb98f94eb415308279474bec4/README.md) says:

> This is a layer to provide ROS Indigo Igloo in an OpenEmbedded Linux system.

the ROS packages you are using are from the "Indigo Igloo" ROS distro. Please be aware that this distro has reached its EOL (see http://wiki.ros.org/Distributions) and will not be supported by v2 of meta-ros (the one with recipes generated by **superflore** -- see
https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme and https://discourse.ros.org/t/pre-announcement-a-new-home-for-meta-ros-under-ros-organization/9392).

**Comment by shr-project** [comment]
The old version currently in meta-ros doesn't even fetch, so this PR is already big improvement even if the version doesn't match with what Ubuntu is using.

LGTM

**Comment by herb-kuta-lge** [comment]
@alistair23 < How about retargeting this PR to the `[legacy]` branch that I've just introduced -- see https://github.com/ros/meta-ros/pull/630 ?

**Comment by alistair23** [comment]
Done, it is now targeting the legacy branch.

**Comment by shr-project** [comment]
thud-draft needs this as well, it should be cherry-picked there as well later.

**Comment by herb-kuta-lge** [comment]
> thud-draft needs this as well, it should be cherry-picked there as well later.

The plan is to upgrade their versions to the ones provided by Ubuntu **bionic** (v2.5.0) as part of adding support for **melodic**.

**Comment by alistair23** [comment]
Even if you want to upgrade to 2.5, this is a step in the right direction as it will reduce the diff as you won't have to upgrade from 2.3 -> 2.5 instead you can go from 2.4 -> 2.5.

**Comment by alistair23** [comment]
Is this ok to be merged?

**Comment by herb-kuta-lge** [comment]
I want to hold off until https://github.com/ros/meta-ros/pull/630 is merged, OK?

**Comment by alistair23** [comment]
Ok, that's fine

**Review by herb-kuta-lge — APPROVED** [review]
NOTE: I have not tested this.

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Please rebase to the current HEAD of [legacy].

**Comment by alistair23** [comment]
Done, it's rebased on legacy

**Review by herb-kuta-lge — APPROVED** [review]

**Pull request merged**
