### PR TITLE
{humble} Sync to files/humble/generated/cache.yaml as of 20240110002827

### PR DESCRIPTION
**Pull request by avanmalleghem**
Recipes generated by **superflore** for all packages in ROS distribution humble.

This pull request was generated by running the following command:

```
superflore-gen-oe-recipes --dry-run --no-branch --ros-distro humble --output-repository-path . --upstream-branch HEAD
```

### CODE REVIEW

**Comment by robwoolley** [comment]
Thanks, @avanmalleghem .  I will take a look at this soon.

**Review by robwoolley — COMMENTED** [review]
This fix is correct, however I will make a small adjustment.  In iron and rolling the generated recipes add ament-cmake-ros-native but humble does not.  Adding ament-cmake-ros-native is preferrable as it pulls in the other dependencies and keeps all the distros aligned.

Thanks!

**Comment by robwoolley** [comment]
@avanmalleghem May I get your sign-off on these fixes to attest that ? (see https://wiki.linuxfoundation.org/dco for details)  Don't worry about submitting the patches, a simple comment here is fine with the email address you would like me to use in the commit message to give you credit.

**Comment by avanmalleghem** [comment]
I agree to the DCO. 

Signed-off-by: Van Malleghem Antoine <a.vanmalleghem@gmail.com>

**Comment by robwoolley** [comment]
I merged in the control-toolbox fix.  I had difficulty seeing the build failures caused by the compiler warnings.  It is possible that the problems were fixed upstream.

Closing for now.  Please let me know if they persist.

**Pull request closed without merging**
