### PR TITLE
WIP: turtlebot3 support for Humble Kirkstone

### PR DESCRIPTION
**Pull request by robwoolley**
This successfully enables ignition and rviz2 to support building the turtlebot3 recipe on ROS Humble with
Yocto Kirkstone.

It requires meta-clang and meta-qt5.  The following also needs to be added to local.conf:

DISTRO_FEATURES:append = " x11 opengl vulkan polkit"
PACKAGECONFIG:append:pn-clang = "  libomp"
PACKAGECONFIG:append:pn-qtbase-native = " gui"
PACKAGECONFIG:append:pn-python3 = "  tk"

Tested on Raspberry Pi 4 using the shell mode with this kas script found in the build branch of meta-ros:
    oeros-kirkstone-humble-raspberrypi4-64.yml
    
Needs some work before I can merge this.  I am just submitting this PR for feedback from people eager to support the Turtlebot3, rviz, or Ignition/Gazebo.

Any feedback you can provide would be very helpful.  Especially enabling optional functionality in the GUI apps like CUDA and Optix.

### CODE REVIEW

**Comment by robwoolley** [comment]
With these changes, a build of bitbake ros-image-world --continue has the following results with only 55 failed tasks:

> NOTE: Tasks Summary: Attempted 30937 tasks of which 30866 didn't need to be rerun and 55 failed.
>                                                                                                                                                                                                                                             Summary: 55 tasks failed:
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2/recipes-graphics/nanogui/nanogui_git.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros-common/recipes-devtools/gazebo/ignition-physics5_5.0.0.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/phidgets-drivers/libphidget22_2.3.3-1.bb:do_patch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/recipes-devtools/libphidget22/libphidget22-upstream_1.13.20230224.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros-common/recipes-devtools/gazebo/ignition-sensors6_6.0.0.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/raspimouse2/raspimouse-msgs_1.1.2-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/qt-gui-core/qt-gui-cpp_2.2.3-2.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rqt/rqt-gui_1.1.7-1.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/mocap4r2/mocap4r2-control-msgs_0.0.7-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/mocap4r2-msgs/mocap4r2-msgs_0.0.5-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/apriltag/apriltag_3.4.0-1.bb:do_patch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/dbw-ros/ds-dbw-msgs_2.1.10-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/turtlebot4-simulator/turtlebot4-ignition-gui-plugins_1.0.2-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/usb-cam/usb-cam_0.8.0-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/aerostack2/as2-motion-reference-handlers_1.0.9-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/metro-nav/base2d-kinematics-msgs_0.2.0-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/aerostack2/as2-behavior_1.0.9-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/caret-trace/caret-msgs_0.5.0-6.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/ros2-kortex/kortex-api_0.2.2-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/mocap4r2/mocap4r2-robot-gt-msgs_0.0.7-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/recipes-support/libtins/libtins_4.4.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/flir-camera-driver/spinnaker-camera-driver_2.1.15-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/recipes-support/draco/draco_1.5.6.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/moveit/moveit-setup-framework_2.5.5-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/rcgcrd-spl-4_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/game-controller-spl-interfaces_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/clearpath-common/clearpath-platform_0.2.7-1.bb:do_install
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/gc-spl-interfaces_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/sick-scan-xd/sick-scan-xd_3.2.5-1.bb:do_populate_lic
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/r2r-spl/splsm-8_2.1.0-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/rcgcd-spl-14_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rqt-bag/rqt-bag_1.1.4-1.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rqt-graph/rqt-graph_1.3.0-1.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rmf-traffic-editor/rmf-traffic-editor-test-maps_1.6.2-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/aerostack2/as2-platform-crazyflie_1.0.9-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/data-tamer/data-tamer-cpp_0.9.3-2.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/sick-scan-xd/sick-scan-xd_3.2.5-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/nmea-hardware-interface/nmea-hardware-interface_0.0.1-3.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/aerostack2/as2-behavior-tree_1.0.9-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/tuw-geometry/tuw-geometry_0.1.1-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/generate-parameter-library/cmake-generate-parameter-module-example_0.3.8-3.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/etsi-its-messages/etsi-its-rviz-plugins_2.0.1-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/ortools-vendor/ortools-vendor_9.9.0-3.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/wrapyfi-ros2-interfaces/wrapyfi-ros2-interfaces_0.4.30-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/rcgcrd-spl-4-conversion_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/psdk-ros2/psdk-wrapper_1.1.1-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/unitree-ros/unitree-ros_1.1.0-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rqt-robot-steering/rqt-robot-steering_1.0.0-4.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/rcgcd-spl-14-conversion_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/hri/pyhri_2.3.0-1.bb:do_compile
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/rqt-moveit/rqt-moveit_1.0.1-3.bb:do_package
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/gc-spl_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/gc-spl-2022_2.1.0-1.bb:do_fetch
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/reach-ros/reach-ros_1.4.0-1.bb:do_configure
>   <PROJECT_DIR>/build/../layers/meta-ros/meta-ros2-humble/generated-recipes/gc-spl/game-controller-spl_2.1.0-1.bb:do_fetch
> Summary: There were 15 WARNING messages.
> Summary: There were 73 ERROR messages, returning a non-zero exit code.

**Comment by whni** [comment]
Wondering if I just turtlebot3 recipe into my own image recipe, will it work through GUI?

**Comment by robwoolley** [comment]
> Wondering if I just turtlebot3 recipe into my own image recipe, will it work through GUI?

Right now it is building X11 and the Qt framework, but you would need to add an actual desktop GUI.

The [meta-qt5-extra](https://github.com/schnitzeltony/meta-qt5-extra) layer has both KDE and LxQt.  For a Raspberry Pi it would probably be best to go with LxQt.

**Comment by bchoineubility** [comment]
great !!

**Comment by whni** [comment]
Hi @robwoolley 

I am also trying to build ros-image-turtlebot3-all on humble and it seems there are more unsupported recipes in    
 `packagegroup-ros-turtlebot3-core` and `packagegroup-ros-turtlebot3-extended`. Could you please also check?

Thank you


=================
checked some packages which have problems:
1. raspicam-node -> camera-ros?
2. rosserial might need to migrate to micro ros
3. tf -> tf2
4. slam-karto not available
5. teleop-twist-joy build error
6. amcl -> nav2-amcl
7. gmapping not available
8. laser-proc build error
9. map-server -> nav2-map-server
10. move-base not available
11. navigation -> navigation2
12. rgbd-launch not available
13. turtlebot3-applications not available
14. turtlebot3-applications-msgs not available
15. turtlebot3-autorace not available

Is it possible that we can fix these too?

**Comment by robwoolley** [comment]
The packagegroup for ros-turtlebot3-core and extended was only ever intended for ROS 1:

https://github.com/ros/meta-ros/blob/aaee06540d1e2f6b27493c11f82a5c9a16808dca/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-turtlebot3-core.bb#L38

I'm excited to see that you are working out the mapping to update it.

I found a comment that confirmed that camera_ros is the replacement for raspicam_node.

I suggest instead of trying to literally map each item, you might find it easier to get the list of packages from the "apt install" lines of the Humble version of the Turtlebot3 Manual: https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/

If you want to run the GUI apps on the RPi as well you will need to get the list of packages from the "apt install" lines of the PC Setup section as well: https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/#pc-setup

**Comment by whni** [comment]
Hi @robwoolley 

Actually GUI running directly RPi is not a must for me. I am just wondering what is the minimum set of recipe that I need to run the basic robot functions on turtlebot3 using humble, including 
1) camera
2) lidar -> slam -> navigation
3) remote control (teleop)

There are some packages in [turtlebot3](https://github.com/ros/meta-ros/blob/kirkstone/meta-ros2-humble/generated-recipes/turtlebot3/turtlebot3_2.1.5-1.bb#L31) recipe, for which you have fixed the dependency issue here so I can add it to my image.

However, for those in packagegroup-ros-turtlebot3-core and packagegroup-ros-turtlebot3-extended, are they necessary for the basic functions that I mentioned above?

Thank you so much!

PS: we are trying to build everything from source so apt might not a good way (but ok for test)

**Comment by robwoolley** [comment]
The packagegroup-ros-turtlebot3-core and packagegroup-ros-turtlebot3-extended provide the packages required for ROS 1.  They aren't relevant to ROS 2.

The best source of information for ROS 2 would be the TurtleBot3 manual by ROBOTIS.  If you look at the "apt install" lines you can see the names of the packages that need to be added to the base image for Raspberry Pi.   

Once you've figured out what packages you need, you may add them to the IMAGE_INSTALL:append line of conf/local.conf.  If everything works once you've tested it on your Raspberry Pi, then you may update the packagegroup-ros-turtlebot3-* recipes so you don't have to manually add them to local.conf every time.

Hope that helps

**Comment by whni** [comment]
Great! Perfect idea! Let me try :)

Hopefully this pull request can be completed soon since my local hacks remove some essential components such as slam-toolbox from turtlebot3-navigation2 -> nav2-bringup to resolve the build error. I am worrying that my hack might break some functions, potentially

Anyway, thank you so much for help!

**Comment by whni** [comment]
Hi @robwoolley 

I am also trying to build colcon into my image so that I can try runtime ros compilation. However, the default oe build derived from ros-image-core or core-image-sato do not have the build tools such as cmake, make, etc.

Do you know any recipe name that contains a build tool set, like build-essential on ubuntu?

By following the setup on https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/#sbc-setup to build https://github.com/ROBOTIS-GIT/ld08_driver.git on the robot device, before build starts, it also threw some errors like:
```
colcon.colcon_core.entry_point ERROR Exception loading extension 'colcon_core.event_handler.desktop_notification': The 'notify2; sys_platform == "linux"' distribution was not found and is required by the application
```
notify2.py looks like some file generated in the package [python3-colcon-notification](https://github.com/ros/meta-ros/blob/kirkstone/meta-ros-common/recipes-devtools/colcon/python3-colcon-notification_0.2.13.bb). Is this package good for use on humble?

Thank you so much!


[Question]
Is on-device (robot) build recommended for yocto project? It looks to me that `colcon` is usually good on the robot machine that runs ubuntu.
As for yocto, are we expect to only use recipe way to add a package? not using colcon

**Comment by whni** [comment]
Hi @robwoolley I checkout out this commit locally and still found ogre package has some build error on imgui:
```
| ----------------------------------------------------------------------------
| 
| -- Configuring done
| CMake Error at Components/Overlay/CMakeLists.txt:42 (add_library):
|   Cannot find source file:
| 
|     /home/weihengni/Projects/robotpi/build/BUILD-robotpi-humble-kirkstone/work/cortexa72-robotpi-linux/ogre/1.12.12-r0/build/imgui-1.79/imgui.cpp
| 
|   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
|   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
| 
| 
| CMake Error at Components/Overlay/CMakeLists.txt:42 (add_library):
|   No SOURCES given to target: OgreOverlay
| 
| 
| CMake Generate step failed.  Build files cannot be regenerated correctly.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/weihengni/Projects/robotpi/build/../layers/meta-ros/meta-ros-common/recipes-devtools/ogre/ogre_1.12.12.bb:do_configure) failed with exit code '1'
```

My workaround is to disable imgui feature
```
EXTRA_OECMAKE_RVIZ_OGRE_VENDOR:append = " -DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI:BOOL=FALSE"
```
Do you have any proper solution for this?

**Comment by whni** [comment]
One more issues with this commit:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ignition-cmake2-vendor : Depends: ignition-cmake2 but it is not installable
 slam-toolbox : Depends: ceres-solver but it is not installable
E: Unable to correct problems, you have held broken packages.

DEBUG: Python function do_rootfs finished
```

`bitbake ignition-cmake2` or `ceres-solver` is good. This only happens during image recipe build with `IMAGE_INSTALL:append = packagegroup-ros-turtlebot3-core`

I have to remove them from ROS_EXEC_DEPENDS in bbappend file but not sure if this will impact the runtime function

**Comment by whni** [comment]
Hi @robwoolley , were you able to check my questions above:
1. colcon support on humble
2. imgui support in ogre
3. ignition-cmake2 and ceres-solver dependency error

Still wondering when this commit will be available on the official humble branch. Thank you so much!

**Comment by robwoolley** [comment]
> Hi @robwoolley , were you able to check my questions above:
> 
> 1. colcon support on humble

This is something that was worked on previously, however I haven't had a chance to try it myself: https://github.com/ros/meta-ros/issues/716

> 2. imgui support in ogre

I don't recall seeing this failure when I was working on Humble+Kirkstone.  However, lately I have been focused on building ogre-next for Rolling for the upcoming Jazzy Jalisco release.

> 3. ignition-cmake2 and ceres-solver dependency error

I recall that some of the packages were not installable because they only produced ${PN}-dev packages.  The trick there was to remove any runtime dependency on them.  eg  meta-ros2-humble/recipes-bbappends/navigation2/nav2-smac-planner_1.1.14-1.bbappend

```
# Doesn't need runtime dependency on ceres-solver
ROS_EXEC_DEPENDS:remove = "ceres-solver"
```
That is likely what is happening here.

> Still wondering when this commit will be available on the official humble branch. Thank you so much!

I don't intend to merge the commit until I can verify that the GUI comes up on a running system.  I intend to use LxQt for that and submitted some fixes upstream to make sure that one can build a LxQt desktop: https://github.com/schnitzeltony/meta-qt5-extra/pull/96  ( If it helps you can use the GitHub command-line tool to check out a PR.  You can also just checkout the commit id directly if that is easier. )

Since the Jazzy Jalisco release is on May 23rd, my best estimate is that it would be sometime in June.

Our regular working group meeting is on Monday if you'd be interested in attending to ask any questions live.
https://discourse.ros.org/t/ros-openembedded-community-group-meeting-17-2024-05-13-3pm-utc/37638/1

**Comment by whni** [comment]
Thank you so much for the update.
1. colcon support on humble: please help verify it on humble. What I did was to add these to the image:
image

However it threw the [error](https://github.com/ros/meta-ros/pull/1140#issuecomment-2089173458)

2. I will continue to use the hack to remove the depenency: imgui in ogre, ceres-solver and ignition-cmake2
3. And yes, I can check out the PR as a temporary workaround, while expecting the official humble branch patch to be available in June.

Thank you so much for the help! 

As for the meeting, I am unable to join due to conflict, but anyway thanks a lot for the invitation!

**Comment by bchoineubility** [comment]
Hi 

I have no build issue for ogre with enabling imgui by adding following dependencies to the bbapend file.

```
 20 EXTRA_OECMAKE_RVIZ_OGRE_VENDOR = " \
 21     -DOGRE_BUILD_COMPONENT_OVERLAY:BOOL=ON \
 22     -DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI:BOOL=ON \
 23 "
 24
 25
 26 DEPENDS += " \
 27   libxaw \
 28 "

 30 inherit cmake_qt5
 37 FILES:${PN}-dev += " /usr/lib/OGRE/Samples/*"
 38 INSANE_SKIP:${PN} += " file-rdeps"

```
Is there anything I miss for build ?

My ogre version is ogre_1.12.8.

BR,
Mark

**Comment by whni** [comment]
Hi @bchoineubility , I am using the current kirkstone branch with [ogre_1.12.12.bb](https://github.com/ros/meta-ros/blob/kirkstone/meta-ros-common/recipes-devtools/ogre/ogre_1.12.12.bb). 

It does not explicitly indicate any DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI flag but this leads to my build [error](https://github.com/ros/meta-ros/pull/1140#issuecomment-2096619532). I have to manually set it to FALSE.

You could try to setup this config: https://github.com/ros/meta-ros/blob/build/kas/oeros-kirkstone-humble-raspberrypi4-64.yml , and try `bitbake ogre`. That might repro my issue

**Comment by bchoineubility** [comment]
> Hi @bchoineubility , I am using the current kirkstone branch with [ogre_1.12.12.bb](https://github.com/ros/meta-ros/blob/kirkstone/meta-ros-common/recipes-devtools/ogre/ogre_1.12.12.bb).
> 
> It does not explicitly indicate any DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI flag but this leads to my build [error](https://github.com/ros/meta-ros/pull/1140#issuecomment-2096619532). I have to manually set it to FALSE.
> 
> You could try to setup this config: https://github.com/ros/meta-ros/blob/build/kas/oeros-kirkstone-humble-raspberrypi4-64.yml , and try `bitbake ogre`. That might repro my issue

Well, I am not sure, but, you may have dependency for a package can not generate some source codes because it could not have native packages to use generating source codes in building the target package.

I recommend to check packages ogre depend individually and CMake files in them. 

BR,
Mark

**Comment by whni** [comment]
@bchoineubility I have investigated via downloading the same ogre package and build on my dev machine out of oe environment. The process has no issue. During the configuration, an [imgui.tar.gz](https://github.com/OGRECave/ogre/blob/master/Components/Overlay/CMakeLists.txt#L25) file will be downloaded and uncompressed. However, in oe, the file was empty during bitbake ogre process.

Could you try to build and see if you have the same issue?

It seems this is an known issue since ogre 1.12.3. I am so surprised that all of you have not encountered it: https://github.com/OGRECave/ogre/issues/1332

**Comment by bchoineubility** [comment]
> @bchoineubility I have investigated via downloading the same ogre package and build on my dev machine out of oe environment. The process has no issue. During the configuration, an [imgui.tar.gz](https://github.com/OGRECave/ogre/blob/master/Components/Overlay/CMakeLists.txt#L25) file will be downloaded and uncompressed. However, in oe, the file was empty during bitbake ogre process.
> 
> Could you try to build and see if you have the same issue?
> 
> It seems this is an known issue since ogre 1.12.3. I am so surprised that all of you have not encountered it: [OGRECave/ogre#1332](https://github.com/OGRECave/ogre/issues/1332)

Hi, 

I have no issue for it. following is my build dir and have imgui.tar.gz as expected.

```
bchoi@ubuntu-20:~/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a_tegra234-oe4t-linux/ogre/1.12.8-r0/build$ ls
api  build.ninja  CMake           CMakeDoxyfile.in            CMakeFiles           Components         CPackSourceConfig.cmake  Docs             freetype-2.10.1.tar.gz  imgui-1.73    include  install_manifest.txt  LICENSE.txt  pkgconfig  pugixml-1.10         RenderSystems  Tools        zziplib-0.13.71
bin  cmake        CMakeCache.txt  CMakeDoxygenDefaults.cmake  cmake_install.cmake  CPackConfig.cmake  Dependencies             freetype-2.10.1  html.cfg                imgui.tar.gz  inst     lib                   OgreMain     PlugIns    pugixml-1.10.tar.gz  Samples        version.txt  zziplib-0.13.71.tar.gz
bchoi@ubuntu-20:~/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a_tegra234-oe4t-linux/ogre/1.12.8-r0/build$
```

BR,
Mark

**Comment by whni** [comment]
Hi @bchoineubility could you please checkout the kirkstone branch and use humble config to take a look? Your build config is different from us. What we found is that the official default kirkstone + humble build has this issue?

@robwoolley could you also take a try? Thank you so much!

`bitbake ogre` with kirkstone branch + https://github.com/ros/meta-ros/blob/build/kas/oeros-kirkstone-humble-raspberrypi4-64.yml

Btw, the build can be successful if I manually checkout the source code and do cmake configure such as via devtool

**Comment by robwoolley** [comment]
@whni I used the instructions here: https://github.com/ros/meta-ros/tree/build/kas to create a build environment, then used kas shell to go into it.  From there, I used "gh pr checkout 1140" to grab the changes from this PR.  Then I went back to the builddir to add the following lines to conf/local:

```
DISTRO_FEATURES:append = " x11 opengl vulkan polkit"
PACKAGECONFIG:append:pn-clang = " libomp"
PACKAGECONFIG:append:pn-qtbase-native = " gui"
PACKAGECONFIG:append:pn-python3 = " tk"

```
and built ogre: `bitbake ogre`

One of the differences is that it is being downloaded by CMake (instead of by bitbake fetcher).  The mechanism is here:

Components/Overlay/CMakeLists.txt
```
if(OGRE_BUILD_COMPONENT_OVERLAY_IMGUI)
  set(IMGUI_DIR "${PROJECT_BINARY_DIR}/imgui-1.79" CACHE PATH "")
  if(NOT EXISTS ${IMGUI_DIR})
    message(STATUS "Downloading imgui")
    file(DOWNLOAD
        https://github.com/ocornut/imgui/archive/v1.79.tar.gz
        ${PROJECT_BINARY_DIR}/imgui.tar.gz)
    execute_process(COMMAND ${CMAKE_COMMAND}
        -E tar xf imgui.tar.gz WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
  endif()
  list(APPEND SOURCE_FILES
    ${IMGUI_DIR}/imgui.cpp
    ${IMGUI_DIR}/imgui_draw.cpp
    ${IMGUI_DIR}/imgui_widgets.cpp
    ${IMGUI_DIR}/imgui_demo.cpp
    ${IMGUI_DIR}/misc/freetype/imgui_freetype.cpp)
else()
    list(REMOVE_ITEM SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/OgreImGuiOverlay.cpp")
endif()
```

I suspect that your corporate firewall may be preventing it from accessing the file somehow.  (Perhaps using an alternative root CA to intercept the HTTPs connection?)  A better solution would be to add imgui as a SRC_URI in the ogre recipe and have it extract itself to a directory in ${S} and then set IMGUR_DIR to point to it.   This is an ideal, long-term fix anyway as it helps ensure the provenance of the code, reproducible builds, and building without connection to the Internet.

Hope that helps!

**Comment by robwoolley** [comment]
I accidentally merged this by mistake when experimenting with "gh pr merge --rebase" thinking it only worked locally.   I have since reset the kirkstone branch back to its previous state.

**Comment by whni** [comment]
Hi @robwoolley , yeah, I followed the exactly same steps as you posted here and I also figured out the mechanism of cmake downloader (please see my [reply](https://github.com/ros/meta-ros/pull/1140#issuecomment-2106651006)). 

The weird thing is that the download process can succeed if I manually checkout the ogre source code and do cmake configure with the same flags as bitbake passes. I can also download imgui.tar.gz through some other tools such as wget, which means I think there should not be any firewall issue. The problem only happens during bitbake process. 

Anyway, let me check more to see if I can find any more clue.

Also thank you for merging the commit!

**Comment by bchoineubility** [comment]
> Hi @robwoolley , yeah, I followed the exactly same steps as you posted here and I also figured out the mechanism of cmake downloader (please see my [reply](https://github.com/ros/meta-ros/pull/1140#issuecomment-2106651006)).
> 
> The weird thing is that the download process can succeed if I manually checkout the ogre source code and do cmake configure with the same flags as bitbake passes. I can also download imgui.tar.gz through some other tools such as wget, which means I think there should not be any firewall issue. The problem only happens during bitbake process.
> 
> Anyway, let me check more to see if I can find any more clue.
> 
> Also thank you for merging the commit!

I think you would have network issue. you can check your ip address is sole and if you use container build you can also check containers running.

BR,
Mark

**Comment by whni** [comment]
Hi @bchoineubility I think it does not make sense for the network issue. It’s a genuine Ubuntu dev machine and we already tested the cmake download independently. It should be something wrong during bitbake process

**Comment by bchoineubility** [comment]
> Hi @bchoineubility I think it does not make sense for the network issue. It’s a genuine Ubuntu dev machine and we already tested the cmake download independently. It should be something wrong during bitbake process

Hi my meta-ros branch is kirkstone-next and commit id is 950bcc85ad7a223252664688de71f9000cfeb61d"

I hope that helps.

**Comment by whni** [comment]
> > Hi @bchoineubility I think it does not make sense for the network issue. It’s a genuine Ubuntu dev machine and we already tested the cmake download independently. It should be something wrong during bitbake process
> 
> Hi my meta-ros branch is kirkstone-next and commit id is [950bcc8](https://github.com/ros/meta-ros/commit/950bcc85ad7a223252664688de71f9000cfeb61d)"
> 
> I hope that helps.

Hi @bchoineubility thanks for sharing your setup. However we want to get a good dev environment from scratch on Ubuntu 22.04 with the stable version of humble + kirkstone, so that we can copy the setup to a broader audiences. Could you explain the difference between kirkstone and its next version? Also I think it’s better to repro the issue with the same setup as ours.

I understand that you might not have enough bandwidth. We will try by ourselves for now but stick to the kirkstone and humble

**Comment by robwoolley** [comment]
Here is a quick test to try.   Set the following in your local.conf to see if it changes anything:
BB_NO_NETWORK="0"

This part of the documentation indicates that there may also be extra measures preventing network access from tasks aside from do_fetch: https://docs.yoctoproject.org/migration-guides/migration-4.0.html?highlight=network#fetching-changes

Whether this works or not, my suggestion from before should be implemented anyway to avoid unexpected downloads outside of do_fetch: "A better solution would be to add imgui as a SRC_URI in the ogre recipe and have it extract itself to a directory in ${S} and then set IMGUR_DIR to point to it"

Cheers,
Rob

**Comment by whni** [comment]
@robwoolley Hi! I just realized that we are misaligned on what was wrong in our environment. The error happens during the `do_configure` instead of `do_fetch`. I can see the ogre source code was fetched and it proceeded to the imgui download step as indicated in https://github.com/OGRECave/ogre/blob/master/Components/Overlay/CMakeLists.txt#L25. However, the imgui.tar.gz seems corrupted:
image

Then I cd to the source code directory `git`, `mkdir build`, `cd build`, and run `cmake ..` directly here, the whole process is successfully and I can see the good imgui.tar.gz
image

Here is the summary:
1. bitbake do_fetch succeeds, but cmake imgui download fails
2. in the source directory from fetched by bitbake, manual cmake imgui succeeds

**Comment by bchoineubility** [comment]
I had experienced similar issue on the Ubuntu by mismatching hash value for a file on the package.  when I tried to download package directly it, hash value is correct but, apt didn't.

**Comment by whni** [comment]
> I had experienced similar issue on the Ubuntu by mismatching hash value for a file on the package. when I tried to download package directly it, hash value is correct but, apt didn't.

Hi Mark, this is not from apt. It was during the cmake configure and fetched by the cmake downloader. And if I manually trigger the cmake process, the file is also good. All these symptoms never indicates a network or hash mismatch issue. It looks so weird it only happens with the cmake during bitbake process

**Comment by whni** [comment]
Ogre issue is fixed via a cmakelist patch, although a bit ugly:

ogre_%.bbappend
```
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI += "https://github.com/ocornut/imgui/archive/v1.79.tar.gz;protocol=https;name=imgui"
SRC_URI += "file://0001-Components-Overlay-search-OE-downloaded-imgui-direct.patch"

SRC_URI[imgui.sha256sum] = "f1908501f6dc6db8a4d572c29259847f6f882684b10488d3a8d2da31744cd0a4"
```

0001-Components-Overlay-search-OE-downloaded-imgui-direct.patch
```
---
 Components/Overlay/CMakeLists.txt | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/Components/Overlay/CMakeLists.txt b/Components/Overlay/CMakeLists.txt
index 64a2a4ed7..46a8880b4 100644
--- a/Components/Overlay/CMakeLists.txt
+++ b/Components/Overlay/CMakeLists.txt
@@ -20,6 +20,10 @@ file(GLOB SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
 
 if(OGRE_BUILD_COMPONENT_OVERLAY_IMGUI)
   set(IMGUI_DIR "${PROJECT_BINARY_DIR}/imgui-1.79" CACHE PATH "")
+  set(OE_IMGUI_DIR "${PROJECT_BINARY_DIR}/../imgui-1.79" CACHE PATH "")
+  if(EXISTS ${OE_IMGUI_DIR})
+    file(RENAME ${OE_IMGUI_DIR} ${IMGUI_DIR})
+  endif()
   if(NOT EXISTS ${IMGUI_DIR})
     message(STATUS "Downloading imgui")
     file(DOWNLOAD
```

**Comment by robwoolley** [comment]
I have posted a new revision the patches here: https://github.com/ros/meta-ros/pull/1150

**Pull request merged**
