### PR TITLE
[dunfell] libyaml-vendor: use platform libyaml to unblock rpm packaging

### PR DESCRIPTION
**Pull request by shr-project**
* fixes:
  https://github.com/ros/meta-ros/issues/701
  https://github.com/ros/meta-ros/issues/688

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

### CODE REVIEW

**Comment by vguen** [comment]
Looks nice for #701 👍 
When trying to test this branch, I encounter the following error
```
WARNING: libyaml-vendor-1.0.2-1-r0 do_patch: Fuzz detected:

Applying patch 0001-CMakeLists.txt-use-platform-libyaml-when-available-i.patch
patching file CMakeLists.txt
Hunk #1 succeeded at 65 with fuzz 1 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify libyaml-vendor
    devtool finish --force-patch-refresh libyaml-vendor <layer_path>

Don't forget to review changes done by devtool!

WARNING: libyaml-vendor-1.0.2-1-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]
ERROR: rcl-yaml-param-parser-1.1.5-1-r0 do_patch: Command Error: 'quilt --quiltrc /workdir/build/tmp/work/aarch64-droneos-linux/rcl-yaml-param-parser/1.1.5-1-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-CMakeLists.txt-use-pkg-config-to-find-yaml.patch
patching file CMakeLists.txt
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- rejects in file CMakeLists.txt
Patch 0001-CMakeLists.txt-use-pkg-config-to-find-yaml.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/aarch64-droneos-linux/rcl-yaml-param-parser/1.1.5-1-r0/temp/log.do_patch.1017
ERROR: Task (/workdir/source/poky/meta-ros/meta-ros2-foxy/generated-recipes/rcl/rcl-yaml-param-parser_1.1.5-1.bb:do_patch) failed with exit code '1'
```

And looking at the sources of the `CMakeListst.txt` that is patched

```
     1	cmake_minimum_required(VERSION 3.5)
     2
     3	project(rcl_yaml_param_parser)
     4
     5	find_package(ament_cmake_ros REQUIRED)
     6	find_package(rcutils REQUIRED)
     7	find_package(libyaml_vendor REQUIRED)
     8
     9	# Default to C++14
    10	if(NOT CMAKE_CXX_STANDARD)
```

it does not corresponde to the code of the patch [0001-CMakeLists.txt-use-pkg-config-to-find-yaml.patch](https://github.com/ros/meta-ros/pull/703/files#diff-b98c72356436cfa1ab403a65309cf72d)

**Comment by shr-project** [comment]
Thanks for test. What OE release were you using? Was it dunfell? I'll retest.

**Comment by shr-project** [comment]
I've updated the PR, now it should apply at least for dunfell+foxy without any other changes I have locally.

**Comment by vguen** [comment]
I am on `dunfell` with `foxy` release.
I still have some problem
```
ERROR: rcl-1.1.5-1-r0 do_configure: Execution of '/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/temp/run.do_configure.2835' failed with exit code 1:
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-droneos-linux/aarch64-droneos-linux-gcc
-- Check for working C compiler: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-droneos-linux/aarch64-droneos-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-droneos-linux/aarch64-droneos-linux-g++
-- Check for working CXX compiler: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/aarch64-droneos-linux/aarch64-droneos-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake_ros: 0.9.0 (/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
-- Found PythonInterp: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.8.2", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found rcl_interfaces: 1.0.0 (/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
CMake Warning at /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_generator_c/cmake/rosidl_generator_cConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:11 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/rcl_interfacesConfig.cmake:41 (include)
  CMakeLists.txt:7 (find_package)


-- Found OpenSSL: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1g")
-- Found FastRTPS: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/include
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rcl_yaml_param_parser: 1.1.5 (/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_yaml_param_parser/cmake)
CMake Error at /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/libyaml_vendor/cmake/ament_cmake_export_dependencies-extras.cmake:22 (find_package):
  By not providing "Findyaml.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "yaml", but
  CMake did not find one.

  Could not find a package configuration file provided by "yaml" with any of
  the following names:

    yamlConfig.cmake
    yaml-config.cmake

  Add the installation prefix of "yaml" to CMAKE_PREFIX_PATH or set
  "yaml_DIR" to a directory containing one of the above files.  If "yaml"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/libyaml_vendor/cmake/libyaml_vendorConfig.cmake:41 (include)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_yaml_param_parser/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/rcl_yaml_param_parser/cmake/rcl_yaml_param_parserConfig.cmake:41 (include)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/temp/log.do_configure.2835
```

For a bit of context, I am building `packagegroup-ros2-demos`

**Comment by vguen** [comment]
For `rosidl_adapter` I tried to add

```
diff --git a/meta-ros2-foxy/generated-recipes/rcl/rcl_1.1.5-1.bb b/meta-ros2-foxy/generated-recipes/rcl/rcl_1.1.5-1.bb
index 802fba6..ead756a 100644
--- a/meta-ros2-foxy/generated-recipes/rcl/rcl_1.1.5-1.bb
+++ b/meta-ros2-foxy/generated-recipes/rcl/rcl_1.1.5-1.bb
@@ -21,6 +21,7 @@ ROS_BUILD_DEPENDS = " \
     rcl-yaml-param-parser \
     rcutils \
     rmw-implementation \
+    rosidl-adapter \
     rosidl-runtime-c \
     tracetools \
 "
```

I do not have problem with that but still with `/workdir/build/tmp/work/aarch64-droneos-linux/rcl/1.1.5-1-r0/recipe-sysroot/usr/share/libyaml_vendor/cmake/ament_cmake_export_dependencies-extras.cmake`

For that one it seems like the file tries to `find_package(yaml)` where it should use what you did in your patch `pkg_check_module(yaml REQUIRED yaml-0.1)`.
If so that means we should patch either
- the macro `ament_export_libraries(yaml)` or `ament_export_dependencies(yaml)`

---

Edit:

Indedd it seems to be in https://github.com/ament/ament_cmake/blob/master/ament_cmake_export_dependencies/cmake/ament_export_dependencies.cmake

**Comment by shr-project** [comment]
I've dropped ament_export_dependencies(yaml) in foxy's libyaml-vendor patch to match with what I did in eloquent.

**Comment by vguen** [comment]
Thanks I was looking to that too, I will try to see if it works.

**Comment by vguen** [comment]
Everythings build 🎉 Thank you for your help !
I hope this will be merge soon !
Indeed fix #701

**Pull request merged**
